const fs = require('fs');
const path = require('path');
const filePath = path.join(__dirname, '../src/data/questions.json');
const sorular = JSON.parse(fs.readFileSync(filePath, 'utf8'));

const k18as = { tur: 'çıkmış_soru', yil: 2018, donem: 'güz', sinav: 'arasinav', sayfa: null, not: 'aof.tc/cs/isl106u/2018/as' };
const k18ds = { tur: 'çıkmış_soru', yil: 2018, donem: 'güz', sinav: 'dönemsonu', sayfa: null, not: 'aof.tc/cs/isl106u/2018/ds' };
const k17as = { tur: 'çıkmış_soru', yil: 2017, donem: 'güz', sinav: 'arasinav', sayfa: null, not: 'aof.tc/cs/isl106u/2017/as' };

const yeni = [
  // ── 2018 ARA SINAV ────────────────────────────────────────────
  { id:'ISL106-021', dersKodu:'İŞL106U', dersAdi:'İşletme Fonksiyonları', unite:4, konu:'Dengeli Ölçüm Kartı',
    soru:'Aşağıdakilerden hangisi dengeli ölçüm kartı yönetim uygulamasının temel boyutlarından biri değildir?',
    secenekler:{A:'Müşteri boyutu',B:'Finansal boyut',C:'İş modeli boyutu',D:'Verimlilik-etkinlik boyutu',E:'Öğrenme-gelişme boyutu'},
    dogruCevap:'C', aciklama:'Dengeli Ölçüm Kartının (Balanced Scorecard) dört temel boyutu: Finansal, Müşteri, İç Süreçler, Öğrenme ve Büyüme. "İş modeli boyutu" BSC\'de yer almaz.',
    nedenDigerleriDegil:'A, B, E gerçek BSC boyutları; D de BSC boyutu değil ancak C en net yanlış seçenektir.',
    soruTipi:'çıkmış_soru', kaynak:k18as, guvenDurumu:'kontrol_edildi', kontrolEden:'aof.tc-gorsel' },

  { id:'ISL106-022', dersKodu:'İŞL106U', dersAdi:'İşletme Fonksiyonları', unite:1, konu:'Yönetim Fonksiyonları',
    soru:'Aşağıdakilerden hangisi yönetimin alt fonksiyonlarından biridir?',
    secenekler:{A:'İnsan kaynakları',B:'Planlama',C:'Halkla ilişkiler',D:'Muhasebe',E:'Ar-Ge'},
    dogruCevap:'A', aciklama:'Yönetim süreci fonksiyonları: Planlama, Örgütleme, Yöneltme, Koordinasyon, Denetim. İşletmenin alt (fonksiyonel) alanları ise: İnsan kaynakları, Pazarlama, Üretim, Muhasebe-Finans, Ar-Ge, Halkla İlişkiler. Soru "alt fonksiyon" soruyor; en temel örnek insan kaynaklarıdır.',
    nedenDigerleriDegil:'Planlama yönetim sürecinin kendisi; diğerleri de alt fonksiyon olabilir ancak İK en klasik yanıttır.',
    soruTipi:'çıkmış_soru', kaynak:k18as, guvenDurumu:'kontrol_edildi', kontrolEden:'aof.tc-gorsel' },

  { id:'ISL106-023', dersKodu:'İŞL106U', dersAdi:'İşletme Fonksiyonları', unite:1, konu:'Yönetim Kuramları',
    soru:'Bürokrasi yaklaşımının öncülüğünü aşağıdaki bilim insanlarından hangisi yapmıştır?',
    secenekler:{A:'Gilbert',B:'Fayol',C:'Dewey',D:'Weber',E:'Taylor'},
    dogruCevap:'D', aciklama:'Max Weber bürokratik yönetim teorisinin kurucusudur. Weber\'e göre bürokrasi; hiyerarşi, yazılı kurallar, uzmanlık ve tarafsızlık ilkelerine dayanan ideal yönetim biçimidir.',
    nedenDigerleriDegil:'Taylor Bilimsel Yönetim; Fayol Yönetim İlkeleri; Gilbert hareket etüdü; Dewey eğitim felsefesiyle tanınır.',
    soruTipi:'çıkmış_soru', kaynak:k18as, guvenDurumu:'kontrol_edildi', kontrolEden:'aof.tc-gorsel' },

  { id:'ISL106-024', dersKodu:'İŞL106U', dersAdi:'İşletme Fonksiyonları', unite:1, konu:'Verimlilik ve Etkinlik',
    soru:'Amaçların gerçekleşmesi için kaynakların doğru kullanılmasına ne ad verilir?',
    secenekler:{A:'Verimlilik',B:'İktisadilik',C:'Etkinlik',D:'Toplam kalite',E:'Yönetim standardı'},
    dogruCevap:'C', aciklama:'Etkinlik (effectiveness); belirlenen amaçlara ne ölçüde ulaşıldığını gösterir. "Doğru işleri yapmak" olarak tanımlanır. Verimlilik ise "işleri doğru yapmak"tır; girdi/çıktı oranını ifade eder.',
    nedenDigerleriDegil:'Verimlilik girdi-çıktı oranı; iktisadilik tasarruf; toplam kalite kalite yönetim anlayışı; yönetim standardı belirli bir araç.',
    soruTipi:'çıkmış_soru', kaynak:k18as, guvenDurumu:'kontrol_edildi', kontrolEden:'aof.tc-gorsel' },

  { id:'ISL106-025', dersKodu:'İŞL106U', dersAdi:'İşletme Fonksiyonları', unite:1, konu:'Sistem Yaklaşımı',
    soru:'Aşağıdakilerden hangileri sistemi tanımlayan unsurlardandır?\nI. Girdi   II. Süreç   III. Çıktı   IV. Geri bildirim',
    secenekler:{A:'Yalnız I',B:'Yalnız III',C:'II ve IV',D:'I, II ve III',E:'I, II, III ve IV'},
    dogruCevap:'E', aciklama:'Sistem yaklaşımında bir sistemin temel unsurları: Girdi (kaynaklar), Dönüşüm süreci, Çıktı (ürün/hizmet) ve Geri bildirim (sistemin düzeltilmesi için bilgi). Tüm dördü de sistemi tanımlar.',
    nedenDigerleriDegil:'Geri bildirim olmadan sistem kendini düzeltemez; dört unsur birlikte tam tanımı oluşturur.',
    soruTipi:'çıkmış_soru', kaynak:k18as, guvenDurumu:'kontrol_edildi', kontrolEden:'aof.tc-gorsel' },

  { id:'ISL106-026', dersKodu:'İŞL106U', dersAdi:'İşletme Fonksiyonları', unite:3, konu:'Tüketici Değerleri',
    soru:'Mehmet; güvendiği, tanıdığı işletmelerden ürün ve hizmet satın alıyorsa aşağıdaki değerlerden hangisine göre hareket etmiş sayılır?',
    secenekler:{A:'Kalite değerine',B:'İmaj değerine',C:'Ekonomik değere',D:'İlişkisel değere',E:'Statü değerine'},
    dogruCevap:'D', aciklama:'İlişkisel değer; tüketicinin bir işletmeye ya da markaya duyduğu güven ve bağlılık temelinde satın alma kararı vermesidir. Mehmet tanıdığı ve güvendiği işletmelerden alıyor, bu ilişkisel değer güdüsüdür.',
    nedenDigerleriDegil:'Kalite değeri ürün kalitesi; ekonomik değer fiyat/performans; imaj değeri marka prestiji; statü değeri sosyal konum için.',
    soruTipi:'çıkmış_soru', kaynak:k18as, guvenDurumu:'kontrol_edildi', kontrolEden:'aof.tc-gorsel' },

  { id:'ISL106-027', dersKodu:'İŞL106U', dersAdi:'İşletme Fonksiyonları', unite:3, konu:'Peter Drucker',
    soru:'Ünlü işletme gurusu Peter Drucker, işletmelerin en temel iki işlevi olduğunu söyler. Bunlar; ------ ve pazarlamadır.',
    secenekler:{A:'finans',B:'muhasebe',C:'insan kaynakları',D:'inovasyon',E:'üretim'},
    dogruCevap:'D', aciklama:'Peter Drucker\'a göre işletmenin iki temel işlevi: Pazarlama ve İnovasyon. Drucker "Pazarlama ve inovasyon dışındaki her şey maliyet üretir" demiştir.',
    nedenDigerleriDegil:'Finans, muhasebe, İK ve üretim önemli fonksiyonlar olsa da Drucker\'ın sözündeki ikinci temel işlev inovasyondur.',
    soruTipi:'çıkmış_soru', kaynak:k18as, guvenDurumu:'kontrol_edildi', kontrolEden:'aof.tc-gorsel' },

  { id:'ISL106-028', dersKodu:'İŞL106U', dersAdi:'İşletme Fonksiyonları', unite:3, konu:'Pazarlama Tanımı',
    soru:'İşletmelerde, müşteriler için değer yaratan ve bu değerin sonucunda müşteri tatmini ve bağlılığı sağlayarak kâr ettiren sürece ne ad verilir?',
    secenekler:{A:'Pazarlama',B:'Leasing',C:'Markalama',D:'Patentleme',E:'Lisanslama'},
    dogruCevap:'A', aciklama:'Pazarlama; müşteriler için değer yaratma, sunma ve bu değeri iletme sürecidir. AMA tanımına göre pazarlama müşterilere değer sağlarken işletmenin de kâr elde etmesini amaçlar.',
    nedenDigerleriDegil:'Leasing finansal kiralama; markalama marka oluşturma; patentleme fikri mülkiyet koruma; lisanslama hak devri.',
    soruTipi:'çıkmış_soru', kaynak:k18as, guvenDurumu:'kontrol_edildi', kontrolEden:'aof.tc-gorsel' },

  { id:'ISL106-029', dersKodu:'İŞL106U', dersAdi:'İşletme Fonksiyonları', unite:3, konu:'SWOT Analizi',
    soru:'------ analizi, işletmenin güçlü ve zayıf yönleri ile pazarlama çevresindeki fırsat ve tehditleri ayrıntılı olarak inceleyen bir analizdir.',
    secenekler:{A:'Dewey',B:'Rioba',C:'SWOT',D:'Maliyet',E:'ZNÖ'},
    dogruCevap:'C', aciklama:'SWOT analizi; İngilizce Strengths (Güçlü Yönler), Weaknesses (Zayıf Yönler), Opportunities (Fırsatlar) ve Threats (Tehditler) kelimelerinin baş harflerinden oluşur. İşletmenin iç ve dış çevre değerlendirmesini bir arada sunar.',
    nedenDigerleriDegil:'Dewey ve Rioba isimler; Maliyet analizi finansal; ZNÖ zayıf-normal-özel anlık sınıf değerlendirmesidir.',
    soruTipi:'çıkmış_soru', kaynak:k18as, guvenDurumu:'kontrol_edildi', kontrolEden:'aof.tc-gorsel' },

  { id:'ISL106-030', dersKodu:'İŞL106U', dersAdi:'İşletme Fonksiyonları', unite:3, konu:'Pazarlama Anlayışları',
    soru:'Çok miktarda üretmeyi, verimliliği artırmayı, maliyeti düşürmeyi amaçlayan, pazarlamayı siparişleri alma ve malların sevkiyatını yapmaktan ibaret olduğunu savunan pazarlama anlayışı aşağıdakilerden hangisidir?',
    secenekler:{A:'Satışa yönelik pazarlama anlayışı',B:'Topluma yönelik pazarlama anlayışı',C:'Pazara yönelik pazarlama anlayışı',D:'Ürüne yönelik pazarlama anlayışı',E:'Üretime yönelik pazarlama anlayışı'},
    dogruCevap:'E', aciklama:'Üretime yönelik pazarlama anlayışı (üretim dönemi); çok üretim, düşük maliyet ve geniş dağıtım odaklıdır. "Üretilebilen her şey satılır" görüşüne dayanır. Bu anlayışta pazarlama fonksiyonu yalnızca sipariş ve sevkiyatla sınırlıdır.',
    nedenDigerleriDegil:'Satışa yönelik: satış ve promosyon odaklı; ürüne yönelik: kalite ve özellik odaklı; pazara yönelik: müşteri ihtiyaçları odaklı.',
    soruTipi:'çıkmış_soru', kaynak:k18as, guvenDurumu:'kontrol_edildi', kontrolEden:'aof.tc-gorsel' },

  { id:'ISL106-031', dersKodu:'İŞL106U', dersAdi:'İşletme Fonksiyonları', unite:4, konu:'Kapasite Planlama',
    soru:'Aşağıdakilerden hangisi kapasite planlama faaliyetlerinde maliyet analizi yapmak için en fazla kullanılan tekniklerden biridir?',
    secenekler:{A:'Başa baş noktası analizi',B:'Gelir analizi',C:'Gider analizi',D:'ZNÖ analizi',E:'Rekabet analizi'},
    dogruCevap:'A', aciklama:'Başa baş noktası (break-even) analizi; sabit ve değişken maliyetlerin toplam gelire eşit olduğu üretim miktarını gösterir. Kapasite planlama ve yatırım kararlarında en yaygın kullanılan maliyet analiz tekniğidir.',
    nedenDigerleriDegil:'Gelir ve gider analizi tek boyutlu; ZNÖ ve rekabet analizi kapasite planlamada kullanılmaz.',
    soruTipi:'çıkmış_soru', kaynak:k18as, guvenDurumu:'kontrol_edildi', kontrolEden:'aof.tc-gorsel' },

  { id:'ISL106-032', dersKodu:'İŞL106U', dersAdi:'İşletme Fonksiyonları', unite:4, konu:'Üretim Kavramı',
    soru:'İktisatçılar üretim olayını ------- üretmek şeklinde tanımlamaktadırlar.',
    secenekler:{A:'fiziki varlık',B:'çıktı',C:'fayda',D:'maliyet',E:'sistem'},
    dogruCevap:'C', aciklama:'İktisatçılara göre üretim; fayda yaratmak anlamına gelir. Bir şeyin yeri, şekli, zamanı veya sahipliği değiştirilerek ona fayda katılıyorsa üretim yapılmış demektir.',
    nedenDigerleriDegil:'Fiziki varlık ve çıktı teknik tanımlar; maliyet girdilerle ilgili; sistem metodoloji; fayda en kapsamlı iktisat tanımıdır.',
    soruTipi:'çıkmış_soru', kaynak:k18as, guvenDurumu:'kontrol_edildi', kontrolEden:'aof.tc-gorsel' },

  { id:'ISL106-033', dersKodu:'İŞL106U', dersAdi:'İşletme Fonksiyonları', unite:1, konu:'Sinerji',
    soru:'Sistem elemanları sistem içinde toplu hareket ettiklerinde tek tek ortaya koyacaklarından çok daha fazlasını ortaya çıkarmaktadırlar. Bu duruma ne ad verilir?',
    secenekler:{A:'Maliyet',B:'Sinerji',C:'Girdi',D:'Azalan fayda',E:'Değer'},
    dogruCevap:'B', aciklama:'Sinerji (synergy); sistem bileşenlerinin birlikte çalışması sonucu tek tek çalışmalarından daha büyük bir sonuç elde edilmesidir. "Bütün, parçaların toplamından büyüktür" ifadesiyle özetlenir.',
    nedenDigerleriDegil:'Azalan fayda tersi yönde bir ekonomik kavram; girdi sistem unsuru; maliyet ve değer farklı kavramlar.',
    soruTipi:'çıkmış_soru', kaynak:k18as, guvenDurumu:'kontrol_edildi', kontrolEden:'aof.tc-gorsel' },

  { id:'ISL106-034', dersKodu:'İŞL106U', dersAdi:'İşletme Fonksiyonları', unite:4, konu:'Üretim Değerleri',
    soru:'Aşağıdakilerden hangisi üretimde, girdilerin çıktıya dönüşümünde yaratılan değerlerden biri değildir?',
    secenekler:{A:'Şekil',B:'Statü',C:'Zaman',D:'Yer',E:'Sahiplik'},
    dogruCevap:'B', aciklama:'Üretimde yaratılan değerler: Şekil değeri (fiziksel dönüşüm), Yer değeri (nakliye), Zaman değeri (depolama), Sahiplik değeri (mülkiyet transferi). "Statü" bir pazarlama/tüketici değeri olabilir ama üretim sürecinde yaratılan dört temel değerden biri değildir.',
    nedenDigerleriDegil:'A, C, D, E üretim ekonomisindeki dört temel değer türüdür; statü bu sınıflandırmaya dahil değildir.',
    soruTipi:'çıkmış_soru', kaynak:k18as, guvenDurumu:'kontrol_edildi', kontrolEden:'aof.tc-gorsel' },

  { id:'ISL106-035', dersKodu:'İŞL106U', dersAdi:'İşletme Fonksiyonları', unite:4, konu:'Üretim Girdileri',
    soru:'Aşağıdakilerden hangileri üretim sürecindeki girdi kapsamında değerlendirilebilir?\nI. Hammadde   II. Makine   III. Sermaye   IV. Enerji',
    secenekler:{A:'Yalnız I',B:'II ve III',C:'II ve IV',D:'I, III ve IV',E:'I, II, III ve IV'},
    dogruCevap:'E', aciklama:'Üretim girdileri; üretim sürecine sokulan tüm kaynakları kapsar: Hammadde (doğal kaynaklar), Makine (sermaye malları), Sermaye (finansal kaynak) ve Enerji. Dördü de üretim faktörü/girdisi sayılır.',
    nedenDigerleriDegil:'Bir üretim sürecinde hammadde, enerji, makine ve sermaye birlikte kullanılır; yalnızca biri değil tümü girdidir.',
    soruTipi:'çıkmış_soru', kaynak:k18as, guvenDurumu:'kontrol_edildi', kontrolEden:'aof.tc-gorsel' },

  { id:'ISL106-036', dersKodu:'İŞL106U', dersAdi:'İşletme Fonksiyonları', unite:5, konu:'Finansman Türleri',
    soru:'Elde edilen kârın, ortaklara dağıtılmayıp işletme bünyesinde bırakılan kısmı ------ finansman olarak adlandırılır.',
    secenekler:{A:'boşta',B:'geçici',C:'oto',D:'prim',E:'vergi'},
    dogruCevap:'C', aciklama:'Otofinansman (öz finansman); işletmenin kârının dağıtılmayarak bünyede tutulmasıyla sağlanan finansman biçimidir. Dışarıdan kaynak almadan, iç kaynaklarla büyümeyi ifade eder.',
    nedenDigerleriDegil:'Geçici, boşta, prim ve vergi finansmanı gerçek finansman türleri değildir; oto (özü) finansman tanımı karşılar.',
    soruTipi:'çıkmış_soru', kaynak:k18as, guvenDurumu:'kontrol_edildi', kontrolEden:'aof.tc-gorsel' },

  { id:'ISL106-037', dersKodu:'İŞL106U', dersAdi:'İşletme Fonksiyonları', unite:5, konu:'Çalışma Sermayesi',
    soru:'Ham madde alımlarına yapılacak ödemeler için geçen süreye ne ad verilir?',
    secenekler:{A:'Ticari borçların ödenme süresi',B:'Stokta geçen süre',C:'Ticari alacakların tahsil süresi',D:'Geleneksel süre',E:'Toplam süre'},
    dogruCevap:'A', aciklama:'Ticari borçların ödenme süresi; hammadde veya mal alımı yapıldıktan sonra satıcılara ödeme yapılıncaya kadar geçen süredir. Uzun olması işletmenin nakit çıkışını geciktirdiğinden avantajlıdır.',
    nedenDigerleriDegil:'Stokta geçen süre üretimden satışa kadar; ticari alacak tahsil süresi satıştan tahsilata kadar olan süre.',
    soruTipi:'çıkmış_soru', kaynak:k18as, guvenDurumu:'kontrol_edildi', kontrolEden:'aof.tc-gorsel' },

  { id:'ISL106-038', dersKodu:'İŞL106U', dersAdi:'İşletme Fonksiyonları', unite:5, konu:'Bilanço',
    soru:'Aşağıdakilerden hangisi bilançonun pasif kısmında yer alır?',
    secenekler:{A:'Stoklar',B:'Uzun süreli yabancı kaynaklar',C:'Duran varlıklar',D:'Dönen varlıklar',E:'Alacaklar'},
    dogruCevap:'B', aciklama:'Bilançonun pasif tarafı kaynakları gösterir: kısa ve uzun süreli yabancı kaynaklar ile öz kaynaklar. Uzun süreli (vadeli) yabancı kaynaklar pasif bölümünde yer alır. Stoklar, duran/dönen varlıklar ve alacaklar aktif taraftadır.',
    nedenDigerleriDegil:'A, C, D, E varlıkları ifade eder ve aktif kısımda yer alır; pasif = finansman kaynakları.',
    soruTipi:'çıkmış_soru', kaynak:k18as, guvenDurumu:'kontrol_edildi', kontrolEden:'aof.tc-gorsel' },

  { id:'ISL106-039', dersKodu:'İŞL106U', dersAdi:'İşletme Fonksiyonları', unite:5, konu:'Çalışma Sermayesi',
    soru:'Çalışma sermayesinin özellikleriyle ilgili aşağıdaki ifadelerden hangisi yanlıştır?',
    secenekler:{A:'Faaliyetlerin kârlı ve verimli yürütülmesi için gereklidir.',B:'Yükümlülüklerini karşılayamama (likidite) riskini azaltır.',C:'İşletmenin tam kapasite çalışmasında etkilidir.',D:'Kredi değerliliğini azaltır.',E:'İş hacminin genişlemesini sağlar.'},
    dogruCevap:'D', aciklama:'Çalışma sermayesi (dönen varlıklar - kısa vadeli yükümlülükler) yüksek olduğunda işletmenin kredi değerliliği ARTAR; zira borç ödeme kapasitesi güçlü demektir. "Azaltır" ifadesi yanlıştır.',
    nedenDigerleriDegil:'A, B, C, E çalışma sermayesinin bilinen faydalarıdır; D tam tersini söylediği için yanlıştır.',
    soruTipi:'çıkmış_soru', kaynak:k18as, guvenDurumu:'kontrol_edildi', kontrolEden:'aof.tc-gorsel' },

  { id:'ISL106-040', dersKodu:'İŞL106U', dersAdi:'İşletme Fonksiyonları', unite:5, konu:'Yatırım Türleri',
    soru:'Aşağıdakilerden hangileri yatırım kavramı içerisinde yer alır?\nI. Genişleme yatırımları  II. Yenileme yatırımları  III. Modernleştirme yatırımları  IV. Stratejik yatırımlar',
    secenekler:{A:'Yalnız I',B:'Yalnız III',C:'I ve II',D:'I, III ve IV',E:'I, II, III ve IV'},
    dogruCevap:'E', aciklama:'Yatırım türleri: Genişleme (kapasite artırma), Yenileme (eskiyen varlıkları yenileme), Modernleştirme (teknolojiyi güncelleme) ve Stratejik yatırımlar (rekabet avantajı sağlama). Dördü de yatırım kapsamındadır.',
    nedenDigerleriDegil:'Her biri farklı amaca hizmet eden geçerli yatırım türüdür; hepsini dışarıda bırakan seçenekler yanlıştır.',
    soruTipi:'çıkmış_soru', kaynak:k18as, guvenDurumu:'kontrol_edildi', kontrolEden:'aof.tc-gorsel' },

  // ── 2018 DÖNEMSONU ────────────────────────────────────────────
  { id:'ISL106-041', dersKodu:'İŞL106U', dersAdi:'İşletme Fonksiyonları', unite:1, konu:'İşletme Fonksiyonları',
    soru:'Aşağıdakilerden hangisi işletmenin destekleyici fonksiyonlarından biridir?',
    secenekler:{A:'Yöneltme',B:'Planlama',C:'Örgütleme',D:'Koordinasyon',E:'Muhasebe'},
    dogruCevap:'E', aciklama:'Yöneltme, Planlama, Örgütleme ve Koordinasyon yönetim sürecinin temel fonksiyonlarıdır. Muhasebe, işletmenin yönetim sürecini destekleyen fonksiyonel (destekleyici) bir alandır.',
    nedenDigerleriDegil:'A, B, C, D yönetim süreci işlevleridir; muhasebe işletmenin fonksiyonel alanıdır.',
    soruTipi:'çıkmış_soru', kaynak:k18ds, guvenDurumu:'kontrol_edildi', kontrolEden:'aof.tc-gorsel' },

  { id:'ISL106-042', dersKodu:'İŞL106U', dersAdi:'İşletme Fonksiyonları', unite:3, konu:'Ürün Sınıflandırması',
    soru:'Aşağıdakilerden hangisi kolayda ürünlerden biridir?',
    secenekler:{A:'Hayat sigortası',B:'Saat',C:'Mobilya',D:'Deterjan',E:'Televizyon'},
    dogruCevap:'D', aciklama:'Kolayda ürünler; sık satın alınan, düşük fiyatlı, az çaba gerektiren ürünlerdir. Deterjan tipik bir kolayda üründür. Hayat sigortası uzmanlık, saat ve televizyon beğenmeli ürün kategorisindedir.',
    nedenDigerleriDegil:'Hayat sigortası uzmanlık/endüstriyel; saat, mobilya, televizyon beğenmeli ürünlerdir (araştırma gerektirirler).',
    soruTipi:'çıkmış_soru', kaynak:k18ds, guvenDurumu:'kontrol_edildi', kontrolEden:'aof.tc-gorsel' },

  { id:'ISL106-043', dersKodu:'İŞL106U', dersAdi:'İşletme Fonksiyonları', unite:4, konu:'Üretim Sistemleri',
    soru:'Aşağıdakilerden hangisi talebe göre sınıflandırılan üretim sistemlerinden biridir?',
    secenekler:{A:'Sürekli üretim',B:'Proje tipi üretim',C:'Kesikli üretim',D:'Siparişe göre üretim',E:'Kütle üretim'},
    dogruCevap:'D', aciklama:'Üretim sistemleri talebe göre: Siparişe göre üretim (müşteri siparişi üzerine başlar), Stok için üretim (tahmine dayalı), Montaj üzerine üretim. Siparişe göre üretim doğrudan talep odaklıdır.',
    nedenDigerleriDegil:'Sürekli, proje, kesikli ve kütle üretim miktara veya akışa göre yapılan sınıflandırmalardır.',
    soruTipi:'çıkmış_soru', kaynak:k18ds, guvenDurumu:'kontrol_edildi', kontrolEden:'aof.tc-gorsel' },

  { id:'ISL106-044', dersKodu:'İŞL106U', dersAdi:'İşletme Fonksiyonları', unite:5, konu:'Yatırım',
    soru:'Üretim miktarının korunması ve/veya artırılması amacıyla bugünden yapılan harcamalara ------ adı verilir.',
    secenekler:{A:'ithalat harcaması',B:'yatırım',C:'sabit sermaye',D:'ihracat harcaması',E:'bütçe'},
    dogruCevap:'B', aciklama:'Yatırım; ilerideki dönemlerde üretim kapasitesini artırmak veya korumak amacıyla bugün yapılan harcamalardır. Makine, ekipman, bina alımları yatırım harcamalarına örnek gösterilebilir.',
    nedenDigerleriDegil:'Sabit sermaye yatırımın sonucunda elde edilen duran varlık; ithalat ve ihracat dış ticaret; bütçe planlama aracı.',
    soruTipi:'çıkmış_soru', kaynak:k18ds, guvenDurumu:'kontrol_edildi', kontrolEden:'aof.tc-gorsel' },

  { id:'ISL106-045', dersKodu:'İŞL106U', dersAdi:'İşletme Fonksiyonları', unite:5, konu:'Muhasebe Kullanıcıları',
    soru:'Aşağıdakilerden hangisi işletme içi bilgi kullanıcılarından biridir?',
    secenekler:{A:'Finansal kurumlar',B:'Medya',C:'Rakipler',D:'İşletme yöneticileri',E:'İşçi sendikaları'},
    dogruCevap:'D', aciklama:'İşletme içi bilgi kullanıcıları; doğrudan işletmenin içindeki kişi ve birimlerdir: Yöneticiler, çalışanlar, departmanlar. Finansal kurumlar, medya, rakipler ve sendikalar dış kullanıcılardır.',
    nedenDigerleriDegil:'A, B, C, E işletme dışındaki taraflardır; yöneticiler işletmenin içinden karar verici.',
    soruTipi:'çıkmış_soru', kaynak:k18ds, guvenDurumu:'kontrol_edildi', kontrolEden:'aof.tc-gorsel' },

  { id:'ISL106-046', dersKodu:'İŞL106U', dersAdi:'İşletme Fonksiyonları', unite:2, konu:'İnsan Kaynakları',
    soru:'İşgörenin işletmeden ayrılırken işveren tarafından İş Kanunu gereğince işgörene ödemekle yükümlü olduğu tazminata ne ad verilir?',
    secenekler:{A:'Kâr payı',B:'Prim',C:'İskonto',D:'Kıdem tazminatı',E:'Şerefiye'},
    dogruCevap:'D', aciklama:'Kıdem tazminatı; işçinin belirli koşullar altında (emeklilik, işveren feshi vb.) işten ayrılması durumunda her çalışma yılı için işveren tarafından ödenmesi zorunlu olan tazminattır.',
    nedenDigerleriDegil:'Kâr payı performansa bağlı; prim teşvik ödemesi; iskonto fiyat indirimi; şerefiye peştemallık.',
    soruTipi:'çıkmış_soru', kaynak:k18ds, guvenDurumu:'kontrol_edildi', kontrolEden:'aof.tc-gorsel' },

  { id:'ISL106-047', dersKodu:'İŞL106U', dersAdi:'İşletme Fonksiyonları', unite:5, konu:'Bütçe',
    soru:'Bütçe hazırlama sürecinin son aşaması aşağıdakilerden hangisidir?',
    secenekler:{A:'Bütçe komitesinin oluşturulması',B:'Bütçe yönergesinin tanımlanması',C:'Bütçenin kabulü ve onayı',D:'Bütçe döneminin belirlenmesi',E:'Bütçe amaçlarının hazırlanması'},
    dogruCevap:'C', aciklama:'Bütçe hazırlama süreci: Amaç belirleme → Dönem belirleme → Komite oluşturma → Yönerge → Taslak bütçe → Revizyon → Kabul ve onay. Son aşama bütçenin yetkili organlarca (yönetim kurulu, genel kurul) kabul ve onayıdır.',
    nedenDigerleriDegil:'A, B, D, E sürecin başlangıç ve orta aşamalarıdır; kabul-onay sürecin son adımını oluşturur.',
    soruTipi:'çıkmış_soru', kaynak:k18ds, guvenDurumu:'kontrol_edildi', kontrolEden:'aof.tc-gorsel' },

  { id:'ISL106-048', dersKodu:'İŞL106U', dersAdi:'İşletme Fonksiyonları', unite:5, konu:'İşletme Belgeleri',
    soru:'Aşağıdakilerden hangisi işletmenin faaliyetlerini sistemli bir şekilde yapabilmesi için kendisinin yarattığı belgelerden biri değildir?',
    secenekler:{A:'Senet',B:'Tediye makbuzu',C:'Tahsilat makbuzu',D:'Stok kartı',E:'Cari hesap kartı'},
    dogruCevap:'A', aciklama:'Senet çoğunlukla karşı taraftan gelen veya dışarıda düzenlenen bir belgedir; işletmenin kendi yarattığı bir belge değildir. Tediye (ödeme) ve tahsilat makbuzları, stok ve cari hesap kartları işletmenin bizzat oluşturduğu iç belgelerdir.',
    nedenDigerleriDegil:'B, C, D, E işletmenin muhasebe ve operasyon süreçlerinde kendi hazırladığı belgelerdir.',
    soruTipi:'çıkmış_soru', kaynak:k18ds, guvenDurumu:'kontrol_edildi', kontrolEden:'aof.tc-gorsel' },

  { id:'ISL106-049', dersKodu:'İŞL106U', dersAdi:'İşletme Fonksiyonları', unite:2, konu:'Yetkinlikler',
    soru:'Aşağıdakilerden hangisi bilişsel yetkinliklerden biridir?',
    secenekler:{A:'Takım çalışması',B:'İş birliği',C:'Teknik ve mesleki uzmanlığa sahip olma',D:'Öz kontrol',E:'Öz güven'},
    dogruCevap:'C', aciklama:'Bilişsel yetkinlikler; analitik düşünme, problem çözme, teknik ve mesleki uzmanlık gibi bilgi ve zihin temelli becerilerdir. Takım çalışması ve iş birliği sosyal yetkinlik; öz kontrol ve öz güven kişisel/duygusal yetkinliktir.',
    nedenDigerleriDegil:'A, B sosyal; D, E duygusal/kişisel yetkinlik kategorisinde yer alır.',
    soruTipi:'çıkmış_soru', kaynak:k18ds, guvenDurumu:'kontrol_edildi', kontrolEden:'aof.tc-gorsel' },

  { id:'ISL106-050', dersKodu:'İŞL106U', dersAdi:'İşletme Fonksiyonları', unite:2, konu:'Endüstri İlişkileri',
    soru:'Aşağıdakilerden hangileri endüstri ilişkileri sistemindeki taraflardandır?\nI. İşçiler ve işçi sendikaları  II. İşverenler ve işveren sendikaları  III. Düzenleyici, hakem ve işveren olarak 3 ayrı rolü birden üstlenen devlet',
    secenekler:{A:'Yalnız I',B:'Yalnız II',C:'I ve II',D:'II ve III',E:'I, II ve III'},
    dogruCevap:'E', aciklama:'Endüstri ilişkileri sistemi üç ana taraftan oluşur: İşçiler ve sendikaları, İşverenler ve sendikaları, Devlet (düzenleyici, hakem ve bazen işveren sıfatıyla). Üçü birlikte sistemi oluşturur.',
    nedenDigerleriDegil:'Herhangi bir tarafı dışarıda bırakan seçenekler eksiktir; sistem üç tarafın etkileşimiyle işler.',
    soruTipi:'çıkmış_soru', kaynak:k18ds, guvenDurumu:'kontrol_edildi', kontrolEden:'aof.tc-gorsel' },

  { id:'ISL106-051', dersKodu:'İŞL106U', dersAdi:'İşletme Fonksiyonları', unite:2, konu:'Ücret Yönetimi',
    soru:'Aşağıdakilerden hangisi ücret yönetiminin amaçlarından biri değildir?',
    secenekler:{A:'Motive edici olabilmek',B:'Etkinlik azalışı sağlamak',C:'Mevcut iş görenleri elde tutmak',D:'Nitelikli iş görenleri çekmek',E:'Verimlilik artışı sağlamak'},
    dogruCevap:'B', aciklama:'Ücret yönetiminin amaçları arasında etkinliği ARTIRMAK yer alır, azaltmak değil. Adil ve rekabetçi ücret sistemi motivasyonu, verimliliği ve nitelikli çalışan çekimini destekler.',
    nedenDigerleriDegil:'A, C, D, E ücret yönetiminin gerçek amaçlarıdır; "etkinlik azalışı" bu amaçların tamamen tersidir.',
    soruTipi:'çıkmış_soru', kaynak:k18ds, guvenDurumu:'kontrol_edildi', kontrolEden:'aof.tc-gorsel' },

  { id:'ISL106-052', dersKodu:'İŞL106U', dersAdi:'İşletme Fonksiyonları', unite:2, konu:'Performans Değerleme',
    soru:'Aşağıdakilerden hangisi geleneksel performans değerleme yöntemlerinden biridir?',
    secenekler:{A:'360 derece performans değerleme',B:'Sıralama',C:'Karma performans değerleme',D:'Hedeflere göre değerleme',E:'Değerlendirme merkezi'},
    dogruCevap:'B', aciklama:'Sıralama yöntemi; çalışanların birbirleriyle karşılaştırılarak en iyiden en kötüye sıralandığı geleneksel bir performans değerleme tekniğidir. 360 derece değerleme modern, değerlendirme merkezi ve MBO (hedeflere göre) daha yeni yaklaşımlardır.',
    nedenDigerleriDegil:'A, D, E modern değerleme yöntemleridir; sıralama skalası geleneksel kategoridedir.',
    soruTipi:'çıkmış_soru', kaynak:k18ds, guvenDurumu:'kontrol_edildi', kontrolEden:'aof.tc-gorsel' },

  { id:'ISL106-053', dersKodu:'İŞL106U', dersAdi:'İşletme Fonksiyonları', unite:6, konu:'Kurumsal Kimlik',
    soru:'Aşağıdakilerden hangileri kurumsal kimliği daha iyi anlamak için kullanılan kavramlardandır?\nI. Yansıtılan kimlik  II. Arzulanan kimlik  III. Uygulanan kimlik  IV. Algılanan kimlik',
    secenekler:{A:'Yalnız I',B:'Yalnız II',C:'I ve III',D:'I, III ve IV',E:'I, II, III ve IV'},
    dogruCevap:'E', aciklama:'Kurumsal kimlik dört boyutuyla incelenir: Yansıtılan kimlik (kurumun dışarıya yansıttığı), Arzulanan kimlik (olmak istediği), Uygulanan kimlik (davranışlarına yansıyan), Algılanan kimlik (paydaşların algısı). Dördü de kurumsal kimliği bütünler.',
    nedenDigerleriDegil:'Herhangi bir boyutu dışarıda bırakan seçenekler eksik kalır; kurumsal kimlik bu dört boyutun bütünüdür.',
    soruTipi:'çıkmış_soru', kaynak:k18ds, guvenDurumu:'kontrol_edildi', kontrolEden:'aof.tc-gorsel' },

  { id:'ISL106-054', dersKodu:'İŞL106U', dersAdi:'İşletme Fonksiyonları', unite:6, konu:'Kriz Yönetimi',
    soru:'Aşağıdakilerden hangisi kriz yönetiminin önemli noktalarından biri değildir?',
    secenekler:{A:'Maliyetlerin anında tüketicilere aktarılması',B:'İletişim ekibinin oluşturulması',C:'Kurum sözcüsüne medya eğitimi verilmesi',D:'İlgili dış birimlerle kurulacak irtibatların tespit edilmesi',E:'Kurumun kilit sözcülerinin belirlenmesi'},
    dogruCevap:'A', aciklama:'Kriz yönetiminde maliyetleri tüketicilere anında aktarmak ne bir yükümlülük ne de iyi uygulama olarak tanımlanır. Kriz yönetimi; iletişim, sözcü belirleme, medya eğitimi ve paydaş koordinasyonuna odaklanır.',
    nedenDigerleriDegil:'B, C, D, E kriz iletişimi ve yönetiminin temel bileşenleridir; A fiyatlandırma kararıyla ilgilidir.',
    soruTipi:'çıkmış_soru', kaynak:k18ds, guvenDurumu:'kontrol_edildi', kontrolEden:'aof.tc-gorsel' },

  { id:'ISL106-055', dersKodu:'İŞL106U', dersAdi:'İşletme Fonksiyonları', unite:6, konu:'Kurumsal İletişim',
    soru:'Kurumsal iletişimle ilgili aşağıdaki ifadelerden hangisi yanlıştır?',
    secenekler:{A:'Etkili bir iletişim için genellikle tek yönlü iletişim tercih edilir.',B:'Tüm kurumlarda iletişim; yatay ve dikey, formal ve informal, içsel ve dışsal olarak gerçekleşebilir.',C:'Paydaşların kurumun kimliği, imajı ve itibarının oluşumunu algıladığı süreç olarak görülebilir.',D:'Kurumun iç ve dış sosyal paydaşlarıyla ilgili tüm iletişim, politika ve uygulamalarını kapsayan bir yönetim biçimidir.',E:'Yönetimsel iletişim, pazarlama iletişimi ve örgütsel iletişim olarak üç başlık altında toplanabilir.'},
    dogruCevap:'A', aciklama:'Etkili iletişim tek yönlü değil, çift yönlü olmalıdır. Çift yönlü iletişim; geri bildirim, diyalog ve katılım sağladığından tek yönlüden daha etkilidir.',
    nedenDigerleriDegil:'B, C, D, E kurumsal iletişimin doğru tanımları ve özellikleridir; tek yönlü iletişim etkinliği sınırlar.',
    soruTipi:'çıkmış_soru', kaynak:k18ds, guvenDurumu:'kontrol_edildi', kontrolEden:'aof.tc-gorsel' },

  { id:'ISL106-056', dersKodu:'İŞL106U', dersAdi:'İşletme Fonksiyonları', unite:6, konu:'Kurumsal İtibar',
    soru:'Kurumsal itibarın temel nitelikleriyle ilgili aşağıdaki ifadelerden hangisi yanlıştır?',
    secenekler:{A:'Kurumsal itibar ve kurumsal imaj kavramları arasında çift yönlü bir ilişki vardır.',B:'Büyük ölçüde paydaşların kurum hakkında oluşturdukları, kurumun davranış, iletişim ve sembollerine dayanan imajlara bağlıdır.',C:'Dinamik olmayan bir kavramdır.',D:'Oluşturulması ve yönetilmesi zaman alır.',E:'Rakiplerin bulunduğu ortamda kurumun algılanan değerini belirginleştirir.'},
    dogruCevap:'C', aciklama:'Kurumsal itibar; değişen koşullara, olaylara ve paydaş algılarına bağlı olarak sürekli değişen dinamik bir kavramdır. "Dinamik olmayan" ifadesi bu nedenle yanlıştır.',
    nedenDigerleriDegil:'A, B, D, E kurumsal itibarın doğru nitelikleridir; itibar zaman içinde şekillenir ve değişebilir.',
    soruTipi:'çıkmış_soru', kaynak:k18ds, guvenDurumu:'kontrol_edildi', kontrolEden:'aof.tc-gorsel' },

  { id:'ISL106-057', dersKodu:'İŞL106U', dersAdi:'İşletme Fonksiyonları', unite:4, konu:'Ar-Ge',
    soru:'OECD tarafından "bilim ve teknolojinin gelişmesini sağlayacak yeni bilgiler elde etmek ve mevcut bilgilerle yeni malzeme, ürün ve araçlar üretmek, yazılım üretimi dahil olmak üzere yeni sistem, süreç ve hizmetler oluşturmak veya mevcut olanları geliştirmek amacı ile yapılan sistematik ve düzenli çalışmalar" şeklinde yapılan tanım aşağıdakilerden hangisini ifade eder?',
    secenekler:{A:'Ar-Ge',B:'Süreç yönetimi',C:'Program',D:'Rekabet',E:'Üretim'},
    dogruCevap:'A', aciklama:'OECD\'nin Frascati Kılavuzu\'ndaki tanım Araştırma ve Geliştirme (Ar-Ge) faaliyetlerini tanımlamaktadır. Ar-Ge; temel araştırma, uygulamalı araştırma ve deneysel geliştirme çalışmalarını kapsar.',
    nedenDigerleriDegil:'Süreç yönetimi, program, rekabet ve üretim bu tanımın kapsamını karşılamaz.',
    soruTipi:'çıkmış_soru', kaynak:k18ds, guvenDurumu:'kontrol_edildi', kontrolEden:'aof.tc-gorsel' },

  { id:'ISL106-058', dersKodu:'İŞL106U', dersAdi:'İşletme Fonksiyonları', unite:4, konu:'İnovasyon',
    soru:'"Mor İnek" kitabıyla farklılaşma alanında çığır açan kişi aşağıdakilerden hangisidir?',
    secenekler:{A:'E. Tresoldi',B:'L. Ghiberti',C:'A. Condivi',D:'P. Canonica',E:'S. Godin'},
    dogruCevap:'E', aciklama:'Seth Godin "Mor İnek" (Purple Cow, 2003) kitabının yazarıdır. Kitapta ürün ve hizmetlerde farklılaşmanın (dikkat çekici olmanın) pazarlama başarısının anahtarı olduğunu savunur.',
    nedenDigerleriDegil:'Diğer isimler Mor İnek kitabıyla ilgisi olmayan kişilerdir.',
    soruTipi:'çıkmış_soru', kaynak:k18ds, guvenDurumu:'kontrol_edildi', kontrolEden:'aof.tc-gorsel' },

  { id:'ISL106-059', dersKodu:'İŞL106U', dersAdi:'İşletme Fonksiyonları', unite:4, konu:'İnovasyon',
    soru:'"Bir yöneticinin düşebileceği en büyük tuzaklardan biri inovasyon ile yeniliğin birbiriyle karıştırılmasıdır." diyen ünlü yönetim gurusu kimdir?',
    secenekler:{A:'Lombardo',B:'Drucker',C:'Gary',D:'Echenoz',E:'Gilbert'},
    dogruCevap:'B', aciklama:'Peter Drucker inovasyon ve yenilik (novelty) arasındaki farka dikkat çekmiştir. Drucker\'a göre inovasyon; değer yaratan değişim iken salt yenilik değer yaratmayabilir.',
    nedenDigerleriDegil:'Diğer isimler bu sözü söyleyen kişiler değildir.',
    soruTipi:'çıkmış_soru', kaynak:k18ds, guvenDurumu:'kontrol_edildi', kontrolEden:'aof.tc-gorsel' },

  { id:'ISL106-060', dersKodu:'İŞL106U', dersAdi:'İşletme Fonksiyonları', unite:4, konu:'İnovasyon Ortamı',
    soru:'Aşağıdakilerden hangisi inovasyon dostu ortamlardan biri değildir?',
    secenekler:{A:'Yöneticileri yeni fikirler geliştirmek konusunda hızlı, bunları yargılamak konusunda yavaş hareket eden ortamlar',B:'Yaratıcılık vahası ortamlar',C:'Farklılaşmayı değil aynılaşmayı sağlayan ortamlar',D:'Statükocu olmayan ortamlar',E:'Başarısızlık ve hatada toleranslı kültür ortamları'},
    dogruCevap:'C', aciklama:'"Farklılaşmayı değil aynılaşmayı sağlayan ortamlar" inovasyon karşıtıdır. İnovasyon farklı düşünmeyi, alışılmışın dışına çıkmayı gerektirir. Aynılaşmayı teşvik eden ortamlar yeni fikirlerin önünü tıkar.',
    nedenDigerleriDegil:'A, B, D, E inovasyon kültürünü destekleyen özelliklerdir; aynılaşma inovasyonun tam tersidir.',
    soruTipi:'çıkmış_soru', kaynak:k18ds, guvenDurumu:'kontrol_edildi', kontrolEden:'aof.tc-gorsel' },

  // ── 2017 ARA SINAV ────────────────────────────────────────────
  { id:'ISL106-061', dersKodu:'İŞL106U', dersAdi:'İşletme Fonksiyonları', unite:1, konu:'Örgüt Yapısı',
    soru:'Aşağıdakilerden hangileri örgüt yapısının temel unsurlarındandır?\nI. Yatay farklılaşma  II. Dikey farklılaşma  III. Merkezileşme ve merkezileşmeme  IV. Biçimselleşme ve biçimselleşmeme',
    secenekler:{A:'Yalnız I',B:'Yalnız II',C:'II ve III',D:'I, II ve III',E:'I, II, III ve IV'},
    dogruCevap:'E', aciklama:'Örgüt yapısının temel unsurları: Yatay farklılaşma (bölümlere ayırma), Dikey farklılaşma (hiyerarşi düzeyleri), Merkezileşme/merkezileşmeme (otoritenin dağılımı), Biçimselleşme (kural ve prosedürlerin yazılı olması). Dördü de temel unsurdur.',
    nedenDigerleriDegil:'Herhangi birini dışarıda bırakan seçenekler eksiktir; dördü birlikte örgüt yapısını tanımlar.',
    soruTipi:'çıkmış_soru', kaynak:k17as, guvenDurumu:'kontrol_edildi', kontrolEden:'aof.tc-gorsel' },

  { id:'ISL106-062', dersKodu:'İŞL106U', dersAdi:'İşletme Fonksiyonları', unite:1, konu:'Etkinlik',
    soru:'Amaçların gerçekleşmesi için kaynakların doğru kullanılmasına ne ad verilir?',
    secenekler:{A:'Etkinlik',B:'Yönetim standardı',C:'Verimlilik',D:'Toplam kalite',E:'İktisadilik'},
    dogruCevap:'A', aciklama:'Etkinlik (effectiveness); önceden belirlenen amaçlara ne ölçüde ulaşıldığını gösterir. "Doğru işleri yapmak" şeklinde de tanımlanır. Verimlilik ise "işleri doğru yapmak"tır (girdi/çıktı oranı).',
    nedenDigerleriDegil:'Verimlilik girdi-çıktı oranı; iktisadilik tasarruf; toplam kalite kalite yönetim felsefesi.',
    soruTipi:'çıkmış_soru', kaynak:k17as, guvenDurumu:'kontrol_edildi', kontrolEden:'aof.tc-gorsel' },

  { id:'ISL106-063', dersKodu:'İŞL106U', dersAdi:'İşletme Fonksiyonları', unite:1, konu:'Liderlik',
    soru:'Liderliğin özellikleriyle ilgili aşağıdaki ifadelerden hangisi yanlıştır?',
    secenekler:{A:'Yöneltmenin belirgin özelliğidir.',B:'Çalışanların motivasyonunu sağlar.',C:'İşleri bizzat ve sadece kendisi yapar.',D:'Astlarda gönüllülüğü sağlar.',E:'Astlara iş yaptırır.'},
    dogruCevap:'C', aciklama:'Lider işleri bizzat kendisi yapmaz; başkalarını yönlendirir, motive eder ve onların aracılığıyla işleri yaptırır. "İşleri bizzat ve sadece kendisi yapar" ifadesi liderliğin özüyle çelişir.',
    nedenDigerleriDegil:'A, B, D, E liderliğin gerçek özellikleridir; lider başkası aracılığıyla sonuç alır.',
    soruTipi:'çıkmış_soru', kaynak:k17as, guvenDurumu:'kontrol_edildi', kontrolEden:'aof.tc-gorsel' },

  { id:'ISL106-064', dersKodu:'İŞL106U', dersAdi:'İşletme Fonksiyonları', unite:4, konu:'Yönetim Araçları',
    soru:'Günlük faaliyetlerin izlenerek değerlendirilmesi ve kaynakların doğru (optimal) kullanımının desteklenmesi düşüncesine dayanan yönetim uygulaması aşağıdakilerden hangisidir?',
    secenekler:{A:'Temel Yetenekler',B:'Kıyaslama',C:'Dengeli Ölçüm Kartı',D:'Altı Sigma',E:'Değişim Mühendisliği'},
    dogruCevap:'C', aciklama:'Dengeli Ölçüm Kartı (Balanced Scorecard); finansal ve finansal olmayan göstergeleri birleştirerek işletmenin günlük faaliyetlerini stratejik hedeflerle ilişkilendirir. Kaynakların optimal kullanımını dört boyuttan takip eder.',
    nedenDigerleriDegil:'Kıyaslama rakiplerle karşılaştırma; Altı Sigma hata azaltma; Değişim Mühendisliği süreç yeniden tasarımı; Temel Yetenekler stratejik avantaj kaynağı.',
    soruTipi:'çıkmış_soru', kaynak:k17as, guvenDurumu:'kontrol_edildi', kontrolEden:'aof.tc-gorsel' },

  { id:'ISL106-065', dersKodu:'İŞL106U', dersAdi:'İşletme Fonksiyonları', unite:1, konu:'Yönetim Özellikleri',
    soru:'Aşağıdakilerden hangisi yönetimin belli başlı özelliklerinden biri değildir?',
    secenekler:{A:'Yalnızca insanlar için geçerlidir.',B:'Bilim değil sanattır.',C:'Yönetim basamakları ve bu basamaklara ait yetki/sorumluluk düzeyleri belirlenmelidir.',D:'Amaçlar önceden belirlenmelidir.',E:'En az iki insan olmalıdır.'},
    dogruCevap:'A', aciklama:'Yönetim "yalnızca insanlar için" değil; insanlar, kaynaklar ve süreçler aracılığıyla amaçlara ulaşmak için uygulanır. Evrensel bir süreç olup insan dışındaki kaynakları da kapsar.',
    nedenDigerleriDegil:'C, D, E yönetimin gerçek özelliklerini ifade eder; "yalnızca insanlar için" ifadesi yönetimin kapsamını hatalı biçimde daraltır.',
    soruTipi:'çıkmış_soru', kaynak:k17as, guvenDurumu:'kontrol_edildi', kontrolEden:'aof.tc-gorsel' },

  { id:'ISL106-066', dersKodu:'İŞL106U', dersAdi:'İşletme Fonksiyonları', unite:3, konu:'Hedef Pazar',
    soru:'Aşağıdakilerden hangileri hedef pazar belirleme stratejilerindendir?\nI. Kitlesel pazarlama  II. Bölümlü pazarlama  III. Niş pazarlama  IV. Mikro pazarlama',
    secenekler:{A:'Yalnız I',B:'Yalnız IV',C:'II ve III',D:'I, III ve IV',E:'I, II, III ve IV'},
    dogruCevap:'E', aciklama:'Hedef pazar belirleme stratejileri: Kitlesel pazarlama (tek segment), Bölümlü pazarlama (çok segment), Niş pazarlama (alt segment), Mikro pazarlama (bireysel/lokal). Dördü de bu stratejilerin kapsamındadır.',
    nedenDigerleriDegil:'Her biri farklı kapsam ve odakta hedef pazar stratejisidir; dördü birlikte tam listeyi oluşturur.',
    soruTipi:'çıkmış_soru', kaynak:k17as, guvenDurumu:'kontrol_edildi', kontrolEden:'aof.tc-gorsel' },

  { id:'ISL106-067', dersKodu:'İŞL106U', dersAdi:'İşletme Fonksiyonları', unite:3, konu:'Marka',
    soru:'İyi bir marka adı seçiminde uzmanların yaptığı önerilerle ilgili aşağıdaki ifadelerden hangisi yanlıştır?',
    secenekler:{A:'Akılda kalıcı olmalıdır.',B:'Ürünün faydaları ve özellikleri hakkında bir şeyler anlatmalıdır.',C:'Kolay söylenebilir ve kolay hatırlanabilir olması gerekir.',D:'Uzun olmalıdır.',E:'Yabancılar tarafından da kolay söylenebilir ve hatırlanabilir olmalıdır.'},
    dogruCevap:'D', aciklama:'İyi bir marka adı kısa, akılda kalıcı ve kolay telaffuz edilebilir olmalıdır. "Uzun olmalıdır" ifadesi bu ilkeyle çelişir; uzun marka adları hatırlanması ve telaffuzu güçleştirir.',
    nedenDigerleriDegil:'A, B, C, E iyi marka adının özellikleri olarak kabul gören ilkelerdir.',
    soruTipi:'çıkmış_soru', kaynak:k17as, guvenDurumu:'kontrol_edildi', kontrolEden:'aof.tc-gorsel' },

  { id:'ISL106-068', dersKodu:'İŞL106U', dersAdi:'İşletme Fonksiyonları', unite:3, konu:'Reklam',
    soru:'Kimliği belirli bir kaynak tarafından belirli bir ücret ödenerek gönderilen, bir örgüt, ürün, hizmet ya da fikir hakkında kişisel olmayan mesajlara ne ad verilir?',
    secenekler:{A:'Lobicilik',B:'Halkla ilişkiler',C:'Reklam',D:'Basın toplantısı',E:'Basın bülteni'},
    dogruCevap:'C', aciklama:'Reklam; kimliği açık bir kaynaktan ücret karşılığı iletilen, kişisel olmayan kitlesel iletişim biçimidir. Temel özellikleri: ücretli, kimliği belli gönderen, kişisel olmayan mesaj.',
    nedenDigerleriDegil:'Halkla ilişkiler genellikle ücretsiz medya kapsamına girer; lobicilik siyasi etki; basın toplantısı ve bülteni PR araçlarıdır.',
    soruTipi:'çıkmış_soru', kaynak:k17as, guvenDurumu:'kontrol_edildi', kontrolEden:'aof.tc-gorsel' },

  { id:'ISL106-069', dersKodu:'İŞL106U', dersAdi:'İşletme Fonksiyonları', unite:3, konu:'Pazarlama',
    soru:'İşletmelerin müşterileri için değer yarattığı ve bu değerin sonucunda müşteri tatmini ve bağlılığı sağlayarak kâr elde ettiği sürece ne ad verilir?',
    secenekler:{A:'Pazarlama',B:'Leasing',C:'Markalama',D:'Lisanslama',E:'Patentleme'},
    dogruCevap:'A', aciklama:'Pazarlama; müşteri ihtiyaçlarını karşılamak için değer yaratma, sunma ve iletme sürecidir. Bu sürecin sonucunda müşteri tatmini, sadakati ve işletme kârlılığı sağlanır.',
    nedenDigerleriDegil:'Leasing finansal kiralama; markalama kimlik oluşturma; lisanslama hak devri; patentleme fikri mülkiyet koruması.',
    soruTipi:'çıkmış_soru', kaynak:k17as, guvenDurumu:'kontrol_edildi', kontrolEden:'aof.tc-gorsel' },

  { id:'ISL106-070', dersKodu:'İŞL106U', dersAdi:'İşletme Fonksiyonları', unite:3, konu:'Peter Drucker',
    soru:'Ünlü işletme gurusu Peter Drucker, işletmelerin en temel iki işlevi olduğunu söyler. Bu işlevler aşağıdakilerin hangisinde birlikte ve doğru olarak verilmiştir?',
    secenekler:{A:'İhracat ve pazarlama',B:'Pazarlama ve inovasyon',C:'İnovasyon ve finansman',D:'Pazarlama ve finansman',E:'İthalat ve pazarlama'},
    dogruCevap:'B', aciklama:'Peter Drucker "Bir işletmenin iki temel işlevi vardır: Pazarlama ve İnovasyon. Yalnız bu ikisi sonuç üretir; geri kalan her şey maliyet" demiştir.',
    nedenDigerleriDegil:'Finansman, ihracat ve ithalat işletme faaliyetleri olmakla birlikte Drucker\'ın sözündeki iki temel işlev değildir.',
    soruTipi:'çıkmış_soru', kaynak:k17as, guvenDurumu:'kontrol_edildi', kontrolEden:'aof.tc-gorsel' },

  { id:'ISL106-071', dersKodu:'İŞL106U', dersAdi:'İşletme Fonksiyonları', unite:4, konu:'Üretim Tarihi',
    soru:'Üretimin ilk dönemlerinde aşağıdakilerden hangisi daha önemliydi?',
    secenekler:{A:'Yönetici sayısı',B:'Miktar',C:'Çeşitlilik',D:'Kalite',E:'Esneklik'},
    dogruCevap:'B', aciklama:'Sanayi devriminin ilk dönemlerinde talep arzı çok aşıyordu; üretilen her şey satılıyordu. Bu dönemde en önemli konu çok üretmek, yani miktar artırmaktı. Kalite ve çeşitlilik daha sonraki dönemlerde ön plana çıktı.',
    nedenDigerleriDegil:'Kalite ve esneklik 20. yüzyılın ortası ve sonrasında, çeşitlilik ise doymuş pazarlarda önem kazandı.',
    soruTipi:'çıkmış_soru', kaynak:k17as, guvenDurumu:'kontrol_edildi', kontrolEden:'aof.tc-gorsel' },

  { id:'ISL106-072', dersKodu:'İŞL106U', dersAdi:'İşletme Fonksiyonları', unite:4, konu:'Hücresel Üretim',
    soru:'Belirli bir parça ailesine dahil tüm parçaların bir üretim hücresinde üretilmesiyle aşağıdakilerden hangisi ortaya çıkar?',
    secenekler:{A:'Üretim rotası kısalır.',B:'Makine hazırlık süresi uzar.',C:'Üretim kapasitesi azalır.',D:'Taşıma maliyetleri artar.',E:'Sipariş bekleme süreleri artar.'},
    dogruCevap:'A', aciklama:'Hücresel üretimde benzer parçalar aynı makineler grubunda (hücrede) üretilir. Bu sayede parçaların fabrika içi hareketi azalır, üretim rotası kısalır ve taşıma maliyetleri düşer.',
    nedenDigerleriDegil:'Makine hazırlık süresi azalır (benzer parçalar); kapasite ve bekleme süreleri de iyileşir.',
    soruTipi:'çıkmış_soru', kaynak:k17as, guvenDurumu:'kontrol_edildi', kontrolEden:'aof.tc-gorsel' },

  { id:'ISL106-073', dersKodu:'İŞL106U', dersAdi:'İşletme Fonksiyonları', unite:4, konu:'Üretim Sistemi',
    soru:'Aşağıdakilerden hangileri üretim sisteminin temel elemanlarındandır?\nI. Girdi  II. Dönüşüm süreci  III. Çıktı  IV. Geri besleme',
    secenekler:{A:'Yalnız II',B:'Yalnız IV',C:'I ve II',D:'I, III ve IV',E:'I, II, III ve IV'},
    dogruCevap:'E', aciklama:'Üretim sistemi girdi → dönüşüm süreci → çıktı → geri besleme döngüsüyle tanımlanır. Geri besleme sisteme düzeltici bilgi sağlar. Dört unsur birlikte eksiksiz sistemi oluşturur.',
    nedenDigerleriDegil:'Geri besleme olmadan sistem kendini düzeltemez; yalnızca bazı unsurları kapsayan seçenekler eksiktir.',
    soruTipi:'çıkmış_soru', kaynak:k17as, guvenDurumu:'kontrol_edildi', kontrolEden:'aof.tc-gorsel' },

  { id:'ISL106-074', dersKodu:'İŞL106U', dersAdi:'İşletme Fonksiyonları', unite:4, konu:'Üretim Türleri',
    soru:'------ üretim doğal maddelerin çeşitli birleştirici yöntemlerle farklı ürünlere dönüştürülmesidir. Çelik, bronz, plastik, cam gibi ürünler bu tür üretimin çıktılarıdır.',
    secenekler:{A:'Primer',B:'Analitik',C:'Sentetik',D:'Fabrikasyon',E:'Montaj'},
    dogruCevap:'C', aciklama:'Sentetik üretim; birden fazla hammadde veya bileşenin birleştirilmesiyle yeni bir ürün oluşturulmasıdır. Çelik (demir+karbon), bronz (bakır+kalay), plastik ve cam bu tür üretimin örnekleridir.',
    nedenDigerleriDegil:'Analitik üretim ham maddeyi ayrıştırır; fabrikasyon parça üretimi; montaj birleştirme; primer ilk çıkarım.',
    soruTipi:'çıkmış_soru', kaynak:k17as, guvenDurumu:'kontrol_edildi', kontrolEden:'aof.tc-gorsel' },

  { id:'ISL106-075', dersKodu:'İŞL106U', dersAdi:'İşletme Fonksiyonları', unite:1, konu:'Sinerji',
    soru:'Sistem elemanları sistem içinde toplu hareket ettiklerinde tek tek ortaya koyacaklarından çok daha fazlasını ortaya çıkarmaktadırlar. Bu duruma ne ad verilir?',
    secenekler:{A:'Girdi',B:'Maliyet',C:'Azalan fayda',D:'Değer',E:'Sinerji'},
    dogruCevap:'E', aciklama:'Sinerji; birlikte hareket eden bileşenlerin tek tek ürettiklerinin toplamını aşan sonuç yaratmasıdır. "Bütün parçaların toplamından büyüktür" prensibidir.',
    nedenDigerleriDegil:'Azalan fayda tersine; değer ve maliyet farklı kavramlar; girdi sistem unsuru.',
    soruTipi:'çıkmış_soru', kaynak:k17as, guvenDurumu:'kontrol_edildi', kontrolEden:'aof.tc-gorsel' },

  { id:'ISL106-076', dersKodu:'İŞL106U', dersAdi:'İşletme Fonksiyonları', unite:5, konu:'Nakit Döngüsü',
    soru:'Nakde dönüşüm süreci nedir?',
    secenekler:{A:'İşletmenin hammaddelere yaptığı ödemeler ile müşterilerden tahsil ettiği ödemeler arasındaki zamandır.',B:'Ürünlerin stokta geçen süresi ile borç ödeme süresi arasındaki zamandır.',C:'İşe başlama süresi ile ürünlerin stokta geçen süresi arasındaki zamandır.',D:'Ticari borçların ödenme süresi ile ürünlerin stokta geçen süresi arasındaki zamandır.',E:'Ürünlerin satış tarihi ile işletmeye yapılan ödemelerin tarihi arasındaki zamandır.'},
    dogruCevap:'A', aciklama:'Nakde dönüşüm süresi; hammadde ödemesinden müşteri tahsilatına kadar geçen süredir. Kısa olması arzu edilir çünkü kısa süre işletmenin nakde daha hızlı kavuştuğunu gösterir.',
    nedenDigerleriDegil:'Diğer tanımlar farklı finansal süreleri karıştırır; A hammadde ödemesi ile tahsilat arasındaki süreyi doğru tanımlar.',
    soruTipi:'çıkmış_soru', kaynak:k17as, guvenDurumu:'kontrol_edildi', kontrolEden:'aof.tc-gorsel' },

  { id:'ISL106-077', dersKodu:'İŞL106U', dersAdi:'İşletme Fonksiyonları', unite:5, konu:'Sermaye Yapısı',
    soru:'Aşağıdakilerden hangisi işletmelerdeki sermaye yapısı kararını etkileyen faktörlerden biri değildir?',
    secenekler:{A:'Rakip firmalarda çalışan yabancı uyruklu yönetici sayısı',B:'İşletmenin risk düzeyi',C:'Finansal esneklik',D:'Vergi ve çeşitli maliyetler',E:'İşletmenin saldırgan ya da tutucu yapısı'},
    dogruCevap:'A', aciklama:'Sermaye yapısı kararını etkileyen faktörler: Risk düzeyi, finansal esneklik, vergi, işletmenin büyüme stratejisi, sektör koşulları. Rakip firmalardaki yabancı uyruklu yönetici sayısının sermaye yapısıyla doğrudan ilişkisi yoktur.',
    nedenDigerleriDegil:'B, C, D, E sermaye yapısı kararında dikkate alınan gerçek faktörlerdir.',
    soruTipi:'çıkmış_soru', kaynak:k17as, guvenDurumu:'kontrol_edildi', kontrolEden:'aof.tc-gorsel' },

  { id:'ISL106-078', dersKodu:'İŞL106U', dersAdi:'İşletme Fonksiyonları', unite:5, konu:'Sermaye Bütçelemesi',
    soru:'Uzun süreli yatırım kârlarında kullanılan ve yatırımın bugün gerektireceği nakit çıkışları ile yatırımdan gelecek yıllar boyunca sağlanacak nakit girişlerinin bir arada gösterildiği finansal planlama aracına ne ad verilir?',
    secenekler:{A:'Fiyat düzenlemesi',B:'Stok yapısı',C:'Kişisel satış düzenlemesi',D:'Sermaye bütçelemesi',E:'Satış tahminleri'},
    dogruCevap:'D', aciklama:'Sermaye bütçelemesi; uzun vadeli yatırım projelerinin değerlendirilmesinde kullanılır. Bugünkü nakit çıkışları ile gelecekteki nakit girişlerini bir arada ele alarak yatırımın geri dönüşünü hesaplar (NPV, IRR gibi yöntemler).',
    nedenDigerleriDegil:'Fiyat düzenlemesi fiyatlandırma; stok yapısı envanter; satış tahmini gelir planı; kişisel satış pazarlama faaliyetidir.',
    soruTipi:'çıkmış_soru', kaynak:k17as, guvenDurumu:'kontrol_edildi', kontrolEden:'aof.tc-gorsel' },

  { id:'ISL106-079', dersKodu:'İŞL106U', dersAdi:'İşletme Fonksiyonları', unite:5, konu:'Bilanço',
    soru:'İşletmede en fazla bir yıl içinde paraya dönüşen varlıklara ne ad verilir?',
    secenekler:{A:'Yabancı kaynaklar',B:'Dönen varlıklar',C:'Kâr',D:'Öz sermaye',E:'Ortaklık payları'},
    dogruCevap:'B', aciklama:'Dönen varlıklar; bir yıl veya normal faaliyet döngüsü içinde paraya dönüşen, satılan veya kullanılan varlıklardır. Kasa, alacaklar, stoklar gibi kalemler dönen varlıklar arasında sayılır.',
    nedenDigerleriDegil:'Yabancı kaynaklar borç; öz sermaye ve ortaklık payları finansman kaynağı; kâr gelir unsurudur.',
    soruTipi:'çıkmış_soru', kaynak:k17as, guvenDurumu:'kontrol_edildi', kontrolEden:'aof.tc-gorsel' },

  { id:'ISL106-080', dersKodu:'İŞL106U', dersAdi:'İşletme Fonksiyonları', unite:5, konu:'Bilanço',
    soru:'Aşağıdakilerden hangisi bilançodaki pasif kısımda yer alır?',
    secenekler:{A:'Duran varlıklar',B:'Alacaklar',C:'Stoklar',D:'Uzun süreli yabancı kaynaklar',E:'Dönen varlıklar'},
    dogruCevap:'D', aciklama:'Bilançonun pasif tarafı kaynakları gösterir: Kısa vadeli yabancı kaynaklar, Uzun vadeli yabancı kaynaklar ve Öz kaynaklar. Duran/dönen varlıklar, alacaklar ve stoklar aktif taraftadır.',
    nedenDigerleriDegil:'A, B, C, E varlıkları ifade eden aktif kalemlerdir; pasif = kaynaklar (borç + öz sermaye).',
    soruTipi:'çıkmış_soru', kaynak:k17as, guvenDurumu:'kontrol_edildi', kontrolEden:'aof.tc-gorsel' },
];

const guncellenmis = [...sorular, ...yeni];
fs.writeFileSync(filePath, JSON.stringify(guncellenmis, null, 2), 'utf8');

const isl106 = guncellenmis.filter(s => s.dersKodu === 'İŞL106U');
console.log(`✓ Toplam ${guncellenmis.length} soru. İŞL106U: ${isl106.length} soru (${isl106.filter(s=>s.guvenDurumu==='kontrol_edildi').length} kontrol_edildi)`);
