const fs = require('fs');
const path = require('path');
const dataPath = path.join(__dirname, '../src/data/questions.json');
const data = JSON.parse(fs.readFileSync(dataPath, 'utf8'));

const yeni = [
  // 2018 arasinav
  { id:'ING102-021', unite:1, konu:'Present Simple Negative', soru:'I ------- wake up early at weekends.', secenekler:{A:"doesn't",B:"don't",C:"am not",D:"isn't",E:"does"}, dogruCevap:'B', aciklama:"Correct answer is B. With 'I' in negative simple present, we use 'don't' (do not). 'Doesn't' is for third person singular (he/she/it).", kaynak:{tur:'arasinav',yil:2018,donem:'güz'} },
  { id:'ING102-022', unite:2, konu:'Short Answers / Agreement', soru:"A: I can't stand football.  B: I ------- either.", secenekler:{A:"can't",B:"could",C:"am",D:"don't",E:"do"}, dogruCevap:'A', aciklama:"Correct answer is A. When agreeing with a negative statement, we repeat the auxiliary: 'I can't either.' 'Either' is used in negative agreement.", kaynak:{tur:'arasinav',yil:2018,donem:'güz'} },
  { id:'ING102-023', unite:2, konu:'Short Answers / Agreement', soru:'A: I love trekking in spring.  B: -------', secenekler:{A:'So do I.',B:"I don't.",C:"I'm not.",D:'Neither do I.',E:'I do too.'}, dogruCevap:'E', aciklama:"Correct answer is E. 'I do too' and 'So do I' both agree with a positive statement. The answer E matches the positive tone and is a valid agreement form.", kaynak:{tur:'arasinav',yil:2018,donem:'güz'} },
  { id:'ING102-024', unite:1, konu:'Present Simple Questions', soru:'A: What do you ------- on the weekends?  B: I usually visit my family.', secenekler:{A:'make',B:'have',C:'take',D:'are doing',E:'do'}, dogruCevap:'E', aciklama:"Correct answer is E. 'What do you do?' is the standard question for habitual activities. 'do' is the main verb here meaning to perform/engage in activities.", kaynak:{tur:'arasinav',yil:2018,donem:'güz'} },
  { id:'ING102-025', unite:1, konu:'Present Simple Questions', soru:'------- you like cooking for your children?', secenekler:{A:'Are',B:'Is',C:'Does',D:'Do',E:'Have'}, dogruCevap:'D', aciklama:"Correct answer is D. Simple present question with 'you' requires auxiliary 'Do'. 'Does' is only for third person singular.", kaynak:{tur:'arasinav',yil:2018,donem:'güz'} },
  { id:'ING102-026', unite:3, konu:'Object Pronouns', soru:"I know you like rock music but I don't like --------.", secenekler:{A:'him',B:'you',C:'it',D:'them',E:'me'}, dogruCevap:'C', aciklama:"Correct answer is C. 'Rock music' is a thing (not a person), so we use the neuter object pronoun 'it'.", kaynak:{tur:'arasinav',yil:2018,donem:'güz'} },
  { id:'ING102-027', unite:1, konu:'Verb Patterns (Gerund)', soru:'Simon enjoys ------- TV at the weekends.', secenekler:{A:'to watch',B:'watch',C:'to watching',D:'watching',E:'watched'}, dogruCevap:'D', aciklama:"Correct answer is D. 'Enjoy' is always followed by a gerund (-ing form): enjoy + watching. It cannot be followed by infinitive.", kaynak:{tur:'arasinav',yil:2018,donem:'güz'} },
  { id:'ING102-028', unite:1, konu:'Present Simple Negative', soru:"I ------- in December because it's too cold.", secenekler:{A:"don't swim",B:"am not swimming",C:"doesn't swim",D:"swim not",E:"not swim"}, dogruCevap:'A', aciklama:"Correct answer is A. First person simple present negative: 'I don't swim'. This expresses a general habitual fact.", kaynak:{tur:'arasinav',yil:2018,donem:'güz'} },
  { id:'ING102-029', unite:4, konu:'Conjunctions', soru:'I usually do not go out ------- I have a cold.', secenekler:{A:'if',B:'but',C:'while',D:'because',E:'although'}, dogruCevap:'A', aciklama:"Correct answer is A. 'If I have a cold' = conditional clause meaning 'when/whenever I have a cold'. This expresses a habitual condition.", kaynak:{tur:'arasinav',yil:2018,donem:'güz'} },
  { id:'ING102-030', unite:3, konu:'Verb Patterns (Infinitive)', soru:"It's important to ------- a foreign language.", secenekler:{A:'speaking',B:'speaks',C:'spoke',D:'spoken',E:'learn'}, dogruCevap:'E', aciklama:"Correct answer is E. After 'to' (infinitive marker), we use the base form of the verb: 'to learn'. 'Speaking' would require 'It's important for/about speaking'.", kaynak:{tur:'arasinav',yil:2018,donem:'güz'} },
  { id:'ING102-031', unite:2, konu:'Present Continuous', soru:'I ------- lunch with my teachers today.', secenekler:{A:'have',B:'am having',C:'has',D:'was having',E:'had'}, dogruCevap:'B', aciklama:"Correct answer is B. Present continuous (am/is/are + -ing) is used for activities happening now or arranged for today: 'I am having lunch today'.", kaynak:{tur:'arasinav',yil:2018,donem:'güz'} },
  { id:'ING102-032', unite:3, konu:'Ordinal Numbers', soru:'The day after tomorrow is the 10th (-------) of August.', secenekler:{A:'ten',B:'tenths',C:'tens',D:'tenner',E:'tenth'}, dogruCevap:'E', aciklama:"Correct answer is E. '10th' in words is 'tenth'. Ordinal numbers are used for dates: first, second, third, fourth… tenth.", kaynak:{tur:'arasinav',yil:2018,donem:'güz'} },
  { id:'ING102-033', unite:2, konu:'Future (be going to)', soru:'We ------- to organize a birthday party for Jeremy.', secenekler:{A:'go',B:'going',C:'will go',D:'are going to',E:'are gone'}, dogruCevap:'D', aciklama:"Correct answer is D. 'Be going to + infinitive' expresses a future plan or intention: 'We are going to organize'. 'Are going' alone (without 'to organize') would need a different structure.", kaynak:{tur:'arasinav',yil:2018,donem:'güz'} },
  { id:'ING102-034', unite:2, konu:'Present Continuous (Future)', soru:'I ------- my friends outside the library at 9 o\'clock this evening.', secenekler:{A:'meet',B:'will meet',C:'am meeting',D:'met',E:'have met'}, dogruCevap:'C', aciklama:"Correct answer is C. Present continuous is used for fixed future arrangements: 'I am meeting my friends at 9'. The specific time ('at 9') signals a pre-arranged event.", kaynak:{tur:'arasinav',yil:2018,donem:'güz'} },
  { id:'ING102-035', unite:5, konu:'Past Simple Questions', soru:'A: Where ------- Bülent born?  B: He was born in Tekirdağ.', secenekler:{A:'was',B:'were',C:'is',D:'did',E:'has'}, dogruCevap:'A', aciklama:"Correct answer is A. 'Where was he born?' — passive past simple question. Bülent is singular, so 'was' is correct (not 'were').", kaynak:{tur:'arasinav',yil:2018,donem:'güz'} },
  { id:'ING102-036', unite:5, konu:'Past Simple Questions', soru:'A: When ------- Sercan move to Bursa?  B: Four years ago.', secenekler:{A:'was',B:'were',C:'did',D:'has',E:'is'}, dogruCevap:'C', aciklama:"Correct answer is C. Past simple question uses auxiliary 'did': 'When did Sercan move?' The answer 'four years ago' confirms past simple.", kaynak:{tur:'arasinav',yil:2018,donem:'güz'} },
  { id:'ING102-037', unite:4, konu:'Prepositions of Time', soru:'I finished my university degree ------- 2005.', secenekler:{A:'at',B:'in',C:'on',D:'by',E:'during'}, dogruCevap:'B', aciklama:"Correct answer is B. We use 'in' with years: 'in 2005'. We use 'on' for specific dates, 'at' for clock times.", kaynak:{tur:'arasinav',yil:2018,donem:'güz'} },
  { id:'ING102-038', unite:3, konu:'There is / There are', soru:'------- many shopping malls in town?', secenekler:{A:'Is there',B:'There is',C:'Are there',D:'There are',E:'Is it'}, dogruCevap:'C', aciklama:"Correct answer is C. 'Many shopping malls' is plural, so we use 'Are there'. Question form: 'Are there many...?' (are + there + plural noun)", kaynak:{tur:'arasinav',yil:2018,donem:'güz'} },
  { id:'ING102-039', unite:3, konu:'There is / There are', soru:'------- an Internet café on every corner.', secenekler:{A:"There are",B:"There's",C:"Are there",D:"Is there",E:"There were"}, dogruCevap:'B', aciklama:"Correct answer is B. 'An Internet café' is singular, so 'There's' (There is) is correct. 'There are' would be used with plural nouns.", kaynak:{tur:'arasinav',yil:2018,donem:'güz'} },
  { id:'ING102-040', unite:4, konu:'Modal Verbs', soru:'A: How ------- I help?  B: Do you know the way to the hospital?', secenekler:{A:'should',B:'would',C:'must',D:'can',E:'may'}, dogruCevap:'D', aciklama:"Correct answer is D. 'How can I help?' is the standard polite offer. 'Can' expresses ability/offer here.", kaynak:{tur:'arasinav',yil:2018,donem:'güz'} },

  // 2018 dönemsonu
  { id:'ING102-041', unite:2, konu:'Present Continuous (Future)', soru:'We ------- our friends at 6:30 this evening.', secenekler:{A:'meet',B:'will meet',C:'are meeting',D:'met',E:'have met'}, dogruCevap:'C', aciklama:"Correct answer is C. Present continuous is used for a planned/arranged future event: 'We are meeting our friends at 6:30'. The specific time confirms a prior arrangement.", kaynak:{tur:'donemsonu',yil:2018,donem:'bahar'} },
  { id:'ING102-042', unite:4, konu:'Modal Verbs (Polite Request)', soru:'------- you recommend a cheap restaurant?', secenekler:{A:'Shall',B:'Could',C:'Must',D:'Should',E:'Would'}, dogruCevap:'B', aciklama:"Correct answer is B. 'Could you...?' is used for polite requests. 'Could you recommend a cheap restaurant?' is asking for a favor politely.", kaynak:{tur:'donemsonu',yil:2018,donem:'bahar'} },
  { id:'ING102-043', unite:4, konu:'Prepositions of Time', soru:'I lived with my grandparents ------- last year.', secenekler:{A:'since',B:'until',C:'for',D:'during',E:'from'}, dogruCevap:'B', aciklama:"Correct answer is B. 'Until last year' means 'up to last year' — the action continued up to that point in time. 'Since' needs a present perfect tense.", kaynak:{tur:'donemsonu',yil:2018,donem:'bahar'} },
  { id:'ING102-044', unite:2, konu:'Present Continuous', soru:'Kate ------- a lot of fast food these days.', secenekler:{A:'is eating',B:'eats',C:'eat',D:'are eating',E:'was eating'}, dogruCevap:'A', aciklama:"Correct answer is A. 'These days' signals a temporary current trend. Present continuous (is eating) is used for activities happening around now. Kate = third person singular → 'is'.", kaynak:{tur:'donemsonu',yil:2018,donem:'bahar'} },
  { id:'ING102-045', unite:4, konu:'Conjunctions', soru:'Sandra goes to the gym ------- she wants to be fit.', secenekler:{A:'although',B:'while',C:'unless',D:'because',E:'but'}, dogruCevap:'D', aciklama:"Correct answer is D. 'Because' introduces the reason: Sandra goes to the gym because (= the reason is) she wants to be fit.", kaynak:{tur:'donemsonu',yil:2018,donem:'bahar'} },
  { id:'ING102-046', unite:1, konu:'Present Simple Questions', soru:'------- your sister often take medication for her headaches?', secenekler:{A:'Is',B:'Do',C:'Are',D:'Has',E:'Does'}, dogruCevap:'E', aciklama:"Correct answer is E. 'Your sister' is third person singular, so we use 'Does' for present simple questions. 'Do' is for I/you/we/they.", kaynak:{tur:'donemsonu',yil:2018,donem:'bahar'} },
  { id:'ING102-047', unite:3, konu:'Impersonal It', soru:"------- expensive to stay in a 7-star hotel.", secenekler:{A:"They're",B:"Its",C:"That's",D:"This is",E:"It's"}, dogruCevap:'E', aciklama:"Correct answer is E. 'It's + adjective + to + infinitive' is the standard structure for expressing general facts: 'It's expensive to stay...'", kaynak:{tur:'donemsonu',yil:2018,donem:'bahar'} },
  { id:'ING102-048', unite:5, konu:'Vocabulary (Travel)', soru:'I want to ------- so I know what to see in Paris before I go.', secenekler:{A:'take a taxi',B:'check in online',C:'book a room',D:'pack my suitcase',E:'buy a guidebook'}, dogruCevap:'E', aciklama:"Correct answer is E. A guidebook gives information about what to see and do in a place. That's exactly what the speaker needs before visiting Paris.", kaynak:{tur:'donemsonu',yil:2018,donem:'bahar'} },
  { id:'ING102-049', unite:5, konu:'Vocabulary (Daily Objects)', soru:'Can I borrow your -------? I want to wash my hair.', secenekler:{A:'toothbrush',B:'towel',C:'shampoo',D:'razor',E:'comb'}, dogruCevap:'C', aciklama:"Correct answer is C. Shampoo is used to wash hair. The sentence clearly links the item to washing hair.", kaynak:{tur:'donemsonu',yil:2018,donem:'bahar'} },
  { id:'ING102-050', unite:4, konu:'Dialogue / Expressions', soru:"A: Could you open the window please? It's very hot.  B: Sure. -------", secenekler:{A:"I'd rather not.",B:"It doesn't matter.",C:"No problem.",D:"Why not?",E:"Never mind."}, dogruCevap:'C', aciklama:"Correct answer is C. 'No problem' is a natural polite response to agreeing to do something that was requested. 'Sure. No problem.' = of course, happy to help.", kaynak:{tur:'donemsonu',yil:2018,donem:'bahar'} },
  { id:'ING102-051', unite:5, konu:'Past Continuous', soru:'What ------- when I saw you yesterday?', secenekler:{A:'were you eating',B:'you were eating',C:'did you eat',D:'you ate',E:'are you eating'}, dogruCevap:'A', aciklama:"Correct answer is A. Past continuous question: 'What were you eating?' — an ongoing action interrupted by seeing (simple past). Question word order: Wh- + were + subject + -ing.", kaynak:{tur:'donemsonu',yil:2018,donem:'bahar'} },
  { id:'ING102-052', unite:3, konu:'Reflexive Pronouns', soru:'I enjoy spending time by -------.',  secenekler:{A:'yourself',B:'himself',C:'herself',D:'myself',E:'itself'}, dogruCevap:'D', aciklama:"Correct answer is D. 'By myself' means alone, on my own. The subject is 'I', so the reflexive pronoun is 'myself'.", kaynak:{tur:'donemsonu',yil:2018,donem:'bahar'} },
  { id:'ING102-053', unite:4, konu:'Opinion Expressions', soru:'-------, most people spend too much time on the Internet.', secenekler:{A:'At the end',B:'In the end',C:'For instance',D:'In my opinion',E:'As a result'}, dogruCevap:'D', aciklama:"Correct answer is D. 'In my opinion' is the standard expression for introducing a personal viewpoint or belief.", kaynak:{tur:'donemsonu',yil:2018,donem:'bahar'} },
  { id:'ING102-054', unite:6, konu:'Comparatives', soru:'I now work ------- hours than I did last year.', secenekler:{A:'less',B:'little',C:'few',D:'fewer',E:'more less'}, dogruCevap:'D', aciklama:"Correct answer is D. 'Hours' is a countable noun, so we use 'fewer' (not 'less') in comparisons: 'fewer hours'. 'Less' is for uncountable nouns.", kaynak:{tur:'donemsonu',yil:2018,donem:'bahar'} },
  { id:'ING102-055', unite:6, konu:'Comparatives', soru:'Playing tennis is ------- than playing football.', secenekler:{A:'most fun',B:'funnest',C:'more funny',D:'funnier',E:'more fun'}, dogruCevap:'E', aciklama:"Correct answer is E. 'Fun' as an adjective uses 'more' for comparative: 'more fun'. (Some grammarians also accept 'funner' informally, but 'more fun' is the standard form.)", kaynak:{tur:'donemsonu',yil:2018,donem:'bahar'} },
  { id:'ING102-056', unite:3, konu:'Describing People (Have got)', soru:'A: Who ------- dark hair in your class?  B: Melis does.', secenekler:{A:'has got',B:'have got',C:'had got',D:'is having',E:'does have'}, dogruCevap:'A', aciklama:"Correct answer is A. 'Who has got dark hair?' — 'who' takes a singular verb (has got) when asking about a person with a physical characteristic.", kaynak:{tur:'donemsonu',yil:2018,donem:'bahar'} },
  { id:'ING102-057', unite:3, konu:'Relative Clauses / Participles', soru:'Mark is the man ------- to your Dad.', secenekler:{A:'is talking',B:'who is talked',C:'talking',D:'who talks',E:'talked'}, dogruCevap:'C', aciklama:"Correct answer is C. A reduced relative clause (participial phrase): 'the man talking to your Dad' = the man who is talking to your Dad. 'Talking' identifies which man.", kaynak:{tur:'donemsonu',yil:2018,donem:'bahar'} },
  { id:'ING102-058', unite:3, konu:'Describing People (Clothes)', soru:'The woman ------- the gray sweater looks very nice.', secenekler:{A:'on',B:'in',C:'with',D:'wearing',E:'at'}, dogruCevap:'B', aciklama:"Correct answer is B. 'The woman in the gray sweater' = the woman wearing the gray sweater. 'In' is used to describe clothing someone is wearing.", kaynak:{tur:'donemsonu',yil:2018,donem:'bahar'} },
  { id:'ING102-059', unite:6, konu:'Future (Will) - Promise', soru:"B: Don't panic! I ------- late this time.", secenekler:{A:"won't be",B:"am not",C:"will be",D:"am being",E:"was not"}, dogruCevap:'A', aciklama:"Correct answer is A. 'Won't be' (will not be) is used for a promise or decision about the future: 'I won't be late this time' = I promise I will not be late.", kaynak:{tur:'donemsonu',yil:2018,donem:'bahar'} },
  { id:'ING102-060', unite:6, konu:'Modal Verbs (May/Might)', soru:'I ------- apply for another job soon but it\'s not definite.', secenekler:{A:'will',B:'may',C:'must',D:'should',E:'can'}, dogruCevap:'B', aciklama:"Correct answer is B. 'May' expresses possibility (not certainty): 'I may apply' = it's possible but not decided. 'It's not definite' confirms this.", kaynak:{tur:'donemsonu',yil:2018,donem:'bahar'} },

  // 2019 dönemsonu (q15 iptal - 19 soru)
  { id:'ING102-061', unite:3, konu:'Vocabulary (Months)', soru:'------- is the sixth month of the year.', secenekler:{A:'June',B:'May',C:'July',D:'April',E:'August'}, dogruCevap:'A', aciklama:"Correct answer is A. June is the 6th month of the year: January(1), February(2), March(3), April(4), May(5), June(6).", kaynak:{tur:'donemsonu',yil:2019,donem:'bahar'} },
  { id:'ING102-062', unite:6, konu:'Quantifiers', soru:'The exam was very difficult. ------- the students failed.', secenekler:{A:'None',B:'A lot',C:'No',D:'Most of',E:'The most'}, dogruCevap:'D', aciklama:"Correct answer is D. 'Most of the students' = the majority of the students. 'Most of' is followed by 'the + noun'. 'Most' alone without 'of' would also work but is not given.", kaynak:{tur:'donemsonu',yil:2019,donem:'bahar'} },
  { id:'ING102-063', unite:1, konu:'Short Answers', soru:'A: Are they students?  B: Yes, -------.', secenekler:{A:"we're",B:'you are',C:'there are',D:'we are',E:'they are'}, dogruCevap:'E', aciklama:"Correct answer is E. Short answer to 'Are they...?' is 'Yes, they are.' The pronoun must match the subject of the question.", kaynak:{tur:'donemsonu',yil:2019,donem:'bahar'} },
  { id:'ING102-064', unite:1, konu:'Short Answers', soru:'A: Does Mark usually walk to college?  B: Yes, he -------.', secenekler:{A:'can',B:'would',C:'has',D:'is',E:'does'}, dogruCevap:'E', aciklama:"Correct answer is E. Short affirmative answer to 'Does he...?' is 'Yes, he does.' The auxiliary matches the question.", kaynak:{tur:'donemsonu',yil:2019,donem:'bahar'} },
  { id:'ING102-065', unite:3, konu:'There is / There are', soru:'------- any jewelry stores in the city center?', secenekler:{A:'Is it',B:'Are they',C:'Is there',D:'Are there',E:'Are those'}, dogruCevap:'D', aciklama:"Correct answer is D. 'Jewelry stores' is plural, so 'Are there' is needed. Question form: Are there + any + plural noun?", kaynak:{tur:'donemsonu',yil:2019,donem:'bahar'} },
  { id:'ING102-066', unite:3, konu:'Object Pronouns', soru:'Mrs. Aydın is our new English teacher. I like ------- very much.', secenekler:{A:'him',B:'you',C:'her',D:'us',E:'it'}, dogruCevap:'C', aciklama:"Correct answer is C. Mrs. Aydın is a woman, so the object pronoun is 'her'. 'I like her very much.'", kaynak:{tur:'donemsonu',yil:2019,donem:'bahar'} },
  { id:'ING102-067', unite:4, konu:'Modal Verbs (Advice)', soru:"A: We're taking a taxi to the airport at 3 o'clock.  B: Don't ------- your passports and tickets.", secenekler:{A:'forget to take',B:'you take',C:'want to take',D:'should take',E:'a good idea to take'}, dogruCevap:'A', aciklama:"Correct answer is A. 'Don't forget to take your passports and tickets' is a natural warning/reminder. 'forget to take' fits after 'Don't'.", kaynak:{tur:'donemsonu',yil:2019,donem:'bahar'} },
  { id:'ING102-068', unite:4, konu:'Purpose (Infinitive of Purpose)', soru:'I am going to the supermarket ------- buy some food.', secenekler:{A:'then',B:'as',C:'to',D:'for',E:'so'}, dogruCevap:'C', aciklama:"Correct answer is C. Infinitive of purpose: 'I'm going to the supermarket to buy some food.' 'To' + infinitive expresses the purpose or reason for going.", kaynak:{tur:'donemsonu',yil:2019,donem:'bahar'} },
  { id:'ING102-069', unite:3, konu:'Possessive Adjectives', soru:'A: Are these ------- books?  B: Yes, they are mine.', secenekler:{A:'my',B:'his',C:'her',D:'their',E:'your'}, dogruCevap:'E', aciklama:"Correct answer is E. B answers 'they are mine' (my books), so A must be asking 'Are these your books?' — asking about B's possession.", kaynak:{tur:'donemsonu',yil:2019,donem:'bahar'} },
  { id:'ING102-070', unite:4, konu:'Modal Verbs (Polite Request)', soru:'A: ------- if I borrow your cell phone?  B: Sure. Go ahead.', secenekler:{A:'Could you mind',B:'Did you mind',C:"Don't you mind",D:'Do you mind',E:'Would you mind'}, dogruCevap:'E', aciklama:"Correct answer is E. 'Would you mind if I...?' is the polite way to ask permission. Answer 'Sure, go ahead' confirms agreement.", kaynak:{tur:'donemsonu',yil:2019,donem:'bahar'} },
  { id:'ING102-071', unite:5, konu:'Past Continuous', soru:'What ------- when I saw you yesterday?', secenekler:{A:'were you eating',B:'you were eating',C:'did you eat',D:'you ate',E:'are you eating'}, dogruCevap:'A', aciklama:"Correct answer is A. Past continuous question for an ongoing past action: 'What were you eating?' The action was in progress when the speaker saw them.", kaynak:{tur:'donemsonu',yil:2019,donem:'bahar'} },
  { id:'ING102-072', unite:3, konu:'Reflexive Pronouns', soru:'Nancy hurt ------- while she was skating.', secenekler:{A:'himself',B:'herself',C:'yourself',D:'myself',E:'itself'}, dogruCevap:'B', aciklama:"Correct answer is B. Nancy is female, so the reflexive pronoun is 'herself'. 'She hurt herself' = the action reflects back on the subject.", kaynak:{tur:'donemsonu',yil:2019,donem:'bahar'} },
  { id:'ING102-073', unite:5, konu:'Past Continuous', soru:'Eric ------- French when his mother called him.', secenekler:{A:'is studying',B:'was studying',C:'studied',D:'studies',E:'would study'}, dogruCevap:'B', aciklama:"Correct answer is B. Past continuous (was studying) describes an action in progress when another past action (called) interrupted it. Classic past continuous usage.", kaynak:{tur:'donemsonu',yil:2019,donem:'bahar'} },
  { id:'ING102-074', unite:6, konu:'Comparatives', soru:'My English is ------- than my French.', secenekler:{A:'more',B:'bad',C:'better',D:'good',E:'less'}, dogruCevap:'C', aciklama:"Correct answer is C. 'Better' is the comparative form of 'good'. My English is better = my English is at a higher level than my French.", kaynak:{tur:'donemsonu',yil:2019,donem:'bahar'} },
  // Q15 iptal
  { id:'ING102-075', unite:3, konu:'Relative Clauses / Participles', soru:'Sally is the girl ------- a piece of birthday cake.', secenekler:{A:'eat',B:'is eating',C:'eats',D:'eating',E:'who eats'}, dogruCevap:'D', aciklama:"Correct answer is D. Reduced relative clause: 'the girl eating a piece of cake' = the girl who is eating a piece of cake. Present participle 'eating' identifies which girl.", kaynak:{tur:'donemsonu',yil:2019,donem:'bahar'} },
  { id:'ING102-076', unite:3, konu:'Describing People (Have got)', soru:'A: Who ------- curly hair in your family?  B: My brother.', secenekler:{A:'gets',B:'has got',C:'got',D:'does get',E:'does have'}, dogruCevap:'B', aciklama:"Correct answer is B. 'Who has got curly hair?' — 'have got' is used to describe physical characteristics. 'Who' as subject takes 'has got' (singular).", kaynak:{tur:'donemsonu',yil:2019,donem:'bahar'} },
  { id:'ING102-077', unite:6, konu:'Future (be going to) / Time Clauses', soru:"After we ------- married, we're going to move out of the city.", secenekler:{A:'get',B:'will get',C:'are getting',D:'are going to get',E:'got'}, dogruCevap:'A', aciklama:"Correct answer is A. In time clauses with 'after', we use present simple (not future): 'After we get married'. The main clause uses future ('going to').", kaynak:{tur:'donemsonu',yil:2019,donem:'bahar'} },
  { id:'ING102-078', unite:5, konu:'Vocabulary (Jobs)', soru:"Dan's a ------- on a national newspaper.", secenekler:{A:'police officer',B:'doctor',C:'letter carrier',D:'firefighter',E:'journalist'}, dogruCevap:'E', aciklama:"Correct answer is E. A journalist works for a newspaper/media outlet. 'Dan works on a national newspaper' → he is a journalist.", kaynak:{tur:'donemsonu',yil:2019,donem:'bahar'} },
  { id:'ING102-079', unite:6, konu:'Future (Will) - Prediction', soru:'I guess George ------- graduate from high school next year.', secenekler:{A:'going to',B:'will',C:'would',D:'maybe',E:'does'}, dogruCevap:'B', aciklama:"Correct answer is B. 'Will' is used for predictions based on opinion/belief (especially with 'I think/guess/believe'): 'I guess he will graduate'.", kaynak:{tur:'donemsonu',yil:2019,donem:'bahar'} },
];

const mevcutIdler = new Set(data.map(s => s.id));
const eklenecek = yeni.filter(s => !mevcutIdler.has(s.id));

eklenecek.forEach(s => {
  s.dersKodu = 'İNG102U';
  s.dersAdi = 'İngilizce II';
  s.soruTipi = 'çıkmış_soru';
  s.guvenDurumu = 'kontrol_edildi';
  s.kontrolEden = 'gorsel_okuma';
  s.nedenDigerleriDegil = s.nedenDigerleriDegil || '';
  s.ogretimNotu = s.ogretimNotu || '';
});

const yeniData = [...data, ...eklenecek];
fs.writeFileSync(dataPath, JSON.stringify(yeniData, null, 2), 'utf8');

const ing = yeniData.filter(s => s.dersKodu === 'İNG102U');
console.log(`✓ Toplam ${yeniData.length} soru. İNG102U: ${ing.length} soru (${ing.filter(s=>s.guvenDurumu==='kontrol_edildi').length} kontrol_edildi)`);
