const fs = require('fs');
const path = require('path');
const dataPath = path.join(__dirname, '../src/data/questions.json');
const data = JSON.parse(fs.readFileSync(dataPath, 'utf8'));

const yeni = [
  // 2018 arasinav
  { id:'ISL132-061', unite:1, konu:'Finansal Raporlama', soru:'Finansal raporlar temel olarak aşağıdakilerden hangisine göre düzenlenir?', secenekler:{A:'Vergi Usul Kanununa',B:'Türk Ticaret Kanununa',C:'Sermaye Piyasası Kanununa',D:'Muhasebe Standartlarına',E:'Genel Kabul Görmüş Muhasebe İlkelerine'}, dogruCevap:'E', aciklama:'Doğru cevap E\'dir çünkü finansal raporlar temel olarak Genel Kabul Görmüş Muhasebe İlkelerine (GKGMİ) göre düzenlenir. Bu ilkeler muhasebe uygulamalarında evrensel standartları belirler.', kaynak:{tur:'arasinav',yil:2018,donem:'güz'} },
  { id:'ISL132-062', unite:3, konu:'Amortisman', soru:'50.000 TL maliyetli bir taşıtın, 5 yıl üzerinden, azalan bakiyeler yöntemine göre hesaplanan ilk yıl amortisman tutarı kaç TL\'dir?', secenekler:{A:'20.000',B:'16.000',C:'14.000',D:'12.000',E:'10.000'}, dogruCevap:'A', aciklama:'Doğru cevap A\'dır çünkü 5 yıllık normal amortisman oranı %20\'dir. Azalan bakiyeler yönteminde bu oran iki katına çıkar: %40. İlk yıl amortisman = 50.000 × %40 = 20.000 TL.', kaynak:{tur:'arasinav',yil:2018,donem:'güz'} },
  { id:'ISL132-063', unite:4, konu:'Ticari Mal İşlemleri', soru:'Aralıklı envanter yönteminde, satış iade işlemi ile ilgili aşağıdaki ifadelerden hangisi doğrudur?', secenekler:{A:'Alıcılar hesabına alacak, satış iadeleri hesabına borç kaydı yapılır.',B:'Ticari mallar hesabına borç, satış iadeleri hesabına alacak kaydı yapılır.',C:'Satıcılar hesabına alacak, satış iadeleri hesabına borç kaydı yapılır.',D:'Ticari mallar hesabına alacak, satış iadeleri hesabına borç kaydı yapılır.',E:'Yurtiçi satışlar hesabına borç, satış iadeleri hesabına alacak kaydı yapılır.'}, dogruCevap:'A', aciklama:'Doğru cevap A\'dır çünkü satış iadesi yapıldığında: Satış İadeleri ve İndirimleri hesabı borçlanır (geliri azaltır), Alıcılar hesabı alacaklanır (alacak azalır). Kısaca: Alıcılar alacak, Satış İadeleri borç.', kaynak:{tur:'arasinav',yil:2018,donem:'güz'} },
  { id:'ISL132-064', unite:2, konu:'Hesap Türleri', soru:'Aşağıdaki işlemlerden hangisi hem varlıklarda hem de borçlarda azalışa neden olur?', secenekler:{A:'Peşin makine satılması',B:'Peşin olarak makine alımı',C:'Amortisman ayrılması',D:'Borcun kasadan ödenmesi',E:'Alacağın tahsil edilmesi'}, dogruCevap:'D', aciklama:'Doğru cevap D\'dir çünkü borcun kasadan ödenmesi işleminde Kasa (varlık) azalır ve Borç hesabı (borç) da azalır. Her iki taraf da aynı anda küçülür.', kaynak:{tur:'arasinav',yil:2018,donem:'güz'} },
  { id:'ISL132-065', unite:2, konu:'Hesap Kuralları', soru:'Aşağıdaki ifadelerden hangileri doğrudur? (I. Varlıklardaki artışlar borç tarafta gösterilir. II. Gelirlerdeki artışlar borç tarafta gösterilir. III. Sermayedeki artışlar alacak tarafta gösterilir. IV. Varlıklardaki artışlar alacak tarafta gösterilir.)', secenekler:{A:'I ve II',B:'I ve III',C:'I ve IV',D:'II ve III',E:'III ve IV'}, dogruCevap:'B', aciklama:'Doğru cevap B\'dir çünkü varlıklar artarken borç (debit) tarafına, sermaye artarken alacak (credit) tarafına yazılır. Gelirler artarken alacak tarafına yazılır (II yanlış), varlıklar borç tarafında artar (IV yanlış).', kaynak:{tur:'arasinav',yil:2018,donem:'güz'} },
  { id:'ISL132-066', unite:3, konu:'Amortisman', soru:'20 Eylül\'de, 60.000 TL maliyetle aktifleştirilen bir taşıt için kıst amortisman uygulanmaktadır. Amortisman süresi 5 yıl olduğuna ve normal amortisman yöntemi uygulandığına göre 5. yıl amortisman tutarı kaç TL\'dir?', secenekler:{A:'12.000',B:'15.000',C:'20.000',D:'24.000',E:'26.000'}, dogruCevap:'A', aciklama:'Doğru cevap A\'dır çünkü yıllık normal amortisman = 60.000/5 = 12.000 TL. Kıst uygulamasında 5. tam yılda tam yıllık amortisman olan 12.000 TL ayrılır (kıst sadece ilk ve son yılları etkiler).', kaynak:{tur:'arasinav',yil:2018,donem:'güz'} },
  { id:'ISL132-067', unite:4, konu:'Yabancı Para İşlemleri', soru:'Kasada bulunan ve maliyeti 3.000 TL olan yabancı paraların, 2.800 TL\'ye satılması durumunda yapılacak kayıtta aşağıdakilerden hangisi doğrudur?', secenekler:{A:'Kasa hesabının hem borç hem alacağına 3.000 TL\'lik kayıt yapılır.',B:'Kasa hesabının hem borç hem alacağına 2.800 TL\'lik kayıt yapılır.',C:'Kambiyo Kârları hesabının alacağına 200 TL\'lik kayıt yapılır.',D:'Kasa hesabının borcuna 3.000 TL\'lik kayıt yapılır.',E:'Kambiyo Zararları hesabının borcuna 200 TL\'lik kayıt yapılır.'}, dogruCevap:'E', aciklama:'Doğru cevap E\'dir çünkü 3.000 TL maliyetli yabancı para 2.800 TL\'ye satılınca 200 TL kambiyo zararı oluşur. Kambiyo Zararları hesabı BORÇLANIR 200 TL, Kasa TL borç 2.800, Yabancı Para Kasası alacak 3.000.', kaynak:{tur:'arasinav',yil:2018,donem:'güz'} },
  { id:'ISL132-068', unite:1, konu:'Muhasebe Temelleri', soru:'Muhasebenin işlevlerinden olan kaydetme işlevi aşağıdakilerden hangisinde gerçekleştirilir?', secenekler:{A:'Büyük defter',B:'Muhasebe fişleri',C:'Envanter defteri',D:'Yevmiye defteri',E:'Bilanço'}, dogruCevap:'D', aciklama:'Doğru cevap D\'dir çünkü yevmiye defteri (günlük defter) muhasebe işlemlerinin kronolojik sırayla ilk kez kaydedildiği defterdir. Kaydetme işlevi burada gerçekleşir.', kaynak:{tur:'arasinav',yil:2018,donem:'güz'} },
  { id:'ISL132-069', unite:1, konu:'Muhasebe Temelleri', soru:'Muhasebenin temel amacı aşağıdakilerden hangisidir?', secenekler:{A:'İşletmenin ödeyeceği vergiyi saptamak',B:'İlgili taraflara doğru, güvenilir ve yararlı bilgi sağlamak',C:'İşletmenin girdi ve çıktılarını kaydetmek',D:'İşletmenin kârını hesaplamak',E:'Finansal tabloları düzenlemek'}, dogruCevap:'B', aciklama:'Doğru cevap B\'dir çünkü muhasebenin temel amacı işletme ile ilgili taraflara (yöneticiler, yatırımcılar, kreditörler) karar almalarına yardımcı olacak doğru, güvenilir ve yararlı bilgi sunmaktır.', kaynak:{tur:'arasinav',yil:2018,donem:'güz'} },
  { id:'ISL132-070', unite:1, konu:'Yevmiye Maddesi', soru:'Yevmiye maddesi türleri ile tanımların doğru eşleştirilmesi aşağıdakilerden hangisidir? (1.Basit madde: K=Birden çok hesap borçlanırken birden çok hesabın alacaklandığı, 2.Bileşik madde: L=Birden çok hesap borçlanırken bir hesabın alacaklandığı, 3.Karışık madde: M=Bir hesap borçlanırken bir hesabın alacaklandığı)', secenekler:{A:'1-M, 2-K, 3-L',B:'1-L, 2-K, 3-M',C:'1-M, 2-L, 3-K',D:'1-K, 2-M, 3-L',E:'1-L, 2-M, 3-K'}, dogruCevap:'C', aciklama:'Doğru cevap C\'dir çünkü basit madde: tek borç - tek alacak (M), bileşik madde: çok borç - tek alacak veya tek borç - çok alacak (L), karışık madde: çok borç - çok alacak (K).', kaynak:{tur:'arasinav',yil:2018,donem:'güz'} },
  { id:'ISL132-071', unite:2, konu:'Hesap Türleri', soru:'Aşağıdakilerden hangisi işletmenin varlık ve kaynak yapısında değişim yaratmayan işlemlerin izlendiği hesap grubudur?', secenekler:{A:'Nazım hesaplar',B:'Gelir tablosu hesapları',C:'Yardımcı hesaplar',D:'Düzenleyici hesaplar',E:'Bilanço hesapları'}, dogruCevap:'A', aciklama:'Doğru cevap A\'dır çünkü nazım hesaplar (bilanço dışı hesaplar) işletmenin varlık ve kaynak yapısında değişim yaratmayan, kefalet ve taahhüt gibi olası yükümlülüklerin izlendiği hesaplardır.', kaynak:{tur:'arasinav',yil:2018,donem:'güz'} },
  { id:'ISL132-072', unite:2, konu:'Dönen Varlıklar', soru:'Aşağıdaki işlemlerin hangisi dönen varlıklar toplamını değiştirmez?', secenekler:{A:'Ticari malların kârlı olarak peşin satılması',B:'Elde bulunan yabancı paraların kârlı olarak Türk Lirasına çevrilmesi',C:'Dönen varlıklarda bulunan hisse senetlerinin peşin olarak zararına satılması',D:'Peşin olarak ticari mal satın alınması',E:'Senet keşide edilerek taşıt satın alınması'}, dogruCevap:'E', aciklama:'Doğru cevap E\'dir çünkü senet keşide ederek taşıt alımında Taşıtlar (duran varlık) artar ve Borç Senetleri (yabancı kaynak) artar; dönen varlıklarda hiçbir değişiklik olmaz.', kaynak:{tur:'arasinav',yil:2018,donem:'güz'} },
  { id:'ISL132-073', unite:2, konu:'Dönen Varlıklar', soru:'Aşağıdakilerden hangisi Dönen Varlıklar hesap grubunda yer alır?', secenekler:{A:'Taşıtlar',B:'Demirbaşlar',C:'Binalar',D:'Mali Duran Varlıklar',E:'Gelecek Aylara Ait Giderler'}, dogruCevap:'E', aciklama:'Doğru cevap E\'dir çünkü Gelecek Aylara Ait Giderler, bir yıl içinde gidere dönüşecek peşin ödemelerdir ve dönen varlıklar grubundadır. Taşıtlar, demirbaşlar, binalar ve mali duran varlıklar duran varlık grubundadır.', kaynak:{tur:'arasinav',yil:2018,donem:'güz'} },
  { id:'ISL132-074', unite:3, konu:'Amortisman', soru:'Maliyeti 85.000 TL, birikmiş amortismanı 51.000 TL olan taşıt, KDV hariç 32.000 TL\'ye satılmıştır. Bu bilgilere göre işletmenin kâr veya zararı kaç TL\'dir?', secenekler:{A:'34.000 zarar',B:'19.000 zarar',C:'2.000 zarar',D:'2.000 kâr',E:'19.000 kâr'}, dogruCevap:'C', aciklama:'Doğru cevap C\'dir çünkü net defter değeri = 85.000 - 51.000 = 34.000 TL. Satış fiyatı 32.000 TL. Zarar = 34.000 - 32.000 = 2.000 TL.', kaynak:{tur:'arasinav',yil:2018,donem:'güz'} },
  { id:'ISL132-075', unite:3, konu:'Duran Varlık Satışı', soru:'Maliyeti 20.000 TL, birikmiş amortismanı 12.000 TL olan demirbaşlar peşin olarak yenilenmek amacıyla 10.000 TL\'ye, %18 KDV ayrıca ilave edilerek satılmıştır. Bu bilgilere göre yapılacak yevmiye kaydında aşağıdakilerden hangisi yanlıştır?', secenekler:{A:'Kasa hesabına 11.800 borç kaydedilir.',B:'Demirbaşlar hesabına 8.000 alacak kaydedilir.',C:'Hesaplanan KDV hesabına 1.800 alacak kaydedilir.',D:'Özel Fonlar hesabına 2.000 alacak kaydedilir.',E:'Birikmiş Amortismanlar hesabına 12.000 borç kaydedilir.'}, dogruCevap:'B', aciklama:'Doğru cevap B\'dir çünkü demirbaşlar hesabının maliyeti 20.000 TL\'dir ve hesaptan tamamen çıkarılması için 20.000 TL alacak kaydedilmesi gerekir. 8.000 TL değil (8.000 net defter değeridir).', kaynak:{tur:'arasinav',yil:2018,donem:'güz'} },
  { id:'ISL132-076', unite:1, konu:'Muhasebe Temelleri', soru:'Muhasebe fonksiyonları ile gerçekleştirilen işlemlerin doğru eşleştirilmesi aşağıdakilerin hangisinde verilmiştir? (1.Kaydetme: K=Finansal olaylara ilişkin verilerin günlük deftere yazılması, 2.Sınıflama: L=Defterlerdeki bilgilerin bilgi kullanıcılarına kısaltılarak sunulması, 3.Özetleme: M=Çok sayıdaki verinin benzer işlem gruplarına göre düzenlenmesi)', secenekler:{A:'1-K, 2-M, 3-L',B:'1-M, 2-K, 3-L',C:'1-L, 2-M, 3-K',D:'1-M, 2-L, 3-K',E:'1-K, 2-L, 3-M'}, dogruCevap:'A', aciklama:'Doğru cevap A\'dır çünkü Kaydetme=K (günlük deftere yazma), Sınıflama=M (benzer işlemleri gruplama), Özetleme=L (bilgileri kısaltarak sunma).', kaynak:{tur:'arasinav',yil:2018,donem:'güz'} },
  { id:'ISL132-077', unite:4, konu:'Menkul Kıymetler', soru:'Dönen varlıklar içinde yer alan ve maliyeti 5.000 TL olan hisse senetlerinin, 4.000 TL\'ye satılması ve paranın banka hesabına yatırılması durumunda aşağıdaki ifadelerden hangisi yanlıştır?', secenekler:{A:'Menkul Kıymet Satış Zararları hesabına 1.000 TL\'lik borç kaydı yapılır.',B:'Hisse senetleri hesabına 5.000 TL\'lik alacak kaydı yapılır.',C:'Banka hesabına 4.000 TL\'lik borç kaydı yapılır.',D:'Bu işlem sonucu hisse senetleri hesap bakiyesi 5.000 TL azalır.',E:'Satılan Ticari Mallar Maliyeti hesabına 5.000 TL\'lik alacak kaydı yapılır.'}, dogruCevap:'E', aciklama:'Doğru cevap E\'dir çünkü hisse senedi satışı bir menkul kıymet işlemidir, ticari mal işlemi değildir. Satılan Ticari Mallar Maliyeti hesabı bu işlemde kullanılmaz.', kaynak:{tur:'arasinav',yil:2018,donem:'güz'} },
  { id:'ISL132-078', unite:1, konu:'Muhasebe Kavramları', soru:'Finansal nitelikli olayların nasıl, ne zaman kaydedileceğini, nasıl ölçüleceğini açıklayan, muhasebe ilkelerinin dayanağını oluşturan gözleme dayalı temel düşünceler ve çıkış noktaları aşağıdakilerden hangisini tanımlamaktadır?', secenekler:{A:'Türk Ticaret Kanunu\'nu',B:'Muhasebe standartlarını',C:'Muhasebe ilkelerini',D:'Muhasebe kavramlarını',E:'Vergi Usul Kanunu\'nu'}, dogruCevap:'D', aciklama:'Doğru cevap D\'dir çünkü muhasebe kavramları, muhasebe uygulamalarının temel dayanaklarını oluşturan gözleme dayalı düşünce ve ilkeleri ifade eder (işletmenin sürekliliği, dönemsellik, maliyet esası gibi).', kaynak:{tur:'arasinav',yil:2018,donem:'güz'} },
  { id:'ISL132-079', unite:1, konu:'Muhasebe Süreci', soru:'İşletmenin belirli bir tarihte varlık ve kaynaklarının durumunu saptamak için yaptığı sayım ve değerleme işlemine ne ad verilir?', secenekler:{A:'Bilanço düzenleme',B:'Envanter çıkartma',C:'Yevmiye defteri tutma',D:'Mizan çıkartma',E:'Büyük deftere kaydetme'}, dogruCevap:'B', aciklama:'Doğru cevap B\'dir çünkü envanter çıkartma, işletmenin belirli bir tarihte sahip olduğu varlık ve kaynakların sayım, ölçüm ve değerlenmesi işlemidir.', kaynak:{tur:'arasinav',yil:2018,donem:'güz'} },
  { id:'ISL132-080', unite:1, konu:'Muhasebe Temelleri', soru:'Muhasebenin defter tutma ile ilgili işlevleri yukarıdakilerden hangileridir? (I. Kaydetme  II. Sınıflama  III. Özetleme  IV. Analiz ve yorum  V. Raporlama)', secenekler:{A:'Yalnız I',B:'I ve II',C:'I, II ve III',D:'I, II ve IV',E:'III, IV ve V'}, dogruCevap:'C', aciklama:'Doğru cevap C\'dir çünkü muhasebenin defter tutma işlevleri kaydetme, sınıflama ve özetlemedir. Analiz ve yorum ile raporlama ise daha geniş muhasebe işlevleri olup defter tutmanın ötesindedir.', kaynak:{tur:'arasinav',yil:2018,donem:'güz'} },

  // 2018 dönemsonu
  { id:'ISL132-081', unite:3, konu:'Duran Varlık Satışı', soru:'Maliyeti 85.000 TL, birikmiş amortismanı 51.000 TL olan taşıt, KDV hariç 32.000 TL\'ye satılmıştır. Bu bilgilere göre işletmenin kâr veya zararı kaç TL\'dir?', secenekler:{A:'34.000 zarar',B:'19.000 zarar',C:'2.000 zarar',D:'2.000 kâr',E:'19.000 kâr'}, dogruCevap:'C', aciklama:'Doğru cevap C\'dir çünkü net defter değeri = 85.000 - 51.000 = 34.000 TL. Satış fiyatı 32.000 TL olduğundan zarar = 34.000 - 32.000 = 2.000 TL.', kaynak:{tur:'donemsonu',yil:2018,donem:'bahar'} },
  { id:'ISL132-082', unite:5, konu:'Gelir ve Gider Hesapları', soru:'Gelirlerle ilgili aşağıdaki ifadelerden hangisi yanlıştır?', secenekler:{A:'Gelirlerdeki artışlar ilgili hesabın borcuna kaydedilir.',B:'Bilançoda yer almazlar.',C:'Gelirler öz sermayede artış yaratır.',D:'Kâr-Zarar hesabının alacak tarafına devredilirler.',E:'Gelirler tahakkuk ilkesine göre kaydedilir.'}, dogruCevap:'A', aciklama:'Doğru cevap A\'dır çünkü gelirlerdeki artışlar ilgili hesabın alacak (sağ) tarafına kaydedilir, borç tarafına değil. Gelir hesapları alacak tarafında büyür.', kaynak:{tur:'donemsonu',yil:2018,donem:'bahar'} },
  { id:'ISL132-083', unite:5, konu:'Gelir ve Gider Kavramları', soru:'Terimler ve tanımların doğru eşleştirilmesi aşağıdakilerin hangisinde verilmiştir? (1.Gelir: K=İşletmeye varlık girişi sağlayarak aktifte artışa neden olan harcama, 2.Gider: L=Satışlardan ve diğer faaliyetlerden elde edilen brüt tutar, 3.Maliyet: M=Hasılat sağlamak amacıyla yapılan aktif tükenmesi)', secenekler:{A:'1-K, 2-L, 3-M',B:'1-L, 2-M, 3-K',C:'1-K, 2-M, 3-L',D:'1-L, 2-K, 3-M',E:'1-M, 2-L, 3-K'}, dogruCevap:'B', aciklama:'Doğru cevap B\'dir çünkü Gelir=L (satış hasılatı), Gider=M (hasılat için yapılan aktif tükenmesi), Maliyet=K (aktife giriş sağlayan harcama).', kaynak:{tur:'donemsonu',yil:2018,donem:'bahar'} },
  { id:'ISL132-084', unite:6, konu:'Dönem Sonu İşlemleri', soru:'Gelecek döneme ait olup, ödemesi cari dönemde peşin yapılan giderler için yapılacak yevmiye kaydında aşağıdakilerden hangisi doğrudur?', secenekler:{A:'Gider Tahakkukları hesabı borçlandırılır.',B:'Gelecek Yıllara Ait Giderler hesabı alacaklandırılır.',C:'Diğer Çeşitli Alacaklar hesabı borçlandırılır.',D:'Genel Yönetim giderleri borçlandırılır.',E:'Gelecek Aylara Ait Giderler hesabı borçlandırılır.'}, dogruCevap:'E', aciklama:'Doğru cevap E\'dir çünkü gelecek aylara/döneme ait peşin ödenen giderlerde Gelecek Aylara Ait Giderler hesabı (aktif) BORÇLANIR; nakit ödeme yapıldığından Kasa/Banka ALACAKLANIR.', kaynak:{tur:'donemsonu',yil:2018,donem:'bahar'} },
  { id:'ISL132-085', unite:6, konu:'Dönem Sonu İşlemleri', soru:'(690 Dönem Net Karı/Zararı HS. BORÇ → 691 Dönem Karı Vergi ve Diğer Yasal Yükümlülük Karş. HS. ALACAK → 692 Dönem Net Karı HS. ALACAK) Bu yevmiye kaydı aşağıdaki işlemlerden hangisine aittir?', secenekler:{A:'Dönem kârının bilanço hesaplarına devrine',B:'Dönem kâr veya zararının hesaplanmasına',C:'Dönem kârının peşin ödenen vergi yasal yükümlülük karşılığının gösterilmesine',D:'Dönem net kârının hesaplanmasına',E:'Dönem kârının peşin ödenen vergi yasal yükümlülüğünün mahsubuna'}, dogruCevap:'D', aciklama:'Doğru cevap D\'dir çünkü bu kayıtta brüt dönem kârından (690) vergi karşılığı (691) ayrılarak net kâr (692) hesaplanmaktadır. Bu dönem net kârının hesaplanması işlemidir.', kaynak:{tur:'donemsonu',yil:2018,donem:'bahar'} },
  { id:'ISL132-086', unite:6, konu:'Dönem Sonu İşlemleri', soru:'İşletmenin elindeki faiz başlangıcı 1 Haziran olan yıllık faiz ödemeli tahvilin dönem sonu itibarıyla gerçekleşen faizi 2.890 TL\'dir. Yıllık faizin tamamı takip eden yıl haziran ayı sonunda tahsil edilecektir. Bu bilgilere göre yapılacak yevmiye kaydında aşağıdakilerden hangisi doğrudur?', secenekler:{A:'Gelir Tahakkukları Hesabı 2.890 borçlandırılır.',B:'Faiz Gelirleri Hesabı 2.890 borçlandırılır.',C:'Gelecek Aylara Ait Gelirler Hesabı 2.890 borçlandırılır.',D:'Bankalar hesabı 2.890 borçlandırılır.',E:'Diğer Olağan Gelir ve Kârlar Hesabı 2.890 alacaklandırılır.'}, dogruCevap:'A', aciklama:'Doğru cevap A\'dır çünkü faiz henüz tahsil edilmedi ancak dönem sonunda hak kazanıldı. Tahakkuk ilkesi gereği: Gelir Tahakkukları (181) BORÇ 2.890, Faiz Gelirleri ALACAK 2.890 kaydı yapılır.', kaynak:{tur:'donemsonu',yil:2018,donem:'bahar'} },
  { id:'ISL132-087', unite:1, konu:'Muhasebe Hukuku', soru:'Değerleme ölçüleri konusunda belirleyici yasal düzenlemeler aşağıdakilerden hangileridir? (I. Vergi Usul Kanunu  II. Türkiye Muhasebe ve Finansal Raporlama Standartları  III. Genel Kabul Görmüş Muhasebe İlkeleri  IV. Muhasebenin Temel Kavramları)', secenekler:{A:'Yalnız I',B:'Yalnız II',C:'I ve II',D:'I ve III',E:'III ve IV'}, dogruCevap:'C', aciklama:'Doğru cevap C\'dir çünkü değerleme ölçüleri konusunda yasal bağlayıcılığı olan düzenlemeler Vergi Usul Kanunu (VUK) ve Türkiye Muhasebe ve Finansal Raporlama Standartları\'dır (TFRS). GKGMİ ve temel kavramlar yasal değil teknik düzenlemelerdir.', kaynak:{tur:'donemsonu',yil:2018,donem:'bahar'} },
  { id:'ISL132-088', unite:4, konu:'Senetli İşlemler', soru:'(320 SATICILAR HS. BORÇ → 121 ALACAK SENETLERİ HS. ALACAK) Bu yevmiye kaydı aşağıdaki işlemlerden hangisine aittir?', secenekler:{A:'Kredili mal satın alınmasına',B:'Senetle mal satılmasına',C:'Senetsiz borca karşılık bir alacak senedi ciro edilmesine',D:'Peşin mal satılmasına',E:'Alacak senedi tahsil edilmesine'}, dogruCevap:'C', aciklama:'Doğru cevap C\'dir çünkü Satıcılar (320) borçlanıyor (satıcı borcumuz azalıyor) ve Alacak Senetleri (121) alacaklanıyor (elimizdeki senedi veriyoruz). Yani senetsiz ticari borcumuzu kapatmak için alacak senedimizi satıcıya ciro ettik.', kaynak:{tur:'donemsonu',yil:2018,donem:'bahar'} },
  { id:'ISL132-089', unite:2, konu:'Hesap Türleri', soru:'Aşağıdakilerden hangileri aktif düzenleyici hesap olarak adlandırılır? (I. Şüpheli alacaklar karşılığı  II. Borç senetleri reeskontu  III. Ödenmemiş sermaye  IV. Alacak senetleri reeskontu)', secenekler:{A:'Yalnız I',B:'Yalnız II',C:'I ve III',D:'I ve IV',E:'III ve IV'}, dogruCevap:'D', aciklama:'Doğru cevap D\'dir çünkü aktif düzenleyici hesaplar aktif (varlık) hesapların değerini düzelten hesaplardır. Şüpheli alacaklar karşılığı (alacakları düzeltir) ve alacak senetleri reeskontu (alacak senetlerini düzeltir) aktif düzenleyicidir.', kaynak:{tur:'donemsonu',yil:2018,donem:'bahar'} },
  { id:'ISL132-090', unite:1, konu:'Muhasebe Süreci', soru:'Muhasebe işlemleri belirli bir tarihte başlar ve belirli bir tarihte sona erer. İzleyen dönemde, aynı muhasebe işlemleri tekrar eder. Bu dönemlerin her birine ------- adı verilir.', secenekler:{A:'hesap dönemi',B:'sayım dönemi',C:'dönem sonu',D:'değerleme dönemi',E:'Ayarlama ve düzeltme dönemi'}, dogruCevap:'A', aciklama:'Doğru cevap A\'dır çünkü hesap dönemi, muhasebe işlemlerinin başlangıç ve bitiş tarihlerini kapsayan bir yıllık dönemdir (genellikle 1 Ocak - 31 Aralık).', kaynak:{tur:'donemsonu',yil:2018,donem:'bahar'} },
  { id:'ISL132-091', unite:1, konu:'Muhasebe Kavramları', soru:'Varlıkların değerinin enflasyon, deflasyon veya diğer piyasa değişmelerine göre her an değiştirilmesinin önüne geçmek ve uzun vadeli yatırım ve planlamalara imkân sağlamak aşağıdaki muhasebe kavramlarından hangisi ile mümkündür?', secenekler:{A:'Parayla ölçülme kavramı',B:'Dönemsellik kavramı',C:'Maliyet esası kavramı',D:'Tutarlılık kavramı',E:'İhtiyatlılık kavramı'}, dogruCevap:'C', aciklama:'Doğru cevap C\'dir çünkü maliyet esası kavramı varlıkların elde etme maliyeti ile kayıt edilmesini öngörür; piyasa değeri değişse bile defter değeri maliyet üzerinden kalır. Bu sayede değerleme tutarlı ve güvenilir olur.', kaynak:{tur:'donemsonu',yil:2018,donem:'bahar'} },
  { id:'ISL132-092', unite:2, konu:'Mali Borçlar', soru:'Aşağıdakilerden hangisi mali borçlar hesap grubunda yer almaz?', secenekler:{A:'Ertelenmiş finansal kiralama borçlanma maliyetleri',B:'Borç senetleri',C:'Uzun vadeli kredilerin anapara taksitleri ve faizleri',D:'Banka kredileri',E:'Finansal kiralama işlemlerinden borçlar'}, dogruCevap:'A', aciklama:'Doğru cevap A\'dır çünkü ertelenmiş finansal kiralama borçlanma maliyetleri pasif düzenleyici bir hesaptır (finansal kiralama borçlarından düşülür); mali borçların içinde gerçek bir borç değildir.', kaynak:{tur:'donemsonu',yil:2018,donem:'bahar'} },
  { id:'ISL132-093', unite:1, konu:'Finansal Tablolar', soru:'Bankalar, kredi talebinde bulunan işletmelerden aşağıdaki belgelerden hangisini istemez?', secenekler:{A:'Son üç yıla ilişkin nakit akış tablosunu',B:'Son üç yıla ilişkin gelir tablosunu',C:'Şirket yetkililerinin imza sirkülerini',D:'Son üç yıla ilişkin bilançolarını',E:'Ticaret sicil belgesini'}, dogruCevap:'A', aciklama:'Doğru cevap A\'dır çünkü Türkiye\'de bankalar kredi değerlendirmesinde standart olarak bilanço, gelir tablosu, imza sirküleri ve ticaret sicil belgesi ister. Nakit akış tablosu küçük ve orta ölçekli işletmelerden zorunlu olarak talep edilmez.', kaynak:{tur:'donemsonu',yil:2018,donem:'bahar'} },
  { id:'ISL132-094', unite:1, konu:'Muhasebe Süreci', soru:'Yeni kurulan bir işletmede, aşağıdakilerden hangisi dönem başı açılış işlemleri kapsamında yer almaz?', secenekler:{A:'Bilanço düzenlenmesi',B:'Genel geçici mizan',C:'Yevmiye defterine kayıt',D:'Büyük deftere kayıt',E:'Envanter çıkarılması'}, dogruCevap:'B', aciklama:'Doğru cevap B\'dir çünkü genel geçici mizan dönem içi veya dönem sonu hazırlanan bir kontrol cetvelidir; açılış işlemleri kapsamında yer almaz. Açılışta bilanço, yevmiye ve büyük deftere kayıt yapılır.', kaynak:{tur:'donemsonu',yil:2018,donem:'bahar'} },
  { id:'ISL132-095', unite:4, konu:'Menkul Kıymetler', soru:'Aşağıdakilerden hangisi Menkul Kıymetler kapsamında değildir?', secenekler:{A:'Tahviller',B:'Hisse senetleri',C:'Finansman bonoları',D:'Hazine bonoları',E:'Alınan çekler'}, dogruCevap:'E', aciklama:'Doğru cevap E\'dir çünkü alınan çekler menkul kıymet değil, Alınan Çekler hesabında izlenen ticari alacak niteliğindedir. Tahvil, hisse senedi, finansman bonosu ve hazine bonosu menkul kıymet kapsamındadır.', kaynak:{tur:'donemsonu',yil:2018,donem:'bahar'} },
  { id:'ISL132-096', unite:7, konu:'Öz Kaynaklar', soru:'(ÖDENMEMİŞ SERMAYE HS. BORÇ 15.000 → SERMAYE HS. ALACAK 15.000) Bu yevmiye kaydı aşağıdaki işlemlerden hangisine aittir?', secenekler:{A:'Zararın sermayeden karşılanmasına',B:'Taahhüt edilen sermayenin ödenmesine',C:'Sermayenin azaltılmasına',D:'Sermaye taahhüdünde bulunulmasına',E:'Ödenmemiş sermayenin tahsiline'}, dogruCevap:'D', aciklama:'Doğru cevap D\'dir çünkü Ödenmemiş Sermaye borçlanıyor (alacak kapatılıyor) ve Sermaye alacaklanıyor → Bu yeni bir taahhüdü değil, mevcut taahhüdün kayda alınması anlamına gelir. Aslında bu kayıt sermaye taahhüdünde bulunma kaydıdır: Sermaye HS. ve Ödenmemiş Sermaye HS. karşılıklı oluşturulur.', kaynak:{tur:'donemsonu',yil:2018,donem:'bahar'} },
  { id:'ISL132-097', unite:6, konu:'Dönem Sonu İşlemleri', soru:'İşletmenin, döneme ilişkin vergi ve yasal yükümlülük karşılığı 13.000 TL, döneme ilişkin geçici vergi tutarı ise 7.000 TL\'dir. Bu bilgilere göre işletmenin vergi tahakkuk kaydı aşağıdakilerden hangisidir?', secenekler:{A:'370 BORÇ 13.000 → 371 ALACAK 13.000',B:'193 BORÇ 7.000 → 371 ALACAK 7.000',C:'370 BORÇ 13.000 → 193 ALACAK 6.000 / 360 ALACAK 7.000',D:'370 BORÇ 13.000 → 371 ALACAK 7.000 / 360 ALACAK 6.000',E:'371 BORÇ 7.000 / 360 BORÇ 6.000 → 370 ALACAK 13.000'}, dogruCevap:'C', aciklama:'Doğru cevap C\'dir çünkü vergi karşılığı 13.000: 370 HS. BORÇ 13.000. Peşin ödenen geçici vergi mahsup edilir: 193 HS. ALACAK 7.000. Kalan ödenecek vergi: 360 HS. ALACAK 6.000 (13.000-7.000).', kaynak:{tur:'donemsonu',yil:2018,donem:'bahar'} },
  { id:'ISL132-098', unite:7, konu:'Öz Kaynaklar', soru:'Aşağıdakilerden hangisi ödenmiş sermayeyi ifade etmektedir?', secenekler:{A:'İşletmenin ortaklarından olan sermaye alacağıdır.',B:'İşletmeye tahsis edilen sermaye tutarıdır.',C:'Ortakların işletmeye olan sermaye borcudur.',D:'İşletmeye henüz yatırılmamış olan sermaye tutarıdır.',E:'İşletmeye tahsis edilen sermayeden henüz ödenmemiş sermaye düşülerek bulunan tutardır.'}, dogruCevap:'E', aciklama:'Doğru cevap E\'dir çünkü ödenmiş sermaye = taahhüt edilen (tahsis edilen) sermaye - ödenmemiş sermaye. Ortakların fiilen ödediği kısımdır.', kaynak:{tur:'donemsonu',yil:2018,donem:'bahar'} },
  { id:'ISL132-099', unite:5, konu:'Kâr ve Vergi', soru:'Gelir tablosunda muhasebe ilkeleri, muhasebe standartları ve TTK hükümlerine göre hesaplanan kâr, ------- olarak adlandırılır.', secenekler:{A:'Düzeltme kârı',B:'Vergi kârı',C:'Sayım kârı',D:'Mali kâr',E:'Ticari kâr'}, dogruCevap:'E', aciklama:'Doğru cevap E\'dir çünkü muhasebe ilkeleri ve standartlara göre gelir tablosunda hesaplanan kâr ticari kârdır. Vergi kârı ise VUK hükümleri çerçevesinde hesaplanan kârdır.', kaynak:{tur:'donemsonu',yil:2018,donem:'bahar'} },
  { id:'ISL132-100', unite:4, konu:'Banka Kredileri', soru:'Bankaların sağladığı kredilerden, banka müşterisi olan işletme adına kendi saygınlığını ortaya koyarak işletmenin taahhüdünü yerine getireceği konusunda üçüncü kişilere güvence verdiği kredi türüne ne ad verilmektedir?', secenekler:{A:'Borçlu cari hesap',B:'Nakit olmayan krediler',C:'Nakit krediler',D:'Finansal kiralama',E:'Akreditif'}, dogruCevap:'E', aciklama:'Doğru cevap E\'dir çünkü akreditif, bankanın müşterisi adına üçüncü taraflara ödeme güvencesi verdiği bir kredi türüdür. Banka nakit vermez; taahhüdü yerine getirilmezse ödemeyi üstlenir.', kaynak:{tur:'donemsonu',yil:2018,donem:'bahar'} },
];

const mevcutIdler = new Set(data.map(s => s.id));
const eklenecek = yeni.filter(s => !mevcutIdler.has(s.id));

eklenecek.forEach(s => {
  s.dersKodu = 'İŞL132U';
  s.dersAdi = 'Finansal Muhasebe';
  s.soruTipi = 'çıkmış_soru';
  s.guvenDurumu = 'kontrol_edildi';
  s.kontrolEden = 'gorsel_okuma';
  s.nedenDigerleriDegil = s.nedenDigerleriDegil || '';
  s.ogretimNotu = s.ogretimNotu || '';
});

const yeniData = [...data, ...eklenecek];
fs.writeFileSync(dataPath, JSON.stringify(yeniData, null, 2), 'utf8');

const isl = yeniData.filter(s => s.dersKodu === 'İŞL132U');
console.log(`✓ Toplam ${yeniData.length} soru. İŞL132U: ${isl.length} soru (${isl.filter(s=>s.guvenDurumu==='kontrol_edildi').length} kontrol_edildi)`);
