const fs = require('fs');
const path = require('path');
const dataPath = path.join(__dirname, '../src/data/questions.json');
const data = JSON.parse(fs.readFileSync(dataPath, 'utf8'));

const yeni = [
  // 2018 dönemsonu
  { id:'IKT104-021', unite:4, konu:'Yatırım', soru:'Aşağıdakilerden hangisi bir yatırımın maliyetini ifade eder?', secenekler:{A:'Kiralar + vergiler',B:'Sermaye mallarının maliyeti + vergiler',C:'Finansal sermayenin maliyeti + reel maliyet',D:'Finansal sermayenin maliyeti + vergiler',E:'Sermaye mallarının maliyeti + finansal sermayenin maliyeti'}, dogruCevap:'E', aciklama:'Doğru cevap E\'dir çünkü yatırımın maliyeti hem sermaye mallarını (makine, teçhizat gibi reel varlıklar) satın almak için ödenen bedeli hem de bu yatırımı finanse etmek için katlanılan finansal sermaye maliyetini kapsar.', kaynak:{tur:'donemsonu',yil:2018,donem:'bahar'} },
  { id:'IKT104-022', unite:6, konu:'Enflasyon ve İşsizlik', soru:'Aşağıdakilerden hangisi enflasyon ve işsizlik arasındaki kısa dönemdeki ilişkiyi gösterir?', secenekler:{A:'Say Yasası',B:'Gresham Yasası',C:'Phillips Eğrisi',D:'Engel Eğrisi',E:'Lorenz Eğrisi'}, dogruCevap:'C', aciklama:'Doğru cevap C\'dir çünkü Phillips Eğrisi, kısa dönemde enflasyon ile işsizlik arasındaki ters yönlü ilişkiyi gösterir: enflasyon artarken işsizlik düşer, enflasyon düşerken işsizlik artar.', kaynak:{tur:'donemsonu',yil:2018,donem:'bahar'} },
  { id:'IKT104-023', unite:3, konu:'Üretim Fonksiyonu', soru:'Veri teknoloji altında, iş gücü ve sermayenin bir araya gelerek hasılatı üretmesini gösteren matematiksel ilişkiye ne ad verilir?', secenekler:{A:'Üretim esnekliği',B:'Verimlilik katsayısı',C:'Teknoloji katsayısı',D:'Üretim fonksiyonu',E:'Arz esnekliği'}, dogruCevap:'D', aciklama:'Doğru cevap D\'dir çünkü üretim fonksiyonu, belirli bir teknoloji düzeyinde emek ve sermaye girdilerinin çıktıya nasıl dönüştüğünü matematiksel olarak ifade eden ilişkidir: Q = f(K, L).', kaynak:{tur:'donemsonu',yil:2018,donem:'bahar'} },
  { id:'IKT104-024', unite:2, konu:'Milli Gelir', soru:'Bir ekonomide ne kadar üretim gerçekleştirildiğinin en önemli göstergesi aşağıdakilerden hangisidir?', secenekler:{A:'Gayri safi yurtiçi hasıla',B:'Katma değer',C:'İnsani gelişme indeksi',D:'Satın alma gücü paritesi',E:'Net faktör gelirleri'}, dogruCevap:'A', aciklama:'Doğru cevap A\'dır çünkü Gayri Safi Yurtiçi Hasıla (GSYH), bir ekonomide belirli bir dönemde üretilen tüm nihai mal ve hizmetlerin piyasa değeridir ve üretim düzeyinin en yaygın kullanılan göstergesidir.', kaynak:{tur:'donemsonu',yil:2018,donem:'bahar'} },
  { id:'IKT104-025', unite:5, konu:'Para Piyasası', soru:'Para piyasasında denge koşulu aşağıdakilerden hangisidir?', secenekler:{A:'Varlık arzının para arzına eşit olması',B:'Varlık arzının varlık talebine eşit olması',C:'Toplam kamu gelirlerinin toplam kamu harcamalarına eşit olması',D:'Para arzının piyasadaki mal miktarına eşit olması',E:'Varlık arzının kamu gelirlerine eşit olması'}, dogruCevap:'B', aciklama:'Doğru cevap B\'dir çünkü para piyasasında denge, para arzı (varlık arzı) para talebine (varlık talebine) eşit olduğunda gerçekleşir. Walras Yasası gereği varlık piyasasının dengede olması para piyasasının da dengede olması anlamına gelir.', kaynak:{tur:'donemsonu',yil:2018,donem:'bahar'} },
  { id:'IKT104-026', unite:4, konu:'Maliye Politikası / Çarpanlar', soru:'Kamunun yer aldığı dışa kapalı bir ekonomide marjinal tüketim eğilimi 0,6 ise vergi çarpanı kaçtır?', secenekler:{A:'-1',B:'-1,5',C:'-2',D:'-2,5',E:'-3'}, dogruCevap:'B', aciklama:'Doğru cevap B\'dir çünkü vergi çarpanı = -MTC/(1-MTC) = -0,6/(1-0,6) = -0,6/0,4 = -1,5. Vergideki artış geliri ve dolayısıyla tüketimi azaltır; bu nedenle çarpan negatiftir.', kaynak:{tur:'donemsonu',yil:2018,donem:'bahar'} },
  { id:'IKT104-027', unite:4, konu:'Toplam Harcamalar', soru:'Aşağıdakilerden hangisi kamunun yer aldığı dışa kapalı bir ekonomideki toplam harcamaları ifade eder?', secenekler:{A:'AE = Y – S + C',B:'AE = Y + C + I',C:'AE = C + S + I',D:'AE = I + S / C',E:'AE = C + I + G'}, dogruCevap:'E', aciklama:'Doğru cevap E\'dir çünkü kapalı ekonomide kamu sektörü varken toplam harcamalar (AE) = Tüketim (C) + Yatırım (I) + Kamu Harcamaları (G). İhracat-ithalat dışa kapalı olduğundan dahil edilmez.', kaynak:{tur:'donemsonu',yil:2018,donem:'bahar'} },
  { id:'IKT104-028', unite:7, konu:'Makroekonomik Sorunlar', soru:'İkiz açığın tanımı aşağıdakilerden hangisidir?', secenekler:{A:'Vergi açığı ve enflasyonun birlikte görülmesidir.',B:'Bütçe açığı ve dış ticaret açığının birlikte görülmesidir.',C:'Bütçe açığı ve işsizliğin birlikte görülmesidir.',D:'Kamu kesimi ve özel kesimin birlikte açık vermesidir.',E:'Bütçe açığı ve talep açığının birlikte görülmesidir.'}, dogruCevap:'B', aciklama:'Doğru cevap B\'dir çünkü ikiz açık (twin deficit), hem bütçe açığı hem de dış ticaret (cari işlemler) açığının eş anlı olarak yaşandığı ekonomik durumu tanımlar.', kaynak:{tur:'donemsonu',yil:2018,donem:'bahar'} },
  { id:'IKT104-029', unite:5, konu:'Para Talebi', soru:'Aşağıdakilerden hangisi para talebini etkileyen unsurlardan biri değildir?', secenekler:{A:'Reel faiz oranındaki değişmeler',B:'Fiyatlar genel düzeyindeki değişmeler',C:'Beklenen enflasyondaki değişmeler',D:'Reel gelirdeki değişmeler',E:'Arbitraj oranındaki değişmeler'}, dogruCevap:'E', aciklama:'Doğru cevap E\'dir çünkü para talebini; faiz oranları, fiyat düzeyi, reel gelir ve beklenen enflasyon gibi faktörler etkiler. Arbitraj oranı döviz piyasalarıyla ilgilidir ve doğrudan para talebini etkilemez.', kaynak:{tur:'donemsonu',yil:2018,donem:'bahar'} },
  { id:'IKT104-030', unite:5, konu:'Para ve Likidite', soru:'Parasal olmayan bir varlığın, ödemelerde kullanılacak bir nakit aracına dönüştürülmesindeki göreceli hız ve kolaylığa ne ad verilir?', secenekler:{A:'Arbitraj',B:'Marjinalite',C:'Hedging',D:'Likidite',E:'Swap'}, dogruCevap:'D', aciklama:'Doğru cevap D\'dir çünkü likidite, bir varlığın değer kaybetmeden ve hızlıca nakde çevrilme kolaylığını ifade eder. En likit varlık paradır.', kaynak:{tur:'donemsonu',yil:2018,donem:'bahar'} },
  { id:'IKT104-031', unite:5, konu:'Para Türleri', soru:'Para olarak tedavülde olan varlık, para olarak değerini tamamen kanuni bir zorunluluktan alıyorsa ve para olmak dışında herhangi bir ticari değeri yoksa, bu paraya ne ad verilir?', secenekler:{A:'Pahalı para',B:'Swap',C:'Fiyat para',D:'Mal para',E:'Hedging'}, dogruCevap:'C', aciklama:'Doğru cevap C\'dir çünkü fiyat para (fiat money), değerini yasal zorunluluktan alan, kendi başına ticari değeri olmayan paradır. Kağıt banknotlar bunun örneğidir; altın veya gümüş içermezler.', kaynak:{tur:'donemsonu',yil:2018,donem:'bahar'} },
  { id:'IKT104-032', unite:4, konu:'Maliye Politikası / Çarpanlar', soru:'Toplam gelir düzeyindeki değişimin kamu harcamalarındaki değişime oranının 1\'e eşit olmasına ne ad verilir?', secenekler:{A:'Denk bütçe çarpanı',B:'Minimum çarpan',C:'Ortalama çarpan',D:'Optimum çarpan',E:'Marjinal bütçe çarpanı'}, dogruCevap:'A', aciklama:'Doğru cevap A\'dır çünkü denk bütçe çarpanı teoremi, kamu harcaması ve vergi aynı miktarda artırıldığında (dengeli bütçe), milli gelirin harcama artışı kadar (çarpan=1) arttığını ifade eder.', kaynak:{tur:'donemsonu',yil:2018,donem:'bahar'} },
  { id:'IKT104-033', unite:3, konu:'Toplam Arz', soru:'Toplam arzı belirleyen temel faktörler aşağıdakilerden hangisinde birlikte ve doğru olarak verilmiştir?', secenekler:{A:'Pazarlama koşulları, teknoloji ve zevkler-tercihler',B:'Talebin gelir esnekliği ve kaynak fiyatları',C:'Kaynak fiyatları, teknoloji ve beklentiler',D:'Talebin gelir esnekliği ve beklentiler',E:'Talebin gelir esnekliği, kaynak fiyatları ve beklentiler'}, dogruCevap:'C', aciklama:'Doğru cevap C\'dir çünkü toplam arzı belirleyen temel faktörler; üretimde kullanılan kaynak fiyatları, teknolojik gelişmeler ve gelecek dönemle ilgili beklentilerdir.', kaynak:{tur:'donemsonu',yil:2018,donem:'bahar'} },
  { id:'IKT104-034', unite:2, konu:'Toplam Talep', soru:'Toplam talebin tanımı aşağıdakilerden hangisidir?', secenekler:{A:'İnsanların ellerinde tuttukları servetleridir.',B:'Belirli bir zaman dönemi boyunca ekonomideki tüm nihai mal ve hizmetlere yapılan harcamaların toplamıdır.',C:'Mal ve hizmetlerin toplam fiyatlarının toplam vergi gelirine oranıdır.',D:'Belirli bir zaman döneminde ekonomideki kira gelirlerinin toplamıdır.',E:'Belirli bir zaman döneminde ekonomide ithalat için yapılan ödemelerin toplamıdır.'}, dogruCevap:'B', aciklama:'Doğru cevap B\'dir çünkü toplam talep, bir ekonomide belirli bir dönem içinde tüketim, yatırım, kamu harcamaları ve net ihracat olarak yapılan tüm harcamaların toplamıdır.', kaynak:{tur:'donemsonu',yil:2018,donem:'bahar'} },
  { id:'IKT104-035', unite:1, konu:'İktisadi Düşünce Tarihi', soru:'"Genel Teori" adlı eseriyle pratik ekonomi politikasına yeni makro yaklaşımlar kazandıran ve ekonomik sistemin kendi başına bırakıldığında iyi işlemediğini savunan iktisatçı aşağıdakilerden hangisidir?', secenekler:{A:'Singer',B:'Linder',C:'Friedman',D:'Keynes',E:'Vernon'}, dogruCevap:'D', aciklama:'Doğru cevap D\'dir çünkü John Maynard Keynes, 1936\'da yayımladığı "Genel Teori" adlı eseriyle devlet müdahalesini savunmuş ve piyasaların kendi kendine tam istihdama ulaşamayacağını ileri sürmüştür.', kaynak:{tur:'donemsonu',yil:2018,donem:'bahar'} },
  { id:'IKT104-036', unite:3, konu:'Toplam Arz', soru:'Yukarıdakilerden hangileri, kısa dönemde toplam arz eğrisinde kaymaya neden olan faktörler arasında yer almaz? (I. Emek dışı girdi fiyatları  II. Arz şokları  III. Talep şokları  IV. Ücret oranları)', secenekler:{A:'Yalnız III',B:'Yalnız IV',C:'I ve II',D:'II ve III',E:'I, II ve IV'}, dogruCevap:'A', aciklama:'Doğru cevap A\'dır çünkü talep şokları toplam talep eğrisini kaydırır, toplam arz eğrisini değil. Girdi fiyatları, arz şokları ve ücret oranları toplam arzdaki kaymaların temel nedenleridir.', kaynak:{tur:'donemsonu',yil:2018,donem:'bahar'} },
  { id:'IKT104-037', unite:6, konu:'Stagflasyon', soru:'Hem ekonomik daralma hem de enflasyonun eş anlı olarak ortaya çıkmasına ne ad verilir?', secenekler:{A:'Optimizasyon',B:'Devalüasyon',C:'Stagflasyon',D:'Deflasyon',E:'Revalüasyon'}, dogruCevap:'C', aciklama:'Doğru cevap C\'dir çünkü stagflasyon, durgunluk (stagnation) ve enflasyonun (inflation) birlikte yaşandığı durumu ifade eden birleşik bir kavramdır. 1970\'lerin petrol krizi bu durumun klasik örneğidir.', kaynak:{tur:'donemsonu',yil:2018,donem:'bahar'} },
  { id:'IKT104-038', unite:5, konu:'Para Politikası', soru:'Merkez bankalarının çeşitli nedenlerle ortaya çıkan para arzı artışını dengelemek için yaptıkları açık piyasa işlemine ne ad verilir?', secenekler:{A:'Sterilizasyon',B:'Hedging',C:'Kotasyon',D:'Arbitraj',E:'Forward işlemi'}, dogruCevap:'A', aciklama:'Doğru cevap A\'dır çünkü sterilizasyon, merkez bankasının döviz alımı gibi nedenlerle artan para arzını, piyasadan tahvil satarak dengelemesi işlemidir. Amaç para miktarını kontrol altında tutmaktır.', kaynak:{tur:'donemsonu',yil:2018,donem:'bahar'} },
  { id:'IKT104-039', unite:7, konu:'İstikrar Politikaları', soru:'Heteredoks istikrar programları, genellikle aşağıdaki durumlardan hangisinin yaşandığı ekonomilerde tercih edilir?', secenekler:{A:'Düşük ithalat bağımlılığı',B:'Tam istihdam',C:'Dış ödemeler fazlası',D:'Ekonomik büyüme',E:'Yüksek kronik enflasyon'}, dogruCevap:'E', aciklama:'Doğru cevap E\'dir çünkü heteredoks programlar, yüksek kronik enflasyonla mücadelede ücret ve fiyat kontrolleri gibi doğrudan müdahaleleri de içerir. Yüksek enflasyonlu ülkelerde (özellikle Latin Amerika) uygulanmıştır.', kaynak:{tur:'donemsonu',yil:2018,donem:'bahar'} },
  { id:'IKT104-040', unite:7, konu:'İstikrar Politikaları', soru:'Aşağıdakilerden hangisi IMF tipi istikrar politikalarının araçlarından biri değildir?', secenekler:{A:'Ücretlerin kontrolü',B:'Ticaretin serbestleştirilmesi',C:'Piyasa faiz oranlarının yükseltilmesi',D:'Paranın revalüasyonu',E:'Sıkı para politikası'}, dogruCevap:'A', aciklama:'Doğru cevap A\'dır çünkü ücret kontrolü heteredoks bir araçtır. IMF tipi (ortodoks) programlar; devalüasyon, faiz artışı, sıkı para politikası ve ticaret serbestleştirmesi gibi piyasa yanlısı araçlara dayanır.', kaynak:{tur:'donemsonu',yil:2018,donem:'bahar'} },

  // 2017 arasinav
  { id:'IKT104-041', unite:2, konu:'GSYH Hesaplama', soru:'GSYH\'nin hesaplamasında kullanılan yöntemler aşağıdakilerden hangisinde birlikte ve doğru olarak verilmiştir?', secenekler:{A:'Gelir, üretim, harcama',B:'Üretim, tüketim',C:'Gelir, üretim, ithalat',D:'Gelir, tasarruf',E:'Tasarruf, yatırım'}, dogruCevap:'A', aciklama:'Doğru cevap A\'dır çünkü GSYH üç temel yöntemle hesaplanır: Gelir yöntemi (faktör ödemeleri toplamı), Üretim yöntemi (katma değerler toplamı) ve Harcama yöntemi (C+I+G+NX).\n', kaynak:{tur:'arasinav',yil:2017,donem:'güz'} },
  { id:'IKT104-042', unite:2, konu:'Nominal ve Reel GSYH', soru:'Cari fiyatlarla GSYH aşağıdakilerden hangisini ifade eder?', secenekler:{A:'Fiziki GSYH',B:'Etken GSYH',C:'Esnek GSYH',D:'Nominal GSYH',E:'Reel GSYH'}, dogruCevap:'D', aciklama:'Doğru cevap D\'dir çünkü cari fiyatlarla (yani o dönemin fiyatlarıyla) hesaplanan GSYH, Nominal GSYH\'dir. Reel GSYH ise baz yıl fiyatlarıyla hesaplanarak enflasyonun etkisi arındırılmış GSYH\'dir.', kaynak:{tur:'arasinav',yil:2017,donem:'güz'} },
  { id:'IKT104-043', unite:2, konu:'Kalkınma Göstergeleri', soru:'Birleşmiş Milletler Kalkınma Programı tarafından geliştirilen; gelir, eğitim ve sağlıklı yaşam sürelerini hesaba katarak ülkeleri insani gelişme düzeyine göre sıralayan endeks aşağıdakilerden hangisidir?', secenekler:{A:'Mutlak Yoksulluk Endeksi',B:'Satın Alma Gücü Endeksi',C:'İnsani Gelişme Endeksi',D:'Kalkınmışlık Endeksi',E:'Toplam Tüketici Endeksi'}, dogruCevap:'C', aciklama:'Doğru cevap C\'dir çünkü UNDP tarafından geliştirilen İnsani Gelişme Endeksi (İGE/HDI), gelir (GSYH/kişi), eğitim (okur-yazarlık, okul yılı) ve sağlık (yaşam beklentisi) boyutlarını birleştirir.', kaynak:{tur:'arasinav',yil:2017,donem:'güz'} },
  { id:'IKT104-044', unite:2, konu:'Gelir-Harcama Eşitliği', soru:'Ekonomide gelir harcama eşitliğinin sağlanmasının koşulu aşağıdakilerden hangisidir?', secenekler:{A:'Gelirlerin reel olması',B:'Elde edilen gelirin tasarrufa ayrılması',C:'Cari işlemler açığının artması',D:'Elde edilen gelirin tamamının harcanması',E:'Dış ticaretin kısıtlanması'}, dogruCevap:'D', aciklama:'Doğru cevap D\'dir çünkü kapalı ekonomide Y = C + S, AE = C + I. Gelir = Harcama için S = I olmalı ya da elde edilen gelirin tamamı harcanmalıdır (tasarruf sıfır olduğunda Y = C = AE).', kaynak:{tur:'arasinav',yil:2017,donem:'güz'} },
  { id:'IKT104-045', unite:6, konu:'Phillips Eğrisi', soru:'Aşağıdakilerden hangisi enflasyon ve işsizlik arasındaki kısa dönemdeki ilişkiyi gösterir?', secenekler:{A:'Gresham Yasası',B:'Phillips Eğrisi',C:'Say Yasası',D:'Lorenz Eğrisi',E:'Engel Eğrisi'}, dogruCevap:'B', aciklama:'Doğru cevap B\'dir çünkü Phillips Eğrisi, kısa dönemde enflasyon ile işsizlik arasındaki ters yönlü ilişkiyi gösterir. A.W. Phillips bu ilişkiyi İngiltere verileriyle ampirik olarak ortaya koymuştur.', kaynak:{tur:'arasinav',yil:2017,donem:'güz'} },
  { id:'IKT104-046', unite:5, konu:'Finansal Sistem', soru:'Aşağıdaki sektörlerden hangisi, ekonomide birikimlerin reel yatırımlara dönüştürülmesinde önemli bir rol oynar?', secenekler:{A:'İnşaat sektörü',B:'Finansal sektör',C:'Hizmet sektörü',D:'Madencilik sektörü',E:'Tarım sektörü'}, dogruCevap:'B', aciklama:'Doğru cevap B\'dir çünkü finansal sektör (bankalar, borsalar, sigorta şirketleri), tasarrufları toplayarak yatırımlara yönlendiren aracı kurumları kapsar; ekonomide fon aktarım mekanizmasının temelini oluşturur.', kaynak:{tur:'arasinav',yil:2017,donem:'güz'} },
  { id:'IKT104-047', unite:2, konu:'Katma Değer', soru:'Bir malın piyasa değeri ile bu malın üretim sürecinde kullanılan girdilerin değeri arasındaki farka ne ad verilir?', secenekler:{A:'Katma değer',B:'Ara malı',C:'Nihai mal',D:'Milli gelir',E:'Fiyat'}, dogruCevap:'A', aciklama:'Doğru cevap A\'dır çünkü katma değer = üretilen çıktının değeri - üretimde kullanılan ara girdilerin değeri. GSYH hesaplamasında çifte saymayı önlemek için katma değer yöntemi kullanılır.', kaynak:{tur:'arasinav',yil:2017,donem:'güz'} },
  { id:'IKT104-048', unite:1, konu:'İktisadi Düşünce Tarihi', soru:'Keynes\'in görüşleri hangi yıllarda artan bir şekilde taraftar bulmaya başlamıştır?', secenekler:{A:"1910'lu",B:"1930'lu",C:"1950'li",D:"1960'lı",E:"1980'li"}, dogruCevap:'B', aciklama:'Doğru cevap B\'dir çünkü Keynes\'in görüşleri, 1929 Büyük Buhranı\'nın yarattığı kitlesel işsizlik ortamında (1930\'larda) devlet müdahalesini meşrulaştırdığı için hızla taraftar buldu.', kaynak:{tur:'arasinav',yil:2017,donem:'güz'} },
  { id:'IKT104-049', unite:2, konu:'GSYH Deflatörü', soru:'GSYH deflatörünün tanımı aşağıdakilerden hangisidir?', secenekler:{A:'Reel GSYH\'nın bütçe açığına oranıdır.',B:'Reel GSYH\'nın vergi gelirlerine oranıdır.',C:'Nominal GSYH\'nın reel GSYH\'ya oranıdır.',D:'Reel GSYH\'nın nominal GSYH\'ya oranıdır.',E:'Nominal GSYH\'nın dış alem gelirlerine oranıdır.'}, dogruCevap:'C', aciklama:'Doğru cevap C\'dir çünkü GSYH deflatörü = (Nominal GSYH / Reel GSYH) × 100. Bu oran, genel fiyat düzeyini ölçer ve enflasyonun reel büyüme üzerindeki etkisini arındırmak için kullanılır.', kaynak:{tur:'arasinav',yil:2017,donem:'güz'} },
  { id:'IKT104-050', unite:2, konu:'Milli Gelir Kavramları', soru:'Faktör fiyatlarıyla safi milli hasıla aşağıdakilerden hangisine eşittir?', secenekler:{A:'Bütçe açığı',B:'Milli gelir',C:'Gayri safi yurtiçi hasıla',D:'Safi yurtiçi hasıla',E:'Gayri safi milli hasıla'}, dogruCevap:'B', aciklama:'Doğru cevap B\'dir çünkü faktör fiyatlarıyla safi milli hasıla = Milli Gelir\'dir. GSMH - Amortisman = Safi Milli Hasıla (piyasa fiyatlarıyla). Buradan sübvansiyonlar çıkarılıp dolaylı vergiler eklenirse faktör fiyatlarıyla SMH = Milli Gelir elde edilir.', kaynak:{tur:'arasinav',yil:2017,donem:'güz'} },
  { id:'IKT104-051', unite:6, konu:'İşsizlik', soru:'Okun yasası aşağıdakilerden hangisini ölçen bir katsayıdır?', secenekler:{A:'Verimlilik artışını',B:'Vergi esnekliğini',C:'Cari işlemler açığını',D:'Gerçekleşen hasıla kazancını',E:'Potansiyel hasıla kaybını'}, dogruCevap:'E', aciklama:'Doğru cevap E\'dir çünkü Okun Yasası, işsizlik oranının doğal işsizlik oranının üzerine çıktığında potansiyel GSYH\'dan ne kadar sapma olduğunu ölçer: her 1 puanlık işsizlik artışı potansiyel hasılada yaklaşık %2\'lik kayıp demektir.', kaynak:{tur:'arasinav',yil:2017,donem:'güz'} },
  { id:'IKT104-052', unite:3, konu:'Üretim Faktörleri', soru:'Firmanın istihdam ettiği son işçinin firmanın toplam maliyetinde yaptığı değişime ne ad verilir?', secenekler:{A:'Toplam ürün maliyeti',B:'Marjinal ürün hasılası',C:'Ortalama faktör maliyeti',D:'Marjinal faktör maliyeti',E:'Marjinal sabit maliyet'}, dogruCevap:'D', aciklama:'Doğru cevap D\'dir çünkü marjinal faktör maliyeti (MFC), bir birim daha fazla emek kullanmanın toplam maliyeti ne kadar artırdığını gösterir. Rekabetçi emek piyasasında MFC = ücret oranına eşittir.', kaynak:{tur:'arasinav',yil:2017,donem:'güz'} },
  { id:'IKT104-053', unite:1, konu:'Kalkınma Ekonomisi', soru:'Aşağıdakilerden hangisi gelişmekte olan ülkelerde sermaye birikiminin yavaş artmasına neden olur?', secenekler:{A:'Etken korumanın düşüklüğü',B:'Dışa kapalı olmaları',C:'Cari işlemler fazlası',D:'Tasarruf oranının düşüklüğü',E:'Senyoraj oranının yüksekliği'}, dogruCevap:'D', aciklama:'Doğru cevap D\'dir çünkü tasarruf oranı düşük olan ülkelerde yatırıma aktarılacak fon miktarı da azdır. Sermaye birikimi = yatırım = tasarruf (kapalı ekonomide), dolayısıyla düşük tasarruf düşük sermaye birikimi demektir.', kaynak:{tur:'arasinav',yil:2017,donem:'güz'} },
  { id:'IKT104-054', unite:2, konu:'Milli Gelir Kavramları', soru:'Net vergi hasılatının tanımı aşağıdakilerden hangisidir?', secenekler:{A:'Devletin topladığı vergilere, dış yardımlar eklendiğinde ulaşılan tutardır.',B:'Devletin topladığı vergilerden, hanehalklarına yaptığı transfer ödemeleri çıkarıldıktan sonra kalan kısımdır.',C:'Devletin topladığı vergilere, vergi cezaları eklendiğinde ulaşılan tutardır.',D:'Toplam kamu gelirlerine, özel tasarruflar eklendiğinde ulaşılan tutardır.',E:'Toplam kamu gelirlerine, bütçe fazlası eklendiğinde ulaşılan tutardır.'}, dogruCevap:'B', aciklama:'Doğru cevap B\'dir çünkü net vergi hasılatı (T) = Toplam vergi gelirleri - Transfer ödemeleri. Transfer ödemeleri (emekli maaşı, işsizlik yardımı vb.) gerçek bir üretim karşılığı olmadığından brüt vergiden düşülür.', kaynak:{tur:'arasinav',yil:2017,donem:'güz'} },
  { id:'IKT104-055', unite:3, konu:'Üretim Teknolojisi', soru:'Aşağıdakilerden hangisi mal ve hizmet üretiminde, üretim faktörlerinin bir araya nasıl getirileceğine dair bilgileri kapsar?', secenekler:{A:'Teknoloji',B:'Girdi çıktı bileşimi',C:'Etkin seçim',D:'Optimizasyon',E:'Doğru bileşim'}, dogruCevap:'A', aciklama:'Doğru cevap A\'dır çünkü teknoloji, belirli miktarda çıktı üretmek için emek, sermaye ve doğal kaynakların nasıl bir araya getirileceğine ilişkin bilgi birikimini ifade eder.', kaynak:{tur:'arasinav',yil:2017,donem:'güz'} },
  { id:'IKT104-056', unite:4, konu:'Tüketim Fonksiyonu', soru:'Keynesyen tüketim fonksiyonunda toplam tüketim harcamaları aşağıdakilerden hangisine bağlıdır?', secenekler:{A:'Cari dönemdeki dış ticaret açığına',B:'Cari dönemdeki senyoraj oranına',C:'Cari dönemdeki toplam harcanabilir gelire',D:'Cari dönemin toplam istihdam oranına',E:'Cari dönemdeki dış borç miktarına'}, dogruCevap:'C', aciklama:'Doğru cevap C\'dir çünkü Keynes\'e göre tüketim (C) = a + bYd şeklinde ifade edilir; burada Yd harcanabilir gelir, b marjinal tüketim eğilimidir. Tüketimi belirleyen temel faktör cari dönemdeki harcanabilir gelirdir.', kaynak:{tur:'arasinav',yil:2017,donem:'güz'} },
  { id:'IKT104-057', unite:4, konu:'Tasarruf', soru:'Özel tasarrufların tanımı aşağıdakilerden hangisidir?', secenekler:{A:'Şahıslar adına devlet tarafından biriktirilen paralardır.',B:'Özel kurumların reel birikimidir.',C:'Özellik taşıyan tasarruflardır.',D:'Özel kişilerin otonom harcamalarıdır.',E:'Gelirin hanehalkları tarafından tüketilmeyen kısmıdır.'}, dogruCevap:'E', aciklama:'Doğru cevap E\'dir çünkü özel tasarruf = Harcanabilir gelir - Tüketim = Yd - C. Yani gelirin harcandıktan sonra arta kalan (tüketilmeyen) kısmıdır.', kaynak:{tur:'arasinav',yil:2017,donem:'güz'} },
  { id:'IKT104-058', unite:5, konu:'Faiz Oranları', soru:'Aşağıdakilerden hangisi reel faiz oranını ifade eder?', secenekler:{A:'Faiz oranı + vade uzunluğu',B:'Nominal faiz oranı + vergi oranı',C:'Faiz oranı + para miktarı',D:'Nominal faiz oranı - vergi oranı',E:'Nominal faiz oranı - enflasyon oranı'}, dogruCevap:'E', aciklama:'Doğru cevap E\'dir çünkü Fisher denklemi: Reel faiz oranı = Nominal faiz oranı - Enflasyon oranı. Reel faiz, paranın satın alma gücündeki gerçek getiriyi yansıtır.', kaynak:{tur:'arasinav',yil:2017,donem:'güz'} },
  { id:'IKT104-059', unite:3, konu:'Üretim Fonksiyonu', soru:'Veri teknoloji altında, işgücü ve sermayenin bir araya gelerek hasılatı üretmesini gösteren matematiksel ilişkiye ne ad verilir?', secenekler:{A:'Üretim fonksiyonu',B:'Arz esnekliği',C:'Üretim esnekliği',D:'Verimlilik katsayısı',E:'Teknoloji katsayısı'}, dogruCevap:'A', aciklama:'Doğru cevap A\'dır çünkü üretim fonksiyonu Q = f(K, L), belirli bir teknoloji düzeyi altında sermaye (K) ve emek (L) girdilerinin çıktıya (Q) nasıl dönüştüğünü matematiksel olarak gösterir.', kaynak:{tur:'arasinav',yil:2017,donem:'güz'} },
  { id:'IKT104-060', unite:4, konu:'Yatırım', soru:'Net yatırımlar kavramı aşağıdakilerden hangisini ifade eder?', secenekler:{A:'Özel sektör yatırımlarını',B:'Kârlı yatırımları',C:'Yatırımcıların ödediği vergileri',D:'Görünen yatırımları',E:'Sermaye stokunda bir dönemden diğerine gerçekleşen artışı'}, dogruCevap:'E', aciklama:'Doğru cevap E\'dir çünkü net yatırım = Brüt yatırım - Amortisman. Net yatırım, sermaye stokundaki net artışı gösterir; amortismanın (eskiyen sermayenin değeri) üzerindeki yeni yatırım miktarıdır.', kaynak:{tur:'arasinav',yil:2017,donem:'güz'} },

  // 2017 dönemsonu
  { id:'IKT104-061', unite:5, konu:'Faiz Oranları', soru:'Nominal faiz oranından, mal ve hizmetlerin fiyatlarındaki artış oranı çıkarıldıktan sonra elde edilen faiz oranına ne ad verilir?', secenekler:{A:'Brüt faiz oranı',B:'Toplam faiz oranı',C:'Reel faiz oranı',D:'Optimum faiz oranı',E:'Arbitraj faiz oranı'}, dogruCevap:'C', aciklama:'Doğru cevap C\'dir çünkü Fisher denklemi: Reel faiz = Nominal faiz - Enflasyon. Reel faiz oranı, enflasyonun satın alma gücü üzerindeki etkisi arındırıldıktan sonra kalan gerçek getiriyi gösterir.', kaynak:{tur:'donemsonu',yil:2017,donem:'bahar'} },
  { id:'IKT104-062', unite:1, konu:'İktisadın Doğuşu', soru:'İktisadın sosyal bir bilim olarak ortaya çıkışı kaçıncı yüzyılda olmuştur?', secenekler:{A:'18.',B:'17.',C:'16.',D:'15.',E:'14.'}, dogruCevap:'A', aciklama:'Doğru cevap A\'dır çünkü iktisat, 18. yüzyılda Adam Smith\'in 1776\'da yayımladığı "Milletlerin Zenginliği" eseriyle bağımsız bir bilim dalı olarak kabul görmüştür.', kaynak:{tur:'donemsonu',yil:2017,donem:'bahar'} },
  { id:'IKT104-063', unite:6, konu:'İşsizlik / Okun Yasası', soru:'Doğal işsizlik oranı ile cari işsizlik oranı arasındaki fark nedeniyle potansiyel hasıladaki kaybı ölçen katsayıya ne ad verilir?', secenekler:{A:'Pareto Optimumu',B:'Say Yasası',C:'Gresham Yasası',D:'Leontief Paradoksu',E:'Okun Yasası'}, dogruCevap:'E', aciklama:'Doğru cevap E\'dir çünkü Okun Yasası, gerçekleşen işsizlik ile doğal işsizlik oranı arasındaki farkın GSYH üzerindeki etkisini ölçer. Her 1 puanlık fazla işsizlik potansiyel hasılada yaklaşık %2 kayba yol açar.', kaynak:{tur:'donemsonu',yil:2017,donem:'bahar'} },
  { id:'IKT104-064', unite:2, konu:'GSYH Tanımı', soru:'Bir ekonomide belirli bir dönemde üretilen tamamlanmış mal ve hizmetlerin piyasa değerine ne ad verilir?', secenekler:{A:'Safi milli hasıla',B:'Gayri safi yurtiçi hasıla',C:'Milli gelir',D:'Arbitraj geliri',E:'Harcanabilir gelir'}, dogruCevap:'B', aciklama:'Doğru cevap B\'dir çünkü Gayri Safi Yurtiçi Hasıla (GSYH), belirli bir dönemde ülke sınırları içinde üretilen tüm nihai mal ve hizmetlerin piyasa değeridir. "Gayri safi" amortisman dahil olduğu anlamına gelir.', kaynak:{tur:'donemsonu',yil:2017,donem:'bahar'} },
  { id:'IKT104-065', unite:7, konu:'İkiz Açık', soru:'İkiz açığın tanımı aşağıdakilerden hangisidir?', secenekler:{A:'Bütçe açığı ve işsizliğin birlikte görülmesidir.',B:'Bütçe açığı ve talep açığının birlikte görülmesidir.',C:'Vergi açığı ve enflasyonun birlikte görülmesidir.',D:'Bütçe açığı ve dış ticaret açığının birlikte görülmesidir.',E:'Kamu kesimi ve özel kesimin birlikte açık vermesidir.'}, dogruCevap:'D', aciklama:'Doğru cevap D\'dir çünkü ikiz açık, hem bütçe açığı (kamu harcamaları > kamu gelirleri) hem de dış ticaret açığının (ithalat > ihracat) eş zamanlı yaşanmasıdır.', kaynak:{tur:'donemsonu',yil:2017,donem:'bahar'} },
  { id:'IKT104-066', unite:5, konu:'Para Çarpanı', soru:'Ticari bankaların her bir TL\'lik rezervden yaratmış olduğu para miktarına ne ad verilir?', secenekler:{A:'Para arbitrajı',B:'Para çarpanı',C:'Para marjı',D:'Rezerv esnekliği',E:'Senyoraj'}, dogruCevap:'B', aciklama:'Doğru cevap B\'dir çünkü para çarpanı = 1 / zorunlu rezerv oranı. Ticari bankalar kısmi rezerv sistemiyle her 1 TL rezervden daha fazla para yaratır. Örneğin %10 rezerv oranıyla para çarpanı 10\'dur.', kaynak:{tur:'donemsonu',yil:2017,donem:'bahar'} },
  { id:'IKT104-067', unite:5, konu:'Merkez Bankası Araçları', soru:'Reeskont faiz oranının tanımı aşağıdakilerden hangisidir?', secenekler:{A:'Diğer bankaların merkez bankasındaki mevduatlarıdır.',B:'Merkez bankasının sistem içindeki bankalara kredi açma durumunda uyguladığı faiz oranıdır.',C:'Merkez bankasının diğer bankalara koyduğu mevduat sınırıdır.',D:'El değiştiren bonoların iskonto oranıdır.',E:'Bankaların senet iskontosuna uyguladığı faiz oranıdır.'}, dogruCevap:'B', aciklama:'Doğru cevap B\'dir çünkü reeskont (iskonto) oranı, merkez bankasının ticari bankalara kredi açarken uyguladığı faiz oranıdır. Bu oran artarsa bankaların borçlanma maliyeti artar ve kredi hacmi daralır.', kaynak:{tur:'donemsonu',yil:2017,donem:'bahar'} },
  { id:'IKT104-068', unite:4, konu:'Çarpan Etkisi', soru:'Bir ekonomide reel toplam çıktının denge düzeyindeki değişiminin, dışsal değişkendeki değişime oranına ne ad verilir?', secenekler:{A:'Arbitraj',B:'Gelir etkisi',C:'Çarpan',D:'Marjinal değişim',E:'Hedging'}, dogruCevap:'C', aciklama:'Doğru cevap C\'dir çünkü çarpan (multiplier), özerk harcamalardaki bir değişikliğin toplam gelirde yarattığı toplam etkinin büyüklüğünü gösterir. Çarpan = 1/(1-MTC).', kaynak:{tur:'donemsonu',yil:2017,donem:'bahar'} },
  { id:'IKT104-069', unite:4, konu:'Kamu Harcamaları Çarpanı', soru:'Kamunun yer aldığı bir ekonomide marjinal tasarruf eğilimi 0,25 ise kamu harcamaları çarpanının değeri kaçtır?', secenekler:{A:'7',B:'6,5',C:'5',D:'4',E:'3,4'}, dogruCevap:'D', aciklama:'Doğru cevap D\'dir çünkü MTS = 0,25 → MTC = 1 - 0,25 = 0,75. Kamu harcamaları çarpanı = 1/(1-MTC) = 1/0,25 = 4.', kaynak:{tur:'donemsonu',yil:2017,donem:'bahar'} },
  { id:'IKT104-070', unite:5, konu:'Para Fonksiyonları', soru:'Paranın değişim aracı olarak kullanılmadığı bir ekonomide, mal ve hizmet değişimi için geçen zaman, emek ve çabaların toplamına ne ad verilir?', secenekler:{A:'İşlem maliyeti',B:'Arbitraj maliyeti',C:'Marjinal maliyet',D:'Fırsat maliyeti',E:'Ortalama maliyet'}, dogruCevap:'A', aciklama:'Doğru cevap A\'dır çünkü paranın değişim aracı olarak kullanılmadığı takas ekonomisinde alıcı ve satıcıyı eşleştirmek için harcanan zaman ve çaba işlem maliyetidir. Para bu maliyetleri büyük ölçüde azaltır.', kaynak:{tur:'donemsonu',yil:2017,donem:'bahar'} },
  { id:'IKT104-071', unite:7, konu:'Döviz Kuru Politikaları', soru:'Para yetkililerinin ya da hükümetin döviz fiyatını artırmasına ne ad verilir?', secenekler:{A:'Revalüasyon',B:'Devalüasyon',C:'Stagflasyon',D:'Konvertibilite',E:'Swap'}, dogruCevap:'B', aciklama:'Doğru cevap B\'dir çünkü devalüasyon, sabit kur sisteminde hükümetin yerli para biriminin değerini resmi olarak düşürmesi (döviz fiyatını artırması) işlemidir. Revalüasyon ise döviz fiyatını düşürür (yerli para güçlenir).', kaynak:{tur:'donemsonu',yil:2017,donem:'bahar'} },
  { id:'IKT104-072', unite:5, konu:'Banka Rezervleri', soru:'Atıl rezervlerin tanımı aşağıdakilerden hangisidir?', secenekler:{A:'Bankaların zorunlu rezervler dışında ellerinde tuttukları rezervlerdir.',B:'Şahısların ellerinde tuttukları rezervlerdir.',C:'Merkez bankasında boş duran rezervlerdir.',D:'Bankaların yurt dışındaki şubelerinde tuttukları rezervlerdir.',E:'Firmaların ellerinde tuttukları rezervlerdir.'}, dogruCevap:'A', aciklama:'Doğru cevap A\'dır çünkü atıl (fazla) rezervler, ticari bankaların merkez bankasının belirlediği zorunlu rezervlerin üzerinde tuttukları ek rezervlerdir. Bu rezervler kredi olarak kullandırılmayı bekler.', kaynak:{tur:'donemsonu',yil:2017,donem:'bahar'} },
  { id:'IKT104-073', unite:6, konu:'Tam İstihdam', soru:'Günümüzde emek gücü yüzde kaç oranında istihdam edildiğinde, ekonomide tam istihdamın gerçekleştiği kabul edilir?', secenekler:{A:'81',B:'85',C:'90',D:'94',E:'98'}, dogruCevap:'C', aciklama:'Doğru cevap C\'dir çünkü günümüzde ekonomistler, emek gücünün yaklaşık %90\'ının istihdam edildiği durumu (doğal işsizlik oranı ~%10) tam istihdam olarak kabul eder.', kaynak:{tur:'donemsonu',yil:2017,donem:'bahar'} },
  { id:'IKT104-074', unite:5, konu:'Senyoraj', soru:'Senyorajın tanımı aşağıdakilerden hangisidir?', secenekler:{A:'Merkez bankasının otonom olmasıdır.',B:'Devletin, merkez bankası üzerindeki otoritesidir.',C:'Devletin borçlarını ödeyemeyeceğini ilan etmesidir.',D:'Paranın üretim maliyeti ile üzerinde yazılı değer arasındaki farktır.',E:'Faiz oranlarında yaşanan beklenmedik düşüştür.'}, dogruCevap:'D', aciklama:'Doğru cevap D\'dir çünkü senyoraj, para basmanın getirisini ifade eder: banknotun üzerinde yazan değer ile basım maliyeti arasındaki fark. Devlet bu geliri para basarak elde eder.', kaynak:{tur:'donemsonu',yil:2017,donem:'bahar'} },
  { id:'IKT104-075', unite:3, konu:'Toplam Arz (Çok Kısa Dönem)', soru:'Çok kısa dönemde toplam arz eğrisinin şekli nasıldır?', secenekler:{A:'Başlangıçta diktir sonra yatay olur.',B:'Dirsekli eğridir.',C:'Başlangıçta yataydır sonra dikleşir.',D:'Tamamen diktir.',E:'Tamamen yataydır.'}, dogruCevap:'E', aciklama:'Doğru cevap E\'dir çünkü çok kısa dönemde (çok kısa vadede) fiyatlar katıdır (değişmez). Bu nedenle toplam arz eğrisi tamamen yatay bir görünüm alır; üretim talebe göre ayarlanırken fiyatlar sabit kalır.', kaynak:{tur:'donemsonu',yil:2017,donem:'bahar'} },
  { id:'IKT104-076', unite:7, konu:'İstikrar Politikaları', soru:'IMF Tipi İstikrar Programları\'nın uygulanmasını gerekli kılan en önemli neden aşağıdakilerden hangisidir?', secenekler:{A:'İşsizliğin artması',B:'Üretimin düşmesi',C:'Durgunluğun ortaya çıkması',D:'Enflasyonun artması',E:'Dış ödemeler dengesinde açıkların ortaya çıkması'}, dogruCevap:'E', aciklama:'Doğru cevap E\'dir çünkü IMF tipi programlar, özellikle dış ödeme güçlüğü (ödemeler dengesi krizleri) yaşayan ülkelere uygulanır. Krizin temel nedeni dış açıklar ve döviz rezervlerinin erimesidir.', kaynak:{tur:'donemsonu',yil:2017,donem:'bahar'} },
  { id:'IKT104-077', unite:3, konu:'Toplam Talep', soru:'Toplam talep eğrisinin eğimini etkileyen döviz kuru etkisi, aşağıdakilerden hangisi arasındaki ilişkiyi gösterir?', secenekler:{A:'Fiyat düzeyi ile net ihracat',B:'Döviz kuru ile ithalat',C:'Faiz oranı ile net ihracat',D:'Verimlilik ile net ihracat',E:'Para değeri ile talep'}, dogruCevap:'A', aciklama:'Doğru cevap A\'dır çünkü döviz kuru etkisinde: fiyat düzeyi artar → faiz artar → döviz değeri artar → ihracat azalır, ithalat artar → net ihracat azalır → toplam talep düşer. Bu fiyat-net ihracat ilişkisidir.', kaynak:{tur:'donemsonu',yil:2017,donem:'bahar'} },
  { id:'IKT104-078', unite:3, konu:'Toplam Arz Faktörleri', soru:'Toplam arzı belirleyen temel faktörler aşağıdakilerden hangisinde birlikte ve doğru olarak verilmiştir?', secenekler:{A:'Pazarlama koşulları, teknoloji ve zevkler-tercihler',B:'Talebin gelir esnekliği ve kaynak fiyatları',C:'Kaynak fiyatları, teknoloji ve beklentiler',D:'Talebin gelir esnekliği, kaynak fiyatları ve beklentiler',E:'Talebin gelir esnekliği ve beklentiler'}, dogruCevap:'C', aciklama:'Doğru cevap C\'dir çünkü toplam arz eğrisi; kaynak (girdi) fiyatları, teknoloji ve gelecek beklentileri tarafından belirlenir. Bu faktörlerdeki değişmeler toplam arz eğrisini sağa veya sola kaydırır.', kaynak:{tur:'donemsonu',yil:2017,donem:'bahar'} },
  { id:'IKT104-079', unite:5, konu:'Para Politikası', soru:'Merkez bankalarının çeşitli nedenlerle ortaya çıkan para arzı artışını dengelemek için yaptıkları açık piyasa işlemlerine ne ad verilir?', secenekler:{A:'Arbitraj',B:'Hedging',C:'Kotasyon',D:'Forward işlemi',E:'Sterilizasyon'}, dogruCevap:'E', aciklama:'Doğru cevap E\'dir çünkü sterilizasyon, merkez bankasının döviz alımı veya başka nedenlerle artan para arzını tahvil satışı gibi açık piyasa işlemleriyle dengelemesidir; para arzı kontrolünü sağlar.', kaynak:{tur:'donemsonu',yil:2017,donem:'bahar'} },
  { id:'IKT104-080', unite:3, konu:'Toplam Arz Teorileri', soru:'Firmaların ürünlerine ait fiyatların, piyasada olup bitene anında cevap verememesi varsayımına dayanan teori aşağıdakilerden hangisidir?', secenekler:{A:'Yapışkan Ücret Teorisi',B:'Faktör Yoğunluğu Teorisi',C:'Yapışkan Fiyat Teorisi',D:'Maliyet Esnekliği Teorisi',E:'Yanlış Algı Teorisi'}, dogruCevap:'C', aciklama:'Doğru cevap C\'dir çünkü Yapışkan Fiyat Teorisi, firmaların menü maliyetleri ve uzun vadeli sözleşmeler nedeniyle fiyatlarını hemen ayarlayamadığını savunur. Bu nedenle kısa dönemde toplam arz eğrisi yatay değil pozitif eğimlidir.', kaynak:{tur:'donemsonu',yil:2017,donem:'bahar'} },
];

const mevcutIdler = new Set(data.map(s => s.id));
const eklenecek = yeni.filter(s => !mevcutIdler.has(s.id));

eklenecek.forEach(s => {
  s.dersKodu = 'İKT104U';
  s.dersAdi = 'İktisada Giriş II';
  s.soruTipi = 'çıkmış_soru';
  s.guvenDurumu = 'kontrol_edildi';
  s.kontrolEden = 'gorsel_okuma';
  s.nedenDigerleriDegil = s.nedenDigerleriDegil || '';
  s.ogretimNotu = s.ogretimNotu || '';
});

const yeniData = [...data, ...eklenecek];
fs.writeFileSync(dataPath, JSON.stringify(yeniData, null, 2), 'utf8');

const ikt = yeniData.filter(s => s.dersKodu === 'İKT104U');
console.log(`✓ Toplam ${yeniData.length} soru. İKT104U: ${ikt.length} soru (${ikt.filter(s=>s.guvenDurumu==='kontrol_edildi').length} kontrol_edildi)`);
