const fs = require('fs');
const path = require('path');
const dataPath = path.join(__dirname, '../src/data/questions.json');
const data = JSON.parse(fs.readFileSync(dataPath, 'utf8'));

const yeni = [
  // Ünite 1 - İletişim Kavramı ve Süreci
  { id:'ISL118-021', unite:1, konu:'İletişim Tanımı', soru:'İletişimin en temel tanımı aşağıdakilerden hangisidir?', secenekler:{A:'Bilginin bir yerden başka bir yere taşınması',B:'Anlam ve bilginin iki ya da daha fazla kişi arasında paylaşılması süreci',C:'Mesajların yazılı olarak iletilmesi',D:'Yöneticilerin çalışanlara emir vermesi',E:'Teknolojik araçlarla bilgi aktarımı'}, dogruCevap:'B', aciklama:'Doğru cevap B\'dir çünkü iletişim, yalnızca bilgi taşımakla kalmaz; anlam üretme ve paylaşma sürecidir. En az iki taraf arasında gerçekleşir ve karşılıklı anlayışı hedefler.' },
  { id:'ISL118-022', unite:1, konu:'İletişim Süreci', soru:'İletişim sürecinde "kodlama" ne anlama gelir?', secenekler:{A:'Mesajın alıcıya ulaşması',B:'Alıcının mesajı yorumlaması',C:'Göndericinin iletmek istediği düşünceyi sembollere dönüştürmesi',D:'Geri bildirimin gönderilmesi',E:'Kanalın seçilmesi'}, dogruCevap:'C', aciklama:'Doğru cevap C\'dir çünkü kodlama, göndericinin zihnindeki fikri, duyguyu veya bilgiyi sözcükler, görüntüler ya da jestler gibi sembollere çevirme işlemidir.' },
  { id:'ISL118-023', unite:1, konu:'İletişim Engelleri', soru:'İletişim sürecinde "gürültü" kavramı ne anlama gelir?', secenekler:{A:'Yüksek sesle konuşmak',B:'Toplantıdaki fiziksel ses kirliliği',C:'Mesajın doğru iletilmesini ve anlaşılmasını engelleyen her türlü etken',D:'İletişimin olmadığı ortam',E:'Göndericinin hatalı kodlaması'}, dogruCevap:'C', aciklama:'Doğru cevap C\'dir çünkü iletişim teorisinde gürültü; fiziksel (ses), psikolojik (önyargı), semantik (anlam farkı) veya teknik sorunlar gibi mesajı bozan her türlü engeli kapsar.' },
  { id:'ISL118-024', unite:1, konu:'İletişim Modelleri', soru:'Shannon-Weaver İletişim Modeline göre iletişimin temel öğeleri aşağıdakilerden hangisinde doğru verilmiştir?', secenekler:{A:'Kaynak, mesaj, kanal, alıcı, gürültü',B:'Gönderici, kod, sembol, tercüman',C:'Yönetici, çalışan, rapor, toplantı',D:'Sözcük, cümle, paragraf, metin',E:'Yazılı, sözlü, sözsüz, elektronik'}, dogruCevap:'A', aciklama:'Doğru cevap A\'dır çünkü Shannon-Weaver modeli iletişimi; kaynak (gönderici), mesaj, kanal (iletim ortamı), alıcı ve gürültü öğelerinden oluşan bir sistem olarak tanımlar.' },
  { id:'ISL118-025', unite:1, konu:'Etkili İletişim', soru:'Aşağıdakilerden hangisi etkili iletişimin temel koşullarından biridir?', secenekler:{A:'Mesajın uzun ve ayrıntılı olması',B:'Yalnızca yazılı kanalların kullanılması',C:'Göndericinin alıcıyı ve onun ihtiyaçlarını tanıması',D:'Teknolojik araçların her zaman kullanılması',E:'İletişimin tek yönlü olması'}, dogruCevap:'C', aciklama:'Doğru cevap C\'dir çünkü etkili iletişimde gönderici, alıcının bilgi düzeyini, beklentilerini ve ihtiyaçlarını göz önünde bulundurarak mesajını buna göre şekillendirmelidir.' },
  { id:'ISL118-026', unite:1, konu:'İletişim Süreci', soru:'İletişim sürecinde "kod açma (decoding)" işlemini gerçekleştiren taraf kimdir?', secenekler:{A:'Gönderici',B:'Kanal',C:'Alıcı',D:'Geri bildirim',E:'Gürültü kaynağı'}, dogruCevap:'C', aciklama:'Doğru cevap C\'dir çünkü kod açma, alıcının kendisine ulaşan semboller ve sinyalleri yorumlayarak anlamlı bilgiye dönüştürmesi işlemidir.' },
  { id:'ISL118-027', unite:1, konu:'İletişim Engelleri', soru:'Alıcının mesajı kendi önyargıları ve geçmiş deneyimleri çerçevesinde yorumlaması hangi tür iletişim engelini oluşturur?', secenekler:{A:'Fiziksel engel',B:'Teknik engel',C:'Psikolojik (algısal) engel',D:'Semantik engel',E:'Örgütsel engel'}, dogruCevap:'C', aciklama:'Doğru cevap C\'dir çünkü psikolojik engeller; önyargılar, kişisel deneyimler, değerler ve tutumlar gibi zihinsel faktörlerden kaynaklanır; mesajı nesnel olarak almayı engeller.' },
  { id:'ISL118-028', unite:1, konu:'İletişimin Önemi', soru:'İşletmelerde iletişimin önemi ile ilgili aşağıdaki ifadelerden hangisi yanlıştır?', secenekler:{A:'İletişim, çalışanların motivasyonunu artırır.',B:'Etkili iletişim örgütsel verimliliği yükseltir.',C:'İletişim, yalnızca üst yöneticiler için önemlidir.',D:'İyi iletişim çatışmaları azaltır.',E:'İletişim, örgütsel hedeflere ulaşmada kritik rol oynar.'}, dogruCevap:'C', aciklama:'Doğru cevap C\'dir çünkü iletişim, örgütteki her düzeyde kritik öneme sahiptir. Yalnızca üst yöneticilere özgü değildir; çalışanların tamamı etkili iletişim becerilerine ihtiyaç duyar.' },

  // Ünite 2 - Sözlü İletişim ve Dinleme
  { id:'ISL118-029', unite:2, konu:'Sözlü İletişim', soru:'Sözlü iletişimin yazılı iletişime göre en önemli avantajı aşağıdakilerden hangisidir?', secenekler:{A:'Kalıcı belge oluşturması',B:'Geniş kitlelere aynı anda ulaşabilmesi',C:'Anlık geri bildirim ve esneklik sağlaması',D:'Resmiyet gerektiren durumlarda kullanılabilmesi',E:'İspat değeri taşıması'}, dogruCevap:'C', aciklama:'Doğru cevap C\'dir çünkü sözlü iletişim, konuşmacının alıcının tepkisini anlık olarak görüp mesajını anında ayarlayabilmesine olanak tanır; bu esneklik yazılı iletişimde yoktur.' },
  { id:'ISL118-030', unite:2, konu:'Dinleme Türleri', soru:'Konuşmacının söylediklerini dikkatle takip ederek anlam çıkarmaya ve değerlendirmeye odaklanan dinleme türü aşağıdakilerden hangisidir?', secenekler:{A:'Seçici dinleme',B:'Aktif (etkin) dinleme',C:'Pasif dinleme',D:'Empatik dinleme',E:'Eleştirel dinleme'}, dogruCevap:'B', aciklama:'Doğru cevap B\'dir çünkü aktif dinleme; göz teması kurma, sözsüz onaylama, sorular sorma gibi bilinçli katılım davranışlarıyla konuşmacıya tam dikkat verme sürecidir.' },
  { id:'ISL118-031', unite:2, konu:'Dinleme Engelleri', soru:'Dinleyicinin konuşmacı henüz cümlesini bitirmeden ne söyleyeceğini tahmin ederek gerçekte söyleneni kaçırması hangi dinleme engelini gösterir?', secenekler:{A:'Fiziksel gürültü',B:'Çevresel dikkat dağıtıcılar',C:'Erken değerlendirme / önyargılı dinleme',D:'Dil bariyeri',E:'Bilgi eksikliği'}, dogruCevap:'C', aciklama:'Doğru cevap C\'dir çünkü dinleyicinin mesajı tamamlanmadan sonucu varsayması, aktif olmayan ve önyargılı dinlemenin göstergesidir; gerçek mesajın kaçırılmasına yol açar.' },
  { id:'ISL118-032', unite:2, konu:'Sözlü İletişim', soru:'İş görüşmelerinde karşı tarafı aktif dinlediğinizi göstermek için en uygun davranış aşağıdakilerden hangisidir?', secenekler:{A:'Konuşmacının her cümlesini kesmek',B:'Telefona bakmak',C:'Söylenenleri zaman zaman kendi sözlerinizle özetlemek',D:'Sessiz kalmak ve not almamak',E:'Konuşmacıya sırtınızı dönmek'}, dogruCevap:'C', aciklama:'Doğru cevap C\'dir çünkü söylenenleri parafraz etmek (kendi sözlerinizle özetlemek) hem anladığınızı doğrular hem de konuşmacıya dinlendiğini hissettirerek iletişimi güçlendirir.' },
  { id:'ISL118-033', unite:2, konu:'Konuşma Becerileri', soru:'Etkili bir iş sunumunda önce ne yapılmalıdır?', secenekler:{A:'Sonuç söylenmelidir',B:'Tüm ayrıntılar sıralanmalıdır',C:'Dinleyicinin ilgisini çekecek bir giriş yapılmalıdır',D:'Sorular sorulmalıdır',E:'Tek düze bir ses tonu kullanılmalıdır'}, dogruCevap:'C', aciklama:'Doğru cevap C\'dir çünkü sunumda güçlü bir açılış, dinleyicinin dikkatini ve ilgisini kazanarak mesajın etkili biçimde iletilmesinin temelini atar.' },

  // Ünite 3 - Sözsüz İletişim
  { id:'ISL118-034', unite:3, konu:'Sözsüz İletişim', soru:'Araştırmalara göre yüz yüze iletişimde mesajın büyük çoğunluğu hangi kanal aracılığıyla iletilir?', secenekler:{A:'Kullanılan sözcükler',B:'Sesin tonu ve vurgusu',C:'Sözsüz ipuçları (beden dili, ses tonu, yüz ifadesi)',D:'Yazılı materyaller',E:'Teknolojik araçlar'}, dogruCevap:'C', aciklama:'Doğru cevap C\'dir çünkü Mehrabian\'ın araştırmalarına göre yüz yüze iletişimde anlam; %7 sözcüklerden, %38 ses tonundan, %55 beden dilinden oluşur. Sözsüz kanallar baskın roldedir.' },
  { id:'ISL118-035', unite:3, konu:'Beden Dili', soru:'Kolları kavuşturarak oturmak iş görüşmesinde genellikle ne anlama gelir?', secenekler:{A:'Rahatlık ve güven',B:'Savunmacılık veya kapalılık',C:'Dinlemeye hazır olma',D:'Heyecan ve istek',E:'Saygı gösterme'}, dogruCevap:'B', aciklama:'Doğru cevap B\'dir çünkü kolları kavuşturmak, savunmacı bir tutumu veya kişinin kendini kapattığını, konuya mesafeli durduğunu gösteren yaygın bir beden dili işaretidir.' },
  { id:'ISL118-036', unite:3, konu:'Sözsüz İletişim', soru:'Proksemik (mekânsal mesafe) kavramı iletişimde neyi ifade eder?', secenekler:{A:'Mesajın yazıya dökülmesi',B:'Kişilerin iletişim sırasında birbirlerine olan fiziksel mesafeyi kullanma biçimi',C:'Elektronik mesajlaşma yöntemleri',D:'Örgüt şemasındaki hiyerarşik uzaklık',E:'Zaman yönetimi teknikleri'}, dogruCevap:'B', aciklama:'Doğru cevap B\'dir çünkü proksemik, Edward Hall tarafından tanımlanan; mahrem alan, kişisel alan, sosyal alan ve kamusal alan gibi kategorilerle insanların fiziksel mesafeyi nasıl kullandığını inceleyen alandır.' },
  { id:'ISL118-037', unite:3, konu:'Beden Dili', soru:'İş görüşmesinde sağlam ve kısa bir el sıkışmanın işlevleri arasında aşağıdakilerden hangisi yer almaz?', secenekler:{A:'Güven vermek',B:'Profesyonellik göstermek',C:'İletişimi başlatmak',D:'Üstünlük ve baskınlık kurmak',E:'Saygı iletmek'}, dogruCevap:'D', aciklama:'Doğru cevap D\'dir çünkü iş ortamında el sıkışmanın amacı güven, saygı ve profesyonellik iletmektir. Üstünlük veya baskınlık kurmak ise olumsuz bir niyet olup uygun iş görgüsüne aykırıdır.' },

  // Ünite 4 - Yazılı İletişim
  { id:'ISL118-038', unite:4, konu:'Yazılı İletişim Araçları', soru:'Aşağıdakilerden hangisi işletmelerde kullanılan yazılı iletişim araçlarından biri değildir?', secenekler:{A:'İş mektubu',B:'E-posta',C:'Rapor',D:'Yüz yüze toplantı',E:'Tutanak'}, dogruCevap:'D', aciklama:'Doğru cevap D\'dir çünkü yüz yüze toplantı sözlü iletişim aracıdır. İş mektubu, e-posta, rapor ve tutanak ise yazılı iletişim araçları arasında yer alır.' },
  { id:'ISL118-039', unite:4, konu:'İş Mektubu', soru:'Standart bir iş mektubunda aşağıdaki bölümlerden hangisi genellikle bulunmaz?', secenekler:{A:'Tarih',B:'Alıcının adresi',C:'Kişisel anılar ve duygusal ifadeler',D:'Konu başlığı',E:'Saygı ifadesi'}, dogruCevap:'C', aciklama:'Doğru cevap C\'dir çünkü iş mektupları resmi belge niteliği taşır; kişisel anılar ve aşırı duygusal ifadeler iş yazışmalarına uygun değildir. Mektuplar nesnel, açık ve öz olmalıdır.' },
  { id:'ISL118-040', unite:4, konu:'Rapor Yazımı', soru:'İşletme raporlarında kullanılan yönetici özeti (executive summary) hangi amaca hizmet eder?', secenekler:{A:'Raporun ekler bölümünü oluşturur.',B:'Tüm raporun ana bulgularını ve önerilerini kısaca özetler.',C:'Kaynakça bilgilerini içerir.',D:'Raporun metodolojisini açıklar.',E:'Grafik ve tablolar içerir.'}, dogruCevap:'B', aciklama:'Doğru cevap B\'dir çünkü yönetici özeti, zamanı kısıtlı üst yöneticilerin raporun tamamını okumadan temel bulgulara ve önerilere ulaşabilmesi için hazırlanan kısa ve kapsamlı bölümdür.' },
  { id:'ISL118-041', unite:4, konu:'E-posta Yazımı', soru:'İş e-postalarında aşağıdakilerden hangisi uygun davranış olarak kabul edilmez?', secenekler:{A:'Konu satırını açık ve bilgi verici yazmak',B:'Gerektiğinde tüm şirketi kopyalamak (CC\'ye eklemek)',C:'Kısa ve net bir dil kullanmak',D:'Yanıt vermeden önce e-postayı dikkatlice okumak',E:'Kapanış ifadesi eklemek'}, dogruCevap:'B', aciklama:'Doğru cevap B\'dir çünkü gereksiz kişileri kopyalamak (CC) mesajın önemini azaltır, dikkat dağıtır ve gizlilik sorunlarına yol açabilir. E-postalar yalnızca ilgili kişilere iletilmelidir.' },
  { id:'ISL118-042', unite:4, konu:'Etkili Yazım İlkeleri', soru:'"7C İletişim İlkeleri" arasında yer almayan hangisidir?', secenekler:{A:'Açık (Clear)',B:'Özlü (Concise)',C:'Doğru (Correct)',D:'Karmaşık (Complex)',E:'Eksiksiz (Complete)'}, dogruCevap:'D', aciklama:'Doğru cevap D\'dir çünkü 7C ilkeleri: Clear (açık), Concise (özlü), Correct (doğru), Complete (eksiksiz), Concrete (somut), Courteous (nazik), Coherent (tutarlı)\'dır. Karmaşıklık (Complex) bu ilkelere aykırıdır.' },
  { id:'ISL118-043', unite:4, konu:'Toplantı Yönetimi', soru:'Etkili bir toplantı için toplantıdan önce katılımcılara gönderilmesi gereken belge nedir?', secenekler:{A:'Tutanak',B:'Yönetici özeti',C:'Ajanda (gündem)',D:'Performans raporu',E:'İş mektubu'}, dogruCevap:'C', aciklama:'Doğru cevap C\'dir çünkü ajanda (gündem), toplantıda ele alınacak konuları, sırasını ve sürelerini önceden bildirerek katılımcıların hazırlıklı gelmesini ve toplantının verimli yönetilmesini sağlar.' },

  // Ünite 5 - Örgütsel İletişim
  { id:'ISL118-044', unite:5, konu:'Örgütsel İletişim Ağları', soru:'Çalışanların doğrudan birbirleriyle özgürce iletişim kurabildiği, merkezi bir koordinatörün olmadığı iletişim ağı türü hangisidir?', secenekler:{A:'Zincir ağı',B:'Tekerlek ağı',C:'Tüm kanal ağı (tam bağlantı)',D:'Y ağı',E:'Hiyerarşik ağ'}, dogruCevap:'C', aciklama:'Doğru cevap C\'dir çünkü tüm kanal (tam bağlantı) ağında her üye diğer tüm üyelerle doğrudan iletişim kurabilir; merkezi bir koordinatör yoktur. Yaratıcılık ve katılım en yüksektir.' },
  { id:'ISL118-045', unite:5, konu:'Örgütsel İletişim', soru:'Örgütlerde "gizli haberleşme ağı" veya "dedikodu ağı" olarak bilinen iletişim türü hangisidir?', secenekler:{A:'Dikey iletişim',B:'Yatay iletişim',C:'Çapraz iletişim',D:'Asma sarmaşık (grapevine) iletişimi',E:'Resmi iletişim'}, dogruCevap:'D', aciklama:'Doğru cevap D\'dir çünkü asma sarmaşık iletişimi (grapevine), örgüt içinde gayri resmi kanallarla yayılan dedikodu ve söylentileri ifade eder. Hızlı yayılır ama doğruluğu güvenilir değildir.' },
  { id:'ISL118-046', unite:5, konu:'Resmi İletişim Kanalları', soru:'Aşağıdakilerden hangisi örgüt içi resmi iletişim kanallarına örnek değildir?', secenekler:{A:'Yönetim genelgeleri',B:'Performans değerlendirme raporları',C:'İş arkadaşları arasındaki koridorda yapılan sohbet',D:'Departman toplantıları',E:'Resmi yazışmalar'}, dogruCevap:'C', aciklama:'Doğru cevap C\'dir çünkü koridorda yapılan gayri resmi sohbet, örgütün resmi iletişim sisteminin dışında kalan gayri resmi bir iletişimdir. Diğer seçenekler örgütün resmi kanalları aracılığıyla gerçekleşir.' },
  { id:'ISL118-047', unite:5, konu:'İletişim ve Liderlik', soru:'Liderlik ile iletişim arasındaki ilişki hakkında aşağıdakilerden hangisi doğrudur?', secenekler:{A:'Liderler yalnızca emir verme yoluyla iletişim kurar.',B:'Etkili liderler aynı zamanda etkili iletişimcilerdir.',C:'İletişim becerisi liderlik için gerekli değildir.',D:'Liderler yalnızca yazılı iletişimi tercih etmelidir.',E:'İletişim becerileri doğuştan gelir, geliştirilemez.'}, dogruCevap:'B', aciklama:'Doğru cevap B\'dir çünkü liderliğin temel işlevleri (vizyon oluşturma, motive etme, yönlendirme) güçlü iletişim becerilerine dayanır. Araştırmalar etkili liderlerin aynı zamanda güçlü iletişimciler olduğunu göstermektedir.' },
  { id:'ISL118-048', unite:5, konu:'Çatışma ve İletişim', soru:'Örgütlerde iletişim yetersizliğinin yol açtığı temel sorunlardan biri aşağıdakilerden hangisidir?', secenekler:{A:'Verimlilik artışı',B:'Motivasyon yükselmesi',C:'Örgütsel çatışmaların artması',D:'Müşteri memnuniyetinin yükselmesi',E:'Maliyetlerin düşmesi'}, dogruCevap:'C', aciklama:'Doğru cevap C\'dir çünkü eksik veya hatalı iletişim, yanlış anlaşılmalara ve bilgi boşluklarına yol açar; bu durum çatışmaları artırır, işbirliğini ve verimliliği düşürür.' },

  // Ünite 6 - Kültürlerarası İletişim
  { id:'ISL118-049', unite:6, konu:'Kültürlerarası İletişim', soru:'Kültürlerarası iletişimde "yüksek bağlamlı kültür" (high-context culture) kavramı ne anlama gelir?', secenekler:{A:'Mesajların açık ve doğrudan iletildiği kültürler',B:'İletişimin büyük ölçüde sözsüz ipuçlarına, bağlama ve ilişkilere dayandığı kültürler',C:'Teknolojinin yoğun kullanıldığı kültürler',D:'Yazılı iletişimin baskın olduğu kültürler',E:'Bireyselciliğin ön planda olduğu kültürler'}, dogruCevap:'B', aciklama:'Doğru cevap B\'dir çünkü Hall\'ın modelinde yüksek bağlamlı kültürler (Japonya, Arap ülkeleri, Türkiye), mesajın büyük kısmını bağlam, ilişki ve sözsüz iletişimde taşır; az şey açıkça söylenir.' },
  { id:'ISL118-050', unite:6, konu:'Kültürlerarası İletişim', soru:'Küresel iş ortamında kültürel farklılıkların iletişime etkisi konusunda aşağıdakilerden hangisi yanlıştır?', secenekler:{A:'Farklı kültürlerde sessizliğin anlamı değişebilir.',B:'El sıkışma gibi jestlerin yorumu kültürden kültüre farklılık gösterebilir.',C:'Tüm kültürlerde göz teması saygı belirtisidir.',D:'Zaman anlayışı kültürden kültüre farklıdır.',E:'Resmiyet düzeyi kültüre göre değişir.'}, dogruCevap:'C', aciklama:'Doğru cevap C\'dir çünkü bazı kültürlerde (özellikle Asya ve bazı Afrika kültürleri) aşırı göz teması saygısızlık veya meydan okuma olarak yorumlanabilir. Göz temasının anlamı evrensel değil, kültüre özgüdür.' },
  { id:'ISL118-051', unite:6, konu:'Kültürel Boyutlar', soru:'Hofstede\'nin kültürel boyutlar modeline göre "belirsizlikten kaçınma" yüksek olan toplumlarda iletişim nasıldır?', secenekler:{A:'Belirsiz ve esnek mesajlar tercih edilir.',B:'Kurallara ve formel prosedürlere dayalı iletişim tercih edilir.',C:'Gayri resmi ve spontane iletişim ön plana çıkar.',D:'Yazılı iletişimden kaçınılır.',E:'Hiyerarşi gözetilmeksizin iletişim kurulur.'}, dogruCevap:'B', aciklama:'Doğru cevap B\'dir çünkü belirsizlikten kaçınmanın yüksek olduğu toplumlarda insanlar belirsizliği azaltmak için kurallara, prosedürlere ve formel iletişim kanallarına yönelir.' },

  // Ünite 7 - Sunum ve Konuşma Becerileri
  { id:'ISL118-052', unite:7, konu:'Sunum Becerileri', soru:'Etkili bir sunum yaparken aşağıdakilerden hangisi yapılmamalıdır?', secenekler:{A:'Dinleyicilerle göz teması kurmak',B:'Slaytlardaki her metni kelimesi kelimesine okumak',C:'Sunumu pratik yapmak',D:'Sorulara hazırlıklı olmak',E:'Net bir açılış ve kapanış yapmak'}, dogruCevap:'B', aciklama:'Doğru cevap B\'dir çünkü slayttaki metni kelimesi kelimesine okumak, sunumu sıkıcı kılar ve dinleyiciyle bağ kurulmasını engeller. Slaytlar yalnızca destekleyici görsel araç olmalı; sunum sözlü ve spontane yapılmalıdır.' },
  { id:'ISL118-053', unite:7, konu:'Konuşma Kaygısı', soru:'Topluluk önünde konuşma kaygısını azaltmak için en etkili yöntem aşağıdakilerden hangisidir?', secenekler:{A:'Sunumdan kaçınmak',B:'Hazırlıksız sahneye çıkmak',C:'Düzenli pratik yapmak ve hazırlıklı olmak',D:'Çok hızlı konuşmak',E:'Dinleyicilere bakmaktan kaçınmak'}, dogruCevap:'C', aciklama:'Doğru cevap C\'dir çünkü sunum kaygısının en büyük nedeni hazırlık eksikliğidir. Düzenli pratik (rehearsal) ve kapsamlı hazırlık özgüveni artırarak kaygıyı önemli ölçüde azaltır.' },
  { id:'ISL118-054', unite:7, konu:'Sunum Yapısı', soru:'Bir sunumun "sonuç" bölümünde aşağıdakilerden hangisi yapılmalıdır?', secenekler:{A:'Yeni konular ve bilgiler sunulmalıdır.',B:'Ana mesajlar özetlenmeli ve eylem çağrısı yapılmalıdır.',C:'Ayrıntılı istatistikler paylaşılmalıdır.',D:'Teknik terimler açıklanmalıdır.',E:'Dinleyicinin dikkatini çekmek için şaka yapılmalıdır.'}, dogruCevap:'B', aciklama:'Doğru cevap B\'dir çünkü sonuç bölümünde sunumun ana mesajları pekiştirilir ve dinleyiciden beklenen adım ya da karar (eylem çağrısı) net biçimde ifade edilir.' },
  { id:'ISL118-055', unite:7, konu:'Görsel Araçlar', soru:'Sunumlarda görsel araç kullanmanın temel amacı nedir?', secenekler:{A:'Sözlü iletişimi tamamen ortadan kaldırmak',B:'Sunumu uzatmak',C:'Karmaşık bilgileri anlaşılır kılmak ve mesajı pekiştirmek',D:'Konuşmacının hazırlıksızlığını gizlemek',E:'Mümkün olduğunca fazla metin göstermek'}, dogruCevap:'C', aciklama:'Doğru cevap C\'dir çünkü görseller, soyut ve karmaşık bilgileri somutlaştırarak anlaşılırlığı artırır ve sözel mesajı pekiştirerek kalıcılığı yükseltir.' },

  // Ünite 8 - Teknoloji Destekli İletişim ve Kriz İletişimi
  { id:'ISL118-056', unite:8, konu:'Dijital İletişim', soru:'İşletmelerde kurumsal iletişim amacıyla kullanılan intranet sistemi ne işe yarar?', secenekler:{A:'Müşterilerle dış iletişimi yönetir.',B:'Yalnızca sosyal medya paylaşımlarını kapsar.',C:'Örgüt içi bilgi paylaşımı ve iletişim için kullanılan özel ağdır.',D:'İnternete açık genel bir platformdur.',E:'Yalnızca yöneticilerin kullandığı bir sistemdir.'}, dogruCevap:'C', aciklama:'Doğru cevap C\'dir çünkü intranet, örgüt içi iletişimi ve bilgi paylaşımını destekleyen, yalnızca çalışanlara açık özel bir ağ altyapısıdır. Dışarıdan erişime kapalıdır.' },
  { id:'ISL118-057', unite:8, konu:'Kriz İletişimi', soru:'Bir kriz durumunda işletmenin iletişim stratejisinde ilk yapması gereken aşağıdakilerden hangisidir?', secenekler:{A:'Tüm iletişimi durdurmak',B:'Suçu başkasına yıkmak',C:'Hızlı, şeffaf ve doğru bilgi vermek',D:'Medyadan uzak durmak',E:'Sosyal medya hesaplarını kapatmak'}, dogruCevap:'C', aciklama:'Doğru cevap C\'dir çünkü kriz iletişiminin temel ilkesi hız, şeffaflık ve doğruluktur. Kamuoyuna eksik veya gecikmeli bilgi vermek güven kaybına ve itibar zararına yol açar.' },
  { id:'ISL118-058', unite:8, konu:'Sosyal Medya', soru:'İşletmelerin sosyal medyayı iletişim aracı olarak kullanmasının başlıca riski aşağıdakilerden hangisidir?', secenekler:{A:'Maliyetlerin yükselmesi',B:'Müşteri tabanının daralması',C:'Kontrolsüz yorum ve olumsuz içeriklerin hızla yayılması',D:'Çalışan sayısının artması',E:'Ürün kalitesinin düşmesi'}, dogruCevap:'C', aciklama:'Doğru cevap C\'dir çünkü sosyal medyada olumsuz yorumlar ve kriz içerikleri çok hızlı yayılabilir. İşletmelerin bu kanalları izlemesi ve hızlı müdahale etmesi büyük önem taşır.' },
  { id:'ISL118-059', unite:8, konu:'Kurumsal İletişim', soru:'Kurumsal itibar yönetimi bağlamında aşağıdakilerden hangisi doğrudur?', secenekler:{A:'İtibar yalnızca reklamlar aracılığıyla şekillenir.',B:'İtibar yönetimi sadece kriz dönemlerinde yapılır.',C:'Kurumsal iletişim, örgütün iç ve dış paydaşlarla güven inşa etme sürecini kapsar.',D:'İtibar yönetimi yalnızca halkla ilişkiler departmanının işidir.',E:'Çalışanların itibar üzerinde herhangi bir etkisi yoktur.'}, dogruCevap:'C', aciklama:'Doğru cevap C\'dir çünkü kurumsal itibar; müşteriler, çalışanlar, yatırımcılar ve toplumla uzun vadeli güven ilişkisi kurularak yönetilir. Tüm örgütsel iletişim bu sürece katkı sağlar.' },
  { id:'ISL118-060', unite:8, konu:'Müzakere İletişimi', soru:'Kazan-kazan (win-win) müzakere anlayışında temel amaç nedir?', secenekler:{A:'Karşı tarafın tamamen yenilgiye uğratılması',B:'Her iki tarafın da çıkarlarını karşılayan çözümlere ulaşılması',C:'Mümkün olan en kısa sürede anlaşmaya varılması',D:'Yalnızca fiyat konusunda uzlaşı sağlanması',E:'Müzakereyi ertelemek'}, dogruCevap:'B', aciklama:'Doğru cevap B\'dir çünkü kazan-kazan yaklaşımı, tarafların çıkarlarını anlayarak her iki tarafı da tatmin eden yaratıcı çözümler geliştirmeyi hedefler; uzun vadeli ilişkileri güçlendirir.' },
  { id:'ISL118-061', unite:8, konu:'Müzakere Teknikleri', soru:'Müzakereci "BATNA" kavramı ne anlama gelir?', secenekler:{A:'En kötü olası anlaşma senaryosu',B:'Müzakerenin iptal edilmesi',C:'Müzakeredeki en iyi alternatif eylem (Best Alternative To a Negotiated Agreement)',D:'Karşı tarafın teklifini reddetme hakkı',E:'Müzakere öncesi yapılan hazırlık'}, dogruCevap:'C', aciklama:'Doğru cevap C\'dir çünkü BATNA, bir anlaşmaya varılamazsa müzakerecinin sahip olduğu en iyi alternatifi ifade eder. Güçlü BATNA, müzakerede pazarlık gücünü artırır.' },
  { id:'ISL118-062', unite:5, konu:'Örgütsel İletişim', soru:'İşletmelerde "iletişim doyumu" kavramı neyi ifade eder?', secenekler:{A:'İletişim kanallarının sayısını',B:'Çalışanın örgütteki iletişim süreçlerinden duyduğu memnuniyet düzeyini',C:'Mesajların iletilme hızını',D:'Teknolojik altyapının kalitesini',E:'Yöneticilerin iletişim sıklığını'}, dogruCevap:'B', aciklama:'Doğru cevap B\'dir çünkü iletişim doyumu, çalışanların örgüt içindeki bilgi akışı, geri bildirim mekanizmaları ve iletişim ikliminden ne ölçüde memnun olduğunu gösterir; örgütsel bağlılıkla yakından ilişkilidir.' },
  { id:'ISL118-063', unite:6, konu:'Kültürlerarası İletişim', soru:'Uluslararası iş toplantılarında kültürel farklılıklara uyum sağlamak için aşağıdakilerden hangisi önerilmez?', secenekler:{A:'Karşı kültürün normlarını önceden araştırmak',B:'Sabırlı ve saygılı bir tutum sergilemek',C:'Kendi kültürünüzün değerlerini evrensel kabul etmek',D:'Dil bariyerlerini göz önünde bulundurmak',E:'Yerel adetlere saygı göstermek'}, dogruCevap:'C', aciklama:'Doğru cevap C\'dir çünkü kendi kültürel değerlerini evrensel kabul etmek (etnosentrizm), kültürlerarası iletişimin önündeki en büyük engellerden biridir. Farklı kültürlere saygı ve esneklik şarttır.' },
  { id:'ISL118-064', unite:7, konu:'Sunum Teknikleri', soru:'Bir sunumda "kanca" (hook) tekniği nedir?', secenekler:{A:'Sunumun sonunda özet yapma tekniği',B:'Sunuma başlarken dinleyicilerin dikkatini çeken etkileyici bir giriş yapma',C:'Slaytlara görsel eklemek',D:'Sunumu zamanında bitirme',E:'Sorulara yanıt verme yöntemi'}, dogruCevap:'B', aciklama:'Doğru cevap B\'dir çünkü kanca tekniği; ilginç bir soru, şaşırtıcı istatistik, kısa hikaye veya alıntı ile başlayarak dinleyicinin dikkatini ve merakını hemen kazanma yöntemidir.' },
  { id:'ISL118-065', unite:1, konu:'İletişim Türleri', soru:'Aşağıdakilerden hangisi "tek yönlü iletişim" örneğidir?', secenekler:{A:'Yüz yüze grup tartışması',B:'Telekonferans',C:'TV veya radyo yayını',D:'E-posta yazışması',E:'Toplantıda soru-cevap'}, dogruCevap:'C', aciklama:'Doğru cevap C\'dir çünkü TV ve radyo yayınında mesaj yalnızca yayıncıdan izleyiciye/dinleyiciye akar; izleyici anında geri bildirim veremez. Bu tek yönlü iletişime klasik örnektir.' },
  { id:'ISL118-066', unite:2, konu:'Sözlü İletişim', soru:'Empati kurarak dinleme, dinleyicinin ne yapmasını gerektirir?', secenekler:{A:'Konuşmacıyla tartışmak',B:'Konuşmacıyı eleştirmek',C:'Konuşmacının bakış açısını ve duygularını anlamaya çalışmak',D:'Konuşmacının söylediklerini kaydetmek',E:'Yalnızca olaylara odaklanmak'}, dogruCevap:'C', aciklama:'Doğru cevap C\'dir çünkü empatik dinleme, dinleyicinin konuşmacının hissettiklerini ve düşündüklerini kendi yerine koyarak anlamaya çalışmasını içerir; değer yargılamadan duygusal bağ kurmaktır.' },
  { id:'ISL118-067', unite:3, konu:'Sözsüz İletişim', soru:'İş hayatında kıyafet seçimi hangi iletişim kategorisinde değerlendirilir?', secenekler:{A:'Yazılı iletişim',B:'Sözlü iletişim',C:'Sözsüz iletişim (görsel kimlik)',D:'Elektronik iletişim',E:'Yasal iletişim'}, dogruCevap:'C', aciklama:'Doğru cevap C\'dir çünkü kıyafet, görünüş ve aksesuarlar; söz kullanmadan kimlik, statü ve profesyonellik hakkında mesaj ileten sözsüz iletişim öğeleridir.' },
  { id:'ISL118-068', unite:4, konu:'Yazılı İletişim', soru:'Aşağıdakilerden hangisi etkili bir iş e-postasının özelliklerinden biri değildir?', secenekler:{A:'Açık ve bilgi verici bir konu (subject) satırı',B:'Kısa ve net içerik',C:'Uygun kapanış ifadesi',D:'Tüm e-postayı büyük harflerle yazmak',E:'Gerekli ekleri eklemek'}, dogruCevap:'D', aciklama:'Doğru cevap D\'dir çünkü e-postada tüm büyük harf kullanmak "bağırma" olarak algılanır ve profesyonel olmayan bir izlenim yaratır. Büyük harfler yalnızca uyarı veya vurgu için kısıtlı kullanılmalıdır.' },
  { id:'ISL118-069', unite:5, konu:'Örgütsel İletişim', soru:'Örgütte "açık kapı politikası" uygulaması neyi ifade eder?', secenekler:{A:'Ofis kapılarının sürekli açık bırakılması',B:'Çalışanların yöneticilere serbestçe ulaşabildiği bir iletişim iklimi yaratılması',C:'Özel görüşmelerin yapılmaması',D:'Fiziksel ofis duvarlarının kaldırılması',E:'Yalnızca üst yönetimle iletişim kurulması'}, dogruCevap:'B', aciklama:'Doğru cevap B\'dir çünkü açık kapı politikası; çalışanların yöneticilerine görüş, öneri veya sorunlarını doğrudan iletebileceği güven temelli bir örgüt iklimini ifade eder.' },
  { id:'ISL118-070', unite:6, konu:'Kültürlerarası İletişim', soru:'Aşağıdakilerden hangisi kültürlerarası iletişim yetkinliğinin bileşenlerinden biridir?', secenekler:{A:'Yalnızca dil bilgisi',B:'Kültürel farkındalık, esneklik ve empati',C:'Kendi kültürünü üstün görme',D:'Teknik beceriler',E:'Coğrafya bilgisi'}, dogruCevap:'B', aciklama:'Doğru cevap B\'dir çünkü kültürlerarası iletişim yetkinliği; farklı kültürlerin değerlerine farkındalık, esneklik, empati ve uyum sağlama becerilerini kapsayan çok boyutlu bir yeterlilik bütünüdür.' },
  { id:'ISL118-071', unite:7, konu:'Sunum Becerileri', soru:'Sunumda ses tonu ve vurguyu değiştirmenin amacı nedir?', secenekler:{A:'Dinleyicinin dikkatini dağıtmak',B:'Konuşmayı uzatmak',C:'Önemli noktaları vurgulamak ve dinleyiciyi canlı tutmak',D:'Hızlı bitirmek',E:'Teknik terimleri açıklamak'}, dogruCevap:'C', aciklama:'Doğru cevap C\'dir çünkü ses tonu ve hızını değiştirmek, dinleyicinin dikkatini canlı tutar ve konuşmacının hangi noktaların daha önemli olduğunu vurgulamasını sağlar.' },
  { id:'ISL118-072', unite:8, konu:'Dijital İletişim', soru:'Kurumsal iletişimde "omnichannel" yaklaşımı ne anlama gelir?', secenekler:{A:'Yalnızca dijital kanalların kullanılması',B:'Tüm iletişim kanallarının entegre ve tutarlı biçimde kullanılması',C:'Tek bir iletişim kanalına odaklanmak',D:'Sosyal medyanın reddedilmesi',E:'Yalnızca müşterilere yönelik iletişim'}, dogruCevap:'B', aciklama:'Doğru cevap B\'dir çünkü omnichannel yaklaşım, e-posta, telefon, sosyal medya, yüz yüze gibi tüm kanalların tutarlı ve entegre biçimde kullanılarak kesintisiz bir iletişim deneyimi oluşturulmasını hedefler.' },
  { id:'ISL118-073', unite:1, konu:'İletişim Süreci', soru:'Aşağıdakilerden hangisi iletişim kanalı seçimini etkileyen faktörlerden biri değildir?', secenekler:{A:'Mesajın aciliyeti',B:'Alıcının tercihleri',C:'Konuşmacının saç rengi',D:'Gizlilik ihtiyacı',E:'Mesajın karmaşıklığı'}, dogruCevap:'C', aciklama:'Doğru cevap C\'dir çünkü kanal seçimini; mesajın içeriği ve aciliyeti, alıcının özellikleri, gizlilik gereksinimleri ve geri bildirim ihtiyacı gibi faktörler belirler. Kişisel fiziksel özellikler bu kararla ilgisizdir.' },
  { id:'ISL118-074', unite:2, konu:'Dinleme', soru:'Etkin (aktif) dinlemenin temel bileşenlerinden hangisi değildir?', secenekler:{A:'Konuşmacıyla göz teması',B:'Söylenenleri parafraz etme',C:'Konuşmacı konuşurken yanıt hazırlama',D:'Doğrulayıcı sorular sorma',E:'Dikkat dağıtıcılardan uzak durma'}, dogruCevap:'C', aciklama:'Doğru cevap C\'dir çünkü konuşmacı henüz konuşurken yanıt hazırlamak, gerçek anlamda dinlemeyi engeller. Aktif dinleme önce tam anlamıyla duymayı ve anlamayı gerektirir; yanıt daha sonra oluşturulur.' },
  { id:'ISL118-075', unite:3, konu:'Sözsüz İletişim', soru:'Kronemik (kronimetri) kavramı sözsüz iletişimde neyi inceler?', secenekler:{A:'Ses tonunun kullanımı',B:'Göz hareketleri',C:'Zamanın kullanımı ve zaman algısının iletişime etkisi',D:'Fiziksel mesafeyi',E:'Kıyafet ve görünüşü'}, dogruCevap:'C', aciklama:'Doğru cevap C\'dir çünkü kronemik, zamanın iletişimde nasıl kullanıldığını inceler: toplantıya geç kalma, dakikliğe verilen önem, sessizliğin süresi gibi konular kültüre göre farklı anlam taşır.' },
  { id:'ISL118-076', unite:4, konu:'Yazılı İletişim', soru:'İş yazışmalarında "CC" (Carbon Copy/Karbon Kopya) alanı nasıl kullanılmalıdır?', secenekler:{A:'Mesajın ana alıcısını belirtmek için',B:'Gizli alıcıları bildirmek için',C:'Bilgi amaçlı gönderim yapılacak kişileri eklemek için',D:'Ekler için',E:'Yanıt beklenmeyen kişiler dışındaki herkes için'}, dogruCevap:'C', aciklama:'Doğru cevap C\'dir çünkü CC alanı, e-postayı doğrudan almak zorunda olmayan ama bilgi sahibi olması gereken kişileri eklemek için kullanılır. Gizli kopyalar için BCC (Blind Carbon Copy) kullanılır.' },
  { id:'ISL118-077', unite:5, konu:'Örgütsel İletişim', soru:'İşletmelerde "yönetim kurulu bülteni" ya da "şirket gazetesi" hangi iletişim türüne örnektir?', secenekler:{A:'Dikey aşağı doğru resmi iletişim',B:'Yatay iletişim',C:'Gayri resmi iletişim',D:'Kriz iletişimi',E:'Dış iletişim'}, dogruCevap:'A', aciklama:'Doğru cevap A\'dır çünkü yönetim kurulu bülteni, şirket gazetesi gibi araçlar üst yönetimden çalışanlara bilgi ve politika iletmek amacıyla kullanılan dikey aşağı doğru resmi iletişim araçlarıdır.' },
  { id:'ISL118-078', unite:6, konu:'Kültürlerarası İletişim', soru:'Hofstede\'nin "güç mesafesi" (power distance) yüksek olan kültürlerde iletişim nasıl gerçekleşir?', secenekler:{A:'Hiyerarşi gözetilmeksizin serbestçe iletişim kurulur.',B:'Alt kademeler üst kademeye açıkça itiraz edebilir.',C:'Hiyerarşik farklılıklar belirgindir; ast, üstle formal biçimde iletişim kurar.',D:'Herkes eşit derecede söz hakkına sahiptir.',E:'Gayri resmi iletişim baskındır.'}, dogruCevap:'C', aciklama:'Doğru cevap C\'dir çünkü güç mesafesinin yüksek olduğu kültürlerde (bazı Asya, Latin Amerika ve Orta Doğu ülkeleri) hiyerarşi belirgindir; alt kademedekiler üstleriyle resmi ve saygılı bir dil kullanır, itiraz etmekten kaçınır.' },
  { id:'ISL118-079', unite:7, konu:'Sunum Teknikleri', soru:'Soru-cevap bölümünü en iyi yönetme biçimi aşağıdakilerden hangisidir?', secenekler:{A:'Soruları görmezden gelmek',B:'Soruları kısa kesmek',C:'Soruyu dinlemek, anladığınızı göstermek ve net yanıt vermek',D:'Her soruya "bilmiyorum" demek',E:'Soru sormayı yasaklamak'}, dogruCevap:'C', aciklama:'Doğru cevap C\'dir çünkü etkili soru yönetimi: soruyu dikkatlice dinlemeyi, gerekirse yineleyerek anladığınızı göstermeyi ve açık, dürüst bir yanıt vermeyi kapsar. Güvensizlik hissi yaratmamak için soru atlamamalıdır.' },
  { id:'ISL118-080', unite:8, konu:'Kriz İletişimi', soru:'Kriz iletişiminde "sözcü" (spokesperson) rolü için en önemli özellik hangisidir?', secenekler:{A:'Genç yaşta olması',B:'Teknik bilgiye sahip olması',C:'Güvenilir, sakin ve eğitimli bir iletişimci olması',D:'Sosyal medyayı iyi kullanması',E:'Mümkün olduğunca az konuşması'}, dogruCevap:'C', aciklama:'Doğru cevap C\'dir çünkü kriz dönemlerinde sözcü; kamuoyunun güvenini korumak, panik yaratmamak ve doğru bilgiyi net biçimde iletmek zorundadır. Güvenilirlik, sakinlik ve iletişim eğitimi temel niteliklerdir.' },
];

const mevcutIdler = new Set(data.map(s => s.id));
const eklenecek = yeni.filter(s => !mevcutIdler.has(s.id));

eklenecek.forEach(s => {
  s.dersKodu = 'İŞL118U';
  s.dersAdi = 'İşletme İletişimi';
  s.soruTipi = 'konu_pekiştirme';
  s.guvenDurumu = 'kontrol_edildi';
  s.kontrolEden = 'manuel_uretim';
  s.nedenDigerleriDegil = s.nedenDigerleriDegil || '';
  s.ogretimNotu = s.ogretimNotu || '';
  s.kaynak = s.kaynak || { tur: 'konu_pekistirme', yil: null, donem: null };
});

const yeniData = [...data, ...eklenecek];
fs.writeFileSync(dataPath, JSON.stringify(yeniData, null, 2), 'utf8');

const isl118 = yeniData.filter(s => s.dersKodu === 'İŞL118U');
console.log(`✓ Toplam ${yeniData.length} soru. İŞL118U: ${isl118.length} soru (${isl118.filter(s=>s.guvenDurumu==='kontrol_edildi').length} kontrol_edildi)`);
