const fs = require('fs');
const path = require('path');
const dataPath = path.join(__dirname, '../src/data/questions.json');
const data = JSON.parse(fs.readFileSync(dataPath, 'utf8'));

const yeni = [
  // 2018 arasinav (q6 boş, q17 iptal - 18 soru)
  { id:'SOS114-021', unite:1, konu:'Algı', soru:'Kırmızı bir elmanın bir kısmının güneşte, bir kısmının ise gölgede kaldığında elmanın tümünün kırmızı olarak algılanması aşağıdakilerden hangisine bir örnektir?', secenekler:{A:'Şekil-zemin ilişkisi',B:'Şekil değişmezliği',C:'Büyüklük değişmezliği',D:'Ortak kader ilkesi',E:'Renk değişmezliği'}, dogruCevap:'E', aciklama:'Doğru cevap E\'dir çünkü renk değişmezliği, bir nesnenin farklı ışık koşullarında bile aynı renkte algılanması ilkesidir. Elmanın bir kısmı gölgede olsa da beyin bunu kırmızı olarak algılamaya devam eder.', kaynak:{tur:'arasinav',yil:2018,donem:'güz'} },
  { id:'SOS114-022', unite:1, konu:'Algı', soru:'Stadyumda futbol maçı izleyen bir bireyin kaleciye odaklanması durumunda zemin aşağıdakilerden hangisi olur?', secenekler:{A:'Seyirciler',B:'Futbol sahası',C:'Hakem',D:'Sesler',E:'Formalar'}, dogruCevap:'A', aciklama:'Doğru cevap A\'dır çünkü şekil-zemin ilişkisinde odaklanılan nesne (kaleci) şekli, geriye kalan her şey (seyirciler dahil) zemini oluşturur.', kaynak:{tur:'arasinav',yil:2018,donem:'güz'} },
  { id:'SOS114-023', unite:1, konu:'Araştırma Yöntemleri', soru:'Çocukların liderlik özelliklerini incelemek için onlarla birlikte sınıf ortamında bulunmak aşağıdaki araştırma yöntemlerinden hangisine bir örnektir?', secenekler:{A:'Gözlem',B:'Deneysel yöntem',C:'Anket',D:'Test',E:'Olay incelemesi'}, dogruCevap:'A', aciklama:'Doğru cevap A\'dır çünkü araştırmacının katılımcılarla birlikte doğal ortamda bulunarak davranışlarını izlemesi gözlem yöntemidir.', kaynak:{tur:'arasinav',yil:2018,donem:'güz'} },
  { id:'SOS114-024', unite:1, konu:'Psikoloji Bakış Açıları', soru:'İngiltere\'de yaşayan insanların mutluluk kaynakları ile El Salvador\'da yaşayan insanların mutluluk kaynaklarının farklı olacağından yola çıkılarak yapılan bir araştırmadaki psikoloji bilimi bakış açısı aşağıdakilerden hangisidir?', secenekler:{A:'Hümanistik',B:'Biyolojik',C:'Psikodinamik',D:'Bilişsel',E:'Sosyo-kültürel'}, dogruCevap:'E', aciklama:'Doğru cevap E\'dir çünkü sosyo-kültürel bakış açısı, kültür ve sosyal çevrenin davranışı nasıl etkilediğini inceler. Farklı ülkelerdeki insanların mutluluk kaynaklarının farklılaşması kültürel etkileri yansıtır.', kaynak:{tur:'arasinav',yil:2018,donem:'güz'} },
  { id:'SOS114-025', unite:2, konu:'Algı', soru:'Bebeğin annesinin sesini tanımasında etkili olan faktör aşağıdakilerden hangisidir?', secenekler:{A:'Zeka',B:'Kültür',C:'Kişilik',D:'Deneyim',E:'Uyarıcı'}, dogruCevap:'D', aciklama:'Doğru cevap D\'dir çünkü bebek annesinin sesini daha önce duyarak tanımayı öğrenmiştir; bu bir deneyim ve öğrenme sürecinin ürünüdür.', kaynak:{tur:'arasinav',yil:2018,donem:'güz'} },
  { id:'SOS114-026', unite:2, konu:'Algı', soru:'Telefonda konuşurken karşı tarafın sesinin sık sık kesilmesine rağmen bireyin söylenenleri algılayabilmesi aşağıdaki gruplama ilkelerinden hangisine bir örnektir?', secenekler:{A:'Tamamlama',B:'Süreklilik',C:'Yakınlık',D:'Benzerlik',E:'Ortak kader ilkesi'}, dogruCevap:'A', aciklama:'Doğru cevap A\'dır çünkü tamamlama ilkesine göre beyin, eksik veya bölünmüş uyarıcıları bütünleyerek tam bir anlam çıkarır.', kaynak:{tur:'arasinav',yil:2018,donem:'güz'} },
  { id:'SOS114-027', unite:1, konu:'Psikoloji Bakış Açıları', soru:'İnsan davranışlarının altında yatan bilinçdışı güdüleri araştıran psikoloji bilimi bakış açısı aşağıdakilerden hangisidir?', secenekler:{A:'Bilişsel',B:'Hümanistik',C:'Psikodinamik',D:'Biyolojik',E:'Sosyo-kültürel'}, dogruCevap:'C', aciklama:'Doğru cevap C\'dir çünkü psikodinamik bakış açısı (Freud\'un kurduğu) bilinçdışı güdülerin davranışları nasıl yönlendirdiğini araştırır.', kaynak:{tur:'arasinav',yil:2018,donem:'güz'} },
  { id:'SOS114-028', unite:1, konu:'Psikoloji Tarihi', soru:'İşlevselcilik ve onun temsilcisi William James ile ilgili aşağıdaki ifadelerden hangisi yanlıştır? (I. Psikolojinin Prensipleri isimli kitabın yazarıdır. II. İlk psikoloji laboratuvarını kurmuştur. III. Zihnin çevreden gelen uyarıcılara nasıl uyum sağladığını araştırmıştır. IV. Yapısalcı bakış açısına tepki olarak doğmuştur. V. Zihinsel faaliyetlerin ne işe yaradığını incelemiştir.)', secenekler:{A:'I',B:'II',C:'III',D:'IV',E:'V'}, dogruCevap:'B', aciklama:'Doğru cevap B\'dir çünkü ilk psikoloji laboratuvarını kuran William James değil, Wilhelm Wundt\'tur (1879, Leipzig). James işlevselciliğin önemli temsilcisidir ancak laboratuvar kurucusu değildir.', kaynak:{tur:'arasinav',yil:2018,donem:'güz'} },
  { id:'SOS114-029', unite:1, konu:'Psikoloji Tanımı', soru:'Aşağıdakilerden hangisi psikolojinin doğrudan ilgi alanına giren konulardan biri değildir?', secenekler:{A:'Tükenme',B:'Zihin',C:'Unutkanlık',D:'Kişilik',E:'Hava kirliliği'}, dogruCevap:'E', aciklama:'Doğru cevap E\'dir çünkü hava kirliliği çevre bilimleri ve kimyanın konusudur; psikoloji zihin, davranış, kişilik, duygu gibi konularla ilgilenir.', kaynak:{tur:'arasinav',yil:2018,donem:'güz'} },
  { id:'SOS114-030', unite:3, konu:'Düşünme ve Problem Çözme', soru:'Bilgisayar teknolojilerinde bilgili bir kişinin, bilgisiz bir kişiye göre bilgisayar arızalarını daha etkili bir şekilde çözebilmesini sağlayan faktör aşağıdakilerden hangisidir?', secenekler:{A:'Uzmanlık',B:'Algoritma',C:'İşleve takılma',D:'Kestirme',E:'Hesaplama'}, dogruCevap:'A', aciklama:'Doğru cevap A\'dır çünkü uzmanlık, belirli bir alanda edinilmiş derin bilgi ve deneyimdir; uzmanlar sorunları daha hızlı ve doğru çözerler.', kaynak:{tur:'arasinav',yil:2018,donem:'güz'} },
  { id:'SOS114-031', unite:4, konu:'Güdülenme', soru:'Bireylerin ihtiyaçlarının basitten karmaşığa doğru ilerlediğini, bir ihtiyaç doyurulduktan sonra diğer bir ihtiyacın ortaya çıktığını savunan güdü kuramı aşağıdakilerden hangisidir?', secenekler:{A:'Optimal Uyarılma Kuramı',B:'Sosyal İhtiyaçlar Kuramı',C:'İçgüdü Kuramı',D:'İhtiyaçlar Hiyerarşisi Kuramı',E:'Dürtü Azalması Kuramı'}, dogruCevap:'D', aciklama:'Doğru cevap D\'dir çünkü Maslow\'un İhtiyaçlar Hiyerarşisi Kuramı ihtiyaçların basitten karmaşığa (fizyolojik → güvenlik → ait olma → değer → kendini gerçekleştirme) sıralandığını ve bir ihtiyaç karşılandığında üstündekinin ortaya çıktığını savunur.', kaynak:{tur:'arasinav',yil:2018,donem:'güz'} },
  { id:'SOS114-032', unite:5, konu:'Kişilik', soru:'Freud\'a göre insan davranışlarının altında yatan temel içgüdüler aşağıdakilerden hangisinde birlikte ve doğru olarak verilmiştir?', secenekler:{A:'Yaşam - Ölüm',B:'Sosyallik - Çatışma',C:'Yaşam - Cinsellik',D:'Ölüm - Saldırganlık',E:'Güvenlik - Sevgi'}, dogruCevap:'A', aciklama:'Doğru cevap A\'dır çünkü Freud\'a göre iki temel içgüdü vardır: Eros (yaşam/cinsellik içgüdüsü) ve Thanatos (ölüm/saldırganlık içgüdüsü). En kapsayıcı çift "Yaşam - Ölüm"tür.', kaynak:{tur:'arasinav',yil:2018,donem:'güz'} },
  { id:'SOS114-033', unite:3, konu:'Zeka', soru:'Her bireyin "g faktörü" olarak adlandırılan genel bir zeka faktörüne sahip olduğunu savunan bilim insanı aşağıdakilerden hangisidir?', secenekler:{A:'Sternberg',B:'Gardner',C:'Thurstone',D:'Binet',E:'Spearman'}, dogruCevap:'E', aciklama:'Doğru cevap E\'dir çünkü Charles Spearman genel zeka faktörü (g faktörü) kuramını geliştirmiştir. Gardner çoklu zeka, Thurstone birincil zihinsel yetenekler, Sternberg üçlü zeka kuramını savunur.', kaynak:{tur:'arasinav',yil:2018,donem:'güz'} },
  { id:'SOS114-034', unite:4, konu:'Duygu', soru:'Duygunun, olayın kendisinden değil, olay hakkındaki yorumlarımızdan ortaya çıktığını ileri süren kuram aşağıdakilerden hangisidir?', secenekler:{A:'James-Lange Kuramı',B:'Bilişsel Kuram',C:'Duygusal Kuram',D:'Cannon-Bard Kuramı',E:'Davranışsal Kuram'}, dogruCevap:'B', aciklama:'Doğru cevap B\'dir çünkü Bilişsel Kuram (Schachter-Singer) duyguların olayın nesnel özelliklerinden değil, o olayı nasıl yorumladığımızdan kaynaklandığını savunur.', kaynak:{tur:'arasinav',yil:2018,donem:'güz'} },
  { id:'SOS114-035', unite:3, konu:'Düşünme ve Problem Çözme', soru:'Bilge, "öğrenme" kavramını oluştururken o kavramı en iyi şekilde temsil edeceğini düşündüğü "bilgi" ve "davranış" gibi terimlerden yola çıkıyor. Bilge\'nin kullandığı kavram oluşturma modeli aşağıdakilerden hangisidir?', secenekler:{A:'Kestirme',B:'Özellikler',C:'Dil',D:'Prototip',E:'Algoritma'}, dogruCevap:'D', aciklama:'Doğru cevap D\'dir çünkü prototip modeli, kavramları o kategorinin en iyi örneği (prototip) aracılığıyla temsil etmeye dayanır. Bilge en tipik özellikleri (bilgi, davranış) kullanarak kavramı oluşturmaktadır.', kaynak:{tur:'arasinav',yil:2018,donem:'güz'} },
  { id:'SOS114-036', unite:3, konu:'Düşünme ve Problem Çözme', soru:'Matematikteki pisagor formülü aşağıdakilerden hangisine bir örnektir?', secenekler:{A:'Kestirme',B:'Amaç analizi',C:'Kategorileştirme',D:'Algoritma',E:'Zihinsel tanım'}, dogruCevap:'D', aciklama:'Doğru cevap D\'dir çünkü algoritma, kesin adımlar izlendiğinde doğru sonuca ulaşan bir problem çözme yöntemidir. Pisagor formülü (a²+b²=c²) doğru uygulandığında her zaman doğru sonuç verir.', kaynak:{tur:'arasinav',yil:2018,donem:'güz'} },
  { id:'SOS114-037', unite:3, konu:'Dil ve Düşünce', soru:'Dünyayı anlamak için kullanılan kategori ve ilişkilerin dilden türediğini ve dilin dünyanın algılanış biçimini yapılandırdığını savunan bilim insanı aşağıdakilerden hangisidir?', secenekler:{A:'Smith',B:'Wittgenstein',C:'Whorf',D:'Locke',E:'Blau'}, dogruCevap:'C', aciklama:'Doğru cevap C\'dir çünkü Benjamin Lee Whorf, dilsel görelilik hipotezi ile dilin düşünceyi ve algıyı şekillendirdiğini savunmuştur. Bu görüş Sapir-Whorf hipotezi olarak da bilinir.', kaynak:{tur:'arasinav',yil:2018,donem:'güz'} },
  { id:'SOS114-038', unite:4, konu:'Duygu', soru:'Bireyin öfkelendiğinde vücut ısısının artması aşağıdaki duygu bileşenlerinden hangisinin sonucudur?', secenekler:{A:'Duygusal',B:'Fizyolojik',C:'Davranışsal',D:'Bilişsel',E:'Duyusal'}, dogruCevap:'B', aciklama:'Doğru cevap B\'dir çünkü vücut ısısının artması, nabzın hızlanması gibi bedensel değişiklikler duygunun fizyolojik bileşenini oluşturur.', kaynak:{tur:'arasinav',yil:2018,donem:'güz'} },

  // 2018 dönemsonu (20 soru)
  { id:'SOS114-039', unite:4, konu:'Güdülenme', soru:'Maslow\'un İhtiyaçlar Hiyerarşisi Kuramına göre kişisel tatmin ve kişisel başarı aşağıdaki ihtiyaç kategorilerinden hangisinin altında yer alır?', secenekler:{A:'Güvenlik',B:'Değer',C:'Fizyolojik',D:'Ait olma',E:'Kendini gerçekleştirme'}, dogruCevap:'B', aciklama:'Doğru cevap B\'dir çünkü Maslow\'un hiyerarşisinde değer (saygınlık) ihtiyaçları; başarı, yeterlilik ve kişisel tatmini kapsar. Kendini gerçekleştirme ise potansiyelin tam olarak kullanılmasıdır.', kaynak:{tur:'donemsonu',yil:2018,donem:'bahar'} },
  { id:'SOS114-040', unite:2, konu:'Algı', soru:'Stadyumlardaki skor panoları aşağıdaki görünürde hareket türlerinden hangisine bir örnektir?', secenekler:{A:'Doğrusal perspektif',B:'Dokum gradyanı',C:'Otokinetik etki',D:'Stroboskopik hareket',E:'Fi fenomeni'}, dogruCevap:'D', aciklama:'Doğru cevap D\'dir çünkü skor panolarındaki lambalar sırayla yanıp sönerek hareket yanılsaması yaratır; bu stroboskopik harekettir (ardışık duran ışıkların hızla yanmasıyla oluşan görünür hareket).', kaynak:{tur:'donemsonu',yil:2018,donem:'bahar'} },
  { id:'SOS114-041', unite:3, konu:'Zeka', soru:'Cattell\'e göre yeni durum ya da problemler ile uğraşılırken kullanılan ve eğitimden çok az etkilenen zeka türü aşağıdakilerden hangisidir?', secenekler:{A:'Uzamsal zeka',B:'Mantıksal zeka',C:'İçsel zeka',D:'Akıcı zeka',E:'Kristalleşmiş zeka'}, dogruCevap:'D', aciklama:'Doğru cevap D\'dir çünkü Cattell\'e göre akıcı zeka doğuştan gelen, eğitimden az etkilenen ve yeni problemleri çözmede kullanılan zekadır. Kristalleşmiş zeka ise öğrenme ve deneyimle gelişir.', kaynak:{tur:'donemsonu',yil:2018,donem:'bahar'} },
  { id:'SOS114-042', unite:1, konu:'Psikoloji Uzmanlık Alanları', soru:'Çevresel koşulların davranışı nasıl ve ne kadar belirlediğini ortaya koymak için genellikle laboratuvar ortamında insan olmayan deneklerle çalışan psikoloji uzmanlık alanı aşağıdakilerden hangisidir?', secenekler:{A:'Fizyolojik psikoloji',B:'Eğitim psikolojisi',C:'Deneysel psikoloji',D:'Sosyal psikoloji',E:'Klinik psikoloji'}, dogruCevap:'C', aciklama:'Doğru cevap C\'dir çünkü deneysel psikoloji, kontrollü laboratuvar koşullarında hayvanlar ve insanlar üzerinde deney yaparak davranışın nedenlerini araştırır.', kaynak:{tur:'donemsonu',yil:2018,donem:'bahar'} },
  { id:'SOS114-043', unite:5, konu:'Kişilik', soru:'Beş Faktör Kişilik Modeline göre bireyin meraklı olması, değişime yatkın olması ve bağımsızlığı tercih etmesi aşağıdaki boyutlardan hangisinin kapsamında yer alır?', secenekler:{A:'Deneyime açıklık',B:'Dışa dönüklük',C:'Duygusal denge',D:'Sorumluluk',E:'Uyumluluk'}, dogruCevap:'A', aciklama:'Doğru cevap A\'dır çünkü deneyime açıklık boyutu merak, yaratıcılık, değişime yatkınlık ve bağımsız düşünceyi kapsar.', kaynak:{tur:'donemsonu',yil:2018,donem:'bahar'} },
  { id:'SOS114-044', unite:6, konu:'Öğrenme', soru:'Tolman\'ın en önemli çalışması olan ve öğrenildiği halde bireyin davranışlarında görülmeyen ancak teşvik edici bir ortamda ortaya çıkan davranışlar olarak tanımlanan kavram aşağıdakilerden hangisidir?', secenekler:{A:'Algısal öğrenme',B:'Koşullu öğrenme',C:'Gizil öğrenme',D:'İşlevsel öğrenme',E:'Koşulsuz öğrenme'}, dogruCevap:'C', aciklama:'Doğru cevap C\'dir çünkü Tolman\'ın gizil öğrenme deneyleri, öğrenmenin pekiştirme olmadan da gerçekleşebildiğini göstermiştir; davranış ödül sunulana kadar gizli kalır.', kaynak:{tur:'donemsonu',yil:2018,donem:'bahar'} },
  { id:'SOS114-045', unite:6, konu:'Öğrenme', soru:'Aşağıdakilerden hangisi Guthrie\'nin bitişiklik ilkesinin istenmeyen davranışları değiştirme amacı ile kullanabileceği yöntemlerden biridir?', secenekler:{A:'Kırık camlar yöntemi',B:'Genelleme yöntemi',C:'Yorma yöntemi',D:'Belleğe alma yöntemi',E:'Sıralama yöntemi'}, dogruCevap:'A', aciklama:'Doğru cevap A\'dır çünkü Guthrie\'nin kırık camlar yöntemi, istenmeyen davranışı tetikleyen uyarıcıya küçük dozlarda maruz bırakarak tepkiyi söndürmeyi hedefler.', kaynak:{tur:'donemsonu',yil:2018,donem:'bahar'} },
  { id:'SOS114-046', unite:5, konu:'Kişilik', soru:'Freud\'un psikodinamik yaklaşımına göre, çocuğun birçok dürtüsünü frenlemeyi ya da kontrol etmeyi öğrendiği 6-11 yaş arası psikoseksüel dönem aşağıdakilerden hangisidir?', secenekler:{A:'Genital dönem',B:'Oral dönem',C:'Anal dönem',D:'Latens dönem',E:'Fallik dönem'}, dogruCevap:'D', aciklama:'Doğru cevap D\'dir çünkü latens dönemde (6-11 yaş) cinsel dürtüler bastırılır ve çocuk sosyal beceriler ile okul öğrenmesine odaklanır.', kaynak:{tur:'donemsonu',yil:2018,donem:'bahar'} },
  { id:'SOS114-047', unite:6, konu:'Öğrenme', soru:'Pavlov\'un Klasik Koşullanma Kuramına göre, köpeğin önüne et konulduğunda ağzının sulanması nasıl bir tepkidir?', secenekler:{A:'Koşullu uyaran',B:'Koşulsuz uyaran',C:'Nötr tepki',D:'Koşulsuz tepki',E:'Koşullu tepki'}, dogruCevap:'D', aciklama:'Doğru cevap D\'dir çünkü et (koşulsuz uyaran) karşısında ağız sulanması öğrenilmeden ortaya çıkan doğal bir tepkidir; bu koşulsuz tepkidir.', kaynak:{tur:'donemsonu',yil:2018,donem:'bahar'} },
  { id:'SOS114-048', unite:6, konu:'Öğrenme', soru:'Edimsel Koşullanma Kuramı aşağıdakilerden hangisine aittir?', secenekler:{A:'Thorndike',B:'Köhler',C:'Bandura',D:'Watson',E:'Skinner'}, dogruCevap:'E', aciklama:'Doğru cevap E\'dir çünkü B.F. Skinner edimsel (operant) koşullanmayı geliştirmiştir. Thorndike etki yasasını, Pavlov klasik koşullanmayı, Bandura sosyal öğrenme kuramını geliştirmiştir.', kaynak:{tur:'donemsonu',yil:2018,donem:'bahar'} },
  { id:'SOS114-049', unite:5, konu:'Kişilik', soru:'Farklı durumlar ve zamanlarda bireyin ayırt edici davranış düzenlerini etkileyen karmaşık ve psikolojik nitelikler bütününe ne ad verilir?', secenekler:{A:'Kişilik',B:'Mizaç',C:'Huy',D:'Benlik',E:'Karakter'}, dogruCevap:'A', aciklama:'Doğru cevap A\'dır çünkü kişilik; farklı durum ve zamanlarda tutarlı biçimde ortaya çıkan, bireyi diğerlerinden ayıran psikolojik nitelikler bütünüdür.', kaynak:{tur:'donemsonu',yil:2018,donem:'bahar'} },
  { id:'SOS114-050', unite:5, konu:'Kişilik', soru:'Freud\'a göre aşağıdakilerden hangileri kişiliği oluşturan unsurlar arasında yer alır? (I. İd  II. Ego  III. Süper ego)', secenekler:{A:'Yalnız I',B:'Yalnız III',C:'I ve II',D:'II ve III',E:'I, II ve III'}, dogruCevap:'E', aciklama:'Doğru cevap E\'dir çünkü Freud\'a göre kişilik İd (ilkel dürtüler), Ego (gerçeklik ilkesi) ve Süper ego (ahlaki kurallar) olmak üzere üç yapıdan oluşur.', kaynak:{tur:'donemsonu',yil:2018,donem:'bahar'} },
  { id:'SOS114-051', unite:7, konu:'Stres', soru:'"Öğrenilmiş iyimserlik" kavramıyla iyimserliğin sonradan öğrenilebileceğini savunan bilim insanı aşağıdakilerden hangisidir?', secenekler:{A:'Selye',B:'Seligman',C:'Freud',D:'Lazarus',E:'Canon'}, dogruCevap:'B', aciklama:'Doğru cevap B\'dir çünkü Martin Seligman öğrenilmiş çaresizlik araştırmalarından yola çıkarak iyimserliğin de öğrenilebileceğini savunmuş ve pozitif psikolojinin kurucusu olmuştur.', kaynak:{tur:'donemsonu',yil:2018,donem:'bahar'} },
  { id:'SOS114-052', unite:7, konu:'Stres', soru:'Organizmanın stresörle savaştığı ve onu yenmeye çalıştığı genel adaptasyon süreci aşaması aşağıdakilerden hangisidir?', secenekler:{A:'Güçlendirme',B:'Direnme',C:'Yabancılaşma',D:'Alarm',E:'Tükenme'}, dogruCevap:'B', aciklama:'Doğru cevap B\'dir çünkü Selye\'nin Genel Adaptasyon Sendromunda ikinci aşama olan direnme, organizmanın stresörle aktif olarak mücadele ettiği dönemdir. Alarm ilk tepki, tükenme ise kaynakların bitmesi aşamasıdır.', kaynak:{tur:'donemsonu',yil:2018,donem:'bahar'} },
  { id:'SOS114-053', unite:8, konu:'Tutumlar ve Sosyal Etki', soru:'Önyargıların davranışa dönüşmüş haline ne ad verilir?', secenekler:{A:'Cam tavan',B:'Mobbing',C:'Cam uçurum',D:'Ayrımcılık',E:'Gürültü'}, dogruCevap:'D', aciklama:'Doğru cevap D\'dir çünkü önyargı zihinsel bir yargılama iken ayrımcılık bu yargının davranışa yansımasıdır; birine gruba üyeliği nedeniyle farklı davranmaktır.', kaynak:{tur:'donemsonu',yil:2018,donem:'bahar'} },
  { id:'SOS114-054', unite:7, konu:'Stres', soru:'Canan, çok sevdiği arkadaşı Pelin ile buluşup kahve içmek ile uzun zamandır vizyona girmesini beklediği sinema filmini izlemek arasında kararsızlık yaşıyor. Canan\'ın yaşadığı kişi içi çatışma türü aşağıdakilerden hangisidir?', secenekler:{A:'Kaçınma-kaçınma',B:'Yaklaşma-yaklaşma',C:'Yaklaşma-kaçınma',D:'Kaçınma-uzaklaşma',E:'Yaklaşma-uzaklaşma'}, dogruCevap:'B', aciklama:'Doğru cevap B\'dir çünkü her iki seçenek de (kahve ve sinema) olumlu ve cazip; iki çekici seçenek arasında kalmak yaklaşma-yaklaşma çatışmasıdır.', kaynak:{tur:'donemsonu',yil:2018,donem:'bahar'} },
  { id:'SOS114-055', unite:8, konu:'Tutumlar ve Sosyal Etki', soru:'Kişinin herhangi bir şey hakkında nasıl davranması gerektiğini belirleyen, o şey hakkındaki hisleri, inanışları ve düşünceleri toplamına ne ad verilir?', secenekler:{A:'Tutum',B:'Bellek',C:'Değer',D:'Biliş',E:'Duygu'}, dogruCevap:'A', aciklama:'Doğru cevap A\'dır çünkü tutum; bir nesne, kişi veya duruma yönelik hisler, düşünceler ve davranış eğilimlerini kapsayan psikolojik yapıdır.', kaynak:{tur:'donemsonu',yil:2018,donem:'bahar'} },
  { id:'SOS114-056', unite:5, konu:'Kişilik', soru:'Evliliğinde problemler olan bir kişinin kendi evliliğindeki problemleri çözmeye çalışmak yerine evliliklerdeki problemleri anlamaya çalışması aşağıdaki savunma mekanizmalarından hangisine bir örnektir?', secenekler:{A:'Entellektüalizasyon',B:'Regresyon',C:'Bastırma',D:'Yüceltme',E:'Yansıtma'}, dogruCevap:'A', aciklama:'Doğru cevap A\'dır çünkü entellektüalizasyon, duygusal sıkıntıyı soyut düşünce ve entelektüel analize kaçarak yönetme savunma mekanizmasıdır. Kişi kendi sorununu teorik düzeyde inceleyerek duygusal acıdan uzaklaşır.', kaynak:{tur:'donemsonu',yil:2018,donem:'bahar'} },
  { id:'SOS114-057', unite:8, konu:'Tutumlar ve Sosyal Etki', soru:'Kişilerden söz konusu tutuma yönelik ifadelerini 1\'den 5\'e kadar sıralanan ve farklı katılım derecelerini ifade eden bir skala üzerinde değerlendirmeleri istenen ölçek tipi aşağıdakilerden hangisidir?', secenekler:{A:'Bogardus ölçeği',B:'Likert ölçeği',C:'Guthrie ölçeği',D:'Thurstone ölçeği',E:'Osgood ölçeği'}, dogruCevap:'B', aciklama:'Doğru cevap B\'dir çünkü Likert ölçeği "kesinlikle katılmıyorum"dan "kesinlikle katılıyorum"a uzanan 5\'li derecelendirme ölçeğidir; tutum ölçümünde en yaygın kullanılan yöntemdir.', kaynak:{tur:'donemsonu',yil:2018,donem:'bahar'} },
  { id:'SOS114-058', unite:8, konu:'Tutumlar ve Sosyal Etki', soru:'Bireyin kendisinin de içinde bulunduğu sosyal gruba yönelik negatif yargılar sonucunda ortaya çıkan olumsuz durumları ifade eden kavram aşağıdakilerden hangisidir?', secenekler:{A:'Dolaylı tutum',B:'Çift tutum',C:'Kalıpyargı tehdidi',D:'Çelişkili ayrımcılık',E:'Sosyal kategorilendirme'}, dogruCevap:'C', aciklama:'Doğru cevap C\'dir çünkü kalıpyargı tehdidi, bireyin kendi grubuna ilişkin olumsuz kalıpyargıları doğrulayabileceği kaygısıyla performansının düşmesi durumudur.', kaynak:{tur:'donemsonu',yil:2018,donem:'bahar'} },

  // 2019 dönemsonu (20 soru)
  { id:'SOS114-059', unite:2, konu:'Algı', soru:'Hareketin, sabit nesne imgelerinin hızlı bir biçimde arka arkaya sunulmasıyla oluşturulduğu görünürde hareket türü aşağıdakilerden hangisidir?', secenekler:{A:'Tamamlama ilkesi',B:'Gerçek hareket',C:'Yakınlık ilkesi',D:'Stroboskopik hareket',E:'Süreklilik ilkesi'}, dogruCevap:'D', aciklama:'Doğru cevap D\'dir çünkü stroboskopik hareket (phi fenomeni), hızla arka arkaya gösterilen durağan görüntülerin hareket ediyormuş gibi algılanmasıdır; sinema ve animasyonun temelini oluşturur.', kaynak:{tur:'donemsonu',yil:2019,donem:'bahar'} },
  { id:'SOS114-060', unite:4, konu:'Güdülenme', soru:'Bir sınavda gereğinden fazla heyecanlanan bir kişinin başarısız olabileceğini savunan güdülenme kuramı aşağıdakilerden hangisidir?', secenekler:{A:'Dürtü kuramı',B:'Dürtü azalması kuramı',C:'Optimal uyarılma kuramı',D:'İhtiyaçlar hiyerarşisi kuramı',E:'İçgüdü kuramı'}, dogruCevap:'C', aciklama:'Doğru cevap C\'dir çünkü optimal uyarılma kuramına göre performans orta düzeyde uyarılmada en iyidir; çok az veya çok fazla heyecan (uyarılma) başarıyı düşürür. Bu Yerkes-Dodson yasasıyla da açıklanır.', kaynak:{tur:'donemsonu',yil:2019,donem:'bahar'} },
  { id:'SOS114-061', unite:3, konu:'Düşünme ve Problem Çözme', soru:'Matematikteki Pisagor formülü aşağıdakilerden hangisine bir örnektir?', secenekler:{A:'Alt amaç analizi',B:'Araçlar ve amaç analizi',C:'Geriye doğru çalışma',D:'Algoritma',E:'Kestirme'}, dogruCevap:'D', aciklama:'Doğru cevap D\'dir çünkü algoritma, adım adım izlendiğinde kesinlikle doğru sonuca ulaşan problem çözme yöntemidir. Pisagor formülü her dik üçgende kesin sonuç verir.', kaynak:{tur:'donemsonu',yil:2019,donem:'bahar'} },
  { id:'SOS114-062', unite:1, konu:'Psikoloji Bakış Açıları', soru:'Pavlov\'un köpeklerle yapılan deneyi ile oluşturulan Klasik Koşullanma Kuramı\'nın temsil ettiği bakış açısı aşağıdakilerden hangisidir?', secenekler:{A:'Sosyo-kültürel',B:'Hümanistik',C:'Psikodinamik',D:'Davranışsal',E:'Biyolojik'}, dogruCevap:'D', aciklama:'Doğru cevap D\'dir çünkü Pavlov\'un klasik koşullanma araştırmaları davranışçı (behaviorist) bakış açısının temel taşlarındandır; gözlemlenebilir uyarıcı-tepki ilişkilerine odaklanır.', kaynak:{tur:'donemsonu',yil:2019,donem:'bahar'} },
  { id:'SOS114-063', unite:6, konu:'Öğrenme', soru:'Tolman\'ın en önemli çalışması olan ve öğrenildiği halde bireyin davranışlarında görülmeyen ancak teşvik edici bir ortamda ortaya çıkan davranışlar olarak tanımlanan kavram aşağıdakilerden hangisidir?', secenekler:{A:'Gizil öğrenme',B:'Koşulsuz öğrenme',C:'Koşullu öğrenme',D:'Algısal öğrenme',E:'İşlevsel öğrenme'}, dogruCevap:'A', aciklama:'Doğru cevap A\'dır çünkü Tolman\'ın labirent deneyleri gizil öğrenmeyi ortaya koymuştur: fareler ödül olmadan da labirenti öğrenmiş, ödül verilince bu öğrenme davranışa yansımıştır.', kaynak:{tur:'donemsonu',yil:2019,donem:'bahar'} },
  { id:'SOS114-064', unite:5, konu:'Kişilik', soru:'Beş faktör kişilik modeline göre bireyin sürekli yeni ve farklı olana ilgi duyması ile ilgili olan kişilik özelliği aşağıdakilerden hangisidir?', secenekler:{A:'Uyumluluk',B:'Sorumluluk',C:'Dışa dönüklük',D:'Nevrotizm',E:'Deneyime açıklık'}, dogruCevap:'E', aciklama:'Doğru cevap E\'dir çünkü deneyime açıklık boyutu yeni deneyimlere, fikirlere ve değişime ilgi duymayı kapsar; meraklı ve hayal gücü geniş bireyler bu boyutta yüksek puan alır.', kaynak:{tur:'donemsonu',yil:2019,donem:'bahar'} },
  { id:'SOS114-065', unite:6, konu:'Öğrenme', soru:'Bir bölgenin mekansal düzenine ilişkin zihinsel temsiline ne ad verilir?', secenekler:{A:'Gizil öğrenme',B:'Bilişsel harita',C:'Bitişiklik',D:'Pekiştirme',E:'Kategorileştirme'}, dogruCevap:'B', aciklama:'Doğru cevap B\'dir çünkü Tolman tarafından ortaya atılan bilişsel harita kavramı, bir ortamın zihinsel olarak temsil edilmesidir; bu sayede canlılar çevreyi gözlemeden de yön bulabilir.', kaynak:{tur:'donemsonu',yil:2019,donem:'bahar'} },
  { id:'SOS114-066', unite:5, konu:'Kişilik', soru:'Freud\'a göre 6-11 yaş dönemindeki çocukların dürtülerini ve isteklerini kontrol etmeyi öğrendiği psikoseksüel aşama aşağıdakilerden hangisidir?', secenekler:{A:'Anal',B:'Genital',C:'Latens',D:'Oral',E:'Fallik'}, dogruCevap:'C', aciklama:'Doğru cevap C\'dir çünkü latens dönemde cinsel dürtüler bastırılır, çocuk akademik ve sosyal becerilere odaklanır. Bu dönem ilkokul yıllarına (6-11 yaş) denk gelir.', kaynak:{tur:'donemsonu',yil:2019,donem:'bahar'} },
  { id:'SOS114-067', unite:5, konu:'Kişilik', soru:'Jung\'a göre "persona" kavramının temel işlevi aşağıdakilerden hangisidir?', secenekler:{A:'Toplumda onay görmek',B:'Benliğini geliştirmek',C:'Özgüven kazanmak',D:'Girişken olmak',E:'Lider olmak'}, dogruCevap:'A', aciklama:'Doğru cevap A\'dır çünkü Jung\'un "persona" kavramı, bireyin topluma karşı taktığı sosyal maskedir; toplumda kabul görmek ve onay almak için sergilenen kamusal kimliği ifade eder.', kaynak:{tur:'donemsonu',yil:2019,donem:'bahar'} },
  { id:'SOS114-068', unite:6, konu:'Öğrenme', soru:'Pavlov\'un Klasik Koşullanma Modeli\'ne göre koşullu ve koşulsuz uyaranın birlikte verilmesiyle elde edilen ve koşullu uyarana yönelik öğrenilmiş tepkiye ne ad verilir?', secenekler:{A:'Sönme',B:'Koşulsuz tepki',C:'Genelleme',D:'Koşullu tepki',E:'Pekiştirme'}, dogruCevap:'D', aciklama:'Doğru cevap D\'dir çünkü koşullu tepki, başlangıçta nötr olan uyarana (zil) koşullanma sonucunda öğrenilmiş tepkidir (ağız sulanması). Koşulsuz tepkiden farklı olarak öğrenme gerektirir.', kaynak:{tur:'donemsonu',yil:2019,donem:'bahar'} },
  { id:'SOS114-069', unite:6, konu:'Öğrenme', soru:'Edimsel Koşullanma Kuramı aşağıdakilerden hangisine aittir?', secenekler:{A:'Köhler',B:'Bandura',C:'Skinner',D:'Watson',E:'Thorndike'}, dogruCevap:'C', aciklama:'Doğru cevap C\'dir çünkü B.F. Skinner, pekiştirme ve ceza yoluyla davranışın şekillendirilmesini açıklayan Edimsel (Operant) Koşullanma Kuramını geliştirmiştir.', kaynak:{tur:'donemsonu',yil:2019,donem:'bahar'} },
  { id:'SOS114-070', unite:5, konu:'Kişilik', soru:'Bilinçaltında yer alan ve doğuştan gelen ilkel arzuları içeren kişilik bileşeni aşağıdakilerden hangisidir?', secenekler:{A:'Süper ego',B:'Mizaç',C:'Ego',D:'Treyt',E:'İd'}, dogruCevap:'E', aciklama:'Doğru cevap E\'dir çünkü Freud\'a göre İd, doğuştan gelen ve zevk ilkesiyle çalışan bilinçdışı kişilik yapısıdır; ilkel dürtü ve arzuları barındırır.', kaynak:{tur:'donemsonu',yil:2019,donem:'bahar'} },
  { id:'SOS114-071', unite:7, konu:'Stres', soru:'Genel adaptasyon sendromuna göre organizmanın stresörle mücadele ettiği ve onu yenmeye çalıştığı aşama aşağıdakilerden hangisidir?', secenekler:{A:'Uyum',B:'Çatışma',C:'Direnme',D:'Alarm',E:'Tükenme'}, dogruCevap:'C', aciklama:'Doğru cevap C\'dir çünkü Selye\'nin Genel Adaptasyon Sendromunun ikinci aşaması olan direnme, vücudun stresörle aktif mücadele ettiği dönemdir. Alarm ilk şok tepkisidir, tükenme ise kaynakların bitmesidir.', kaynak:{tur:'donemsonu',yil:2019,donem:'bahar'} },
  { id:'SOS114-072', unite:8, konu:'Tutumlar ve Sosyal Etki', soru:'Herhangi bir tutum objesine ilişkin birbirine zıt sıfat çiftleri ve bu sıfat çiftleri arasında 5\'li veya 7\'li aralıklar kullanılarak oluşturulan ölçek aşağıdakilerden hangisidir?', secenekler:{A:'Bogardus ölçeği',B:'Osgood\'un duygusal anlam ölçeği',C:'Skinner ölçeği',D:'Thurstone ölçeği',E:'Likert ölçeği'}, dogruCevap:'B', aciklama:'Doğru cevap B\'dir çünkü Osgood\'un semantik fark (duygusal anlam) ölçeği, zıt sıfat çiftleri (iyi-kötü, güçlü-zayıf) arasında derecelendirme yapmaya dayanır.', kaynak:{tur:'donemsonu',yil:2019,donem:'bahar'} },
  { id:'SOS114-073', unite:5, konu:'Kişilik', soru:'Evliliğinde problemler olan bir kişinin kendi evliliğindeki problemleri çözmeye çalışmak yerine evliliklerdeki problemleri anlamaya çalışması aşağıdaki savunma mekanizmalarından hangisine bir örnektir?', secenekler:{A:'Entelektüalizasyon',B:'Bastırma',C:'Yansıtma',D:'Regresyon',E:'Yüceltme'}, dogruCevap:'A', aciklama:'Doğru cevap A\'dır çünkü entelektüalizasyon, kişisel duygusal sorunu soyut ve teorik düzeyde ele alarak duygusal acıdan uzaklaşma savunma mekanizmasıdır.', kaynak:{tur:'donemsonu',yil:2019,donem:'bahar'} },
  { id:'SOS114-074', unite:8, konu:'Tutumlar ve Sosyal Etki', soru:'ABC Modeli\'ne göre aşağıdakilerden hangileri tutum bileşenleri arasında yer alır? (I. Duygu  II. Biliş  III. Davranış niyeti)', secenekler:{A:'Yalnız I',B:'Yalnız III',C:'I ve II',D:'II ve III',E:'I, II ve III'}, dogruCevap:'E', aciklama:'Doğru cevap E\'dir çünkü ABC modeline göre tutumun üç bileşeni vardır: Duygu (Affect), Biliş (Belief/Cognition) ve Davranış niyeti (Conation). Üçü birlikte tutumu oluşturur.', kaynak:{tur:'donemsonu',yil:2019,donem:'bahar'} },
  { id:'SOS114-075', unite:7, konu:'Stres', soru:'Girişkenliğin yüksek, işbirliğinin düşük olduğu çatışmayla başa çıkma stili aşağıdakilerden hangisidir?', secenekler:{A:'Kaçınma',B:'Rekabet',C:'Uyum',D:'Ortak çalışma',E:'Uzlaşma'}, dogruCevap:'B', aciklama:'Doğru cevap B\'dir çünkü rekabet stili yüksek girişkenlik ve düşük işbirliği ile karakterizedir; kişi kendi çıkarlarını ön plana alarak çatışmayı kazanmaya çalışır.', kaynak:{tur:'donemsonu',yil:2019,donem:'bahar'} },
  { id:'SOS114-076', unite:8, konu:'Tutumlar ve Sosyal Etki', soru:'Kişinin tutumu ile kendisinden beklenen davranışın birbirinden farklı olması durumunda ortaya çıkan kavram aşağıdakilerden hangisidir?', secenekler:{A:'Bilişsel karmaşa',B:'Sönme',C:'Koşulsuz tepki',D:'Sosyal yargı',E:'Kalıpyargı tehdidi'}, dogruCevap:'A', aciklama:'Doğru cevap A\'dır çünkü bilişsel karmaşa (çelişki/tutarsızlık), tutum ile davranış arasındaki uyumsuzluktan kaynaklanan rahatsızlık durumudur; Festinger\'ın bilişsel çelişki kuramıyla da açıklanır.', kaynak:{tur:'donemsonu',yil:2019,donem:'bahar'} },
  { id:'SOS114-077', unite:7, konu:'Stres', soru:'Erdem, birlikte vakit geçirmekten hoşlanmadığı bir akrabasını ziyaret etmek ile sevmediği bir dersin projesini hazırlamak arasında çatışma yaşamaktadır. Erdem\'in yaşadığı kişi içi çatışması aşağıdakilerden hangisidir?', secenekler:{A:'Yaklaşma-kaçınma',B:'Kaçınma-kaçınma',C:'Yansıtma',D:'Regresyon',E:'Yaklaşma-yaklaşma'}, dogruCevap:'B', aciklama:'Doğru cevap B\'dir çünkü her iki seçenek de (istenmeyen akraba ziyareti ve sevilmeyen proje) olumsuz; iki kaçınılmak istenen şey arasında kalmak kaçınma-kaçınma çatışmasıdır.', kaynak:{tur:'donemsonu',yil:2019,donem:'bahar'} },
  { id:'SOS114-078', unite:8, konu:'Tutumlar ve Sosyal Etki', soru:'Bireyin kendisinin de içinde bulunduğu sosyal gruba yönelik olumlu yargılar sonucunda ortaya çıkan olumlu durumları ifade eden kavram aşağıdakilerden hangisidir?', secenekler:{A:'Ayrımcılık',B:'Önyargı',C:'Kalıpyargı tehdidi',D:'Çift tutum',E:'Kalıpyargı avantajı'}, dogruCevap:'E', aciklama:'Doğru cevap E\'dir çünkü kalıpyargı avantajı, kişinin ait olduğu gruba yönelik olumlu kalıpyargıların performansını artırdığı durumu ifade eder; kalıpyargı tehdidin tam tersidir.', kaynak:{tur:'donemsonu',yil:2019,donem:'bahar'} },
];

const mevcutIdler = new Set(data.map(s => s.id));
const eklenecek = yeni.filter(s => !mevcutIdler.has(s.id));

eklenecek.forEach(s => {
  s.dersKodu = 'SOS114U';
  s.dersAdi = 'Davranış Bilimleri II';
  s.soruTipi = 'çıkmış_soru';
  s.guvenDurumu = 'kontrol_edildi';
  s.kontrolEden = 'gorsel_okuma';
  s.aciklama = s.aciklama || '';
  s.nedenDigerleriDegil = '';
  s.ogretimNotu = '';
});

const yeniData = [...data, ...eklenecek];
fs.writeFileSync(dataPath, JSON.stringify(yeniData, null, 2), 'utf8');

const sos = yeniData.filter(s => s.dersKodu === 'SOS114U');
console.log(`✓ Toplam ${yeniData.length} soru. SOS114U: ${sos.length} soru (${sos.filter(s=>s.guvenDurumu==='kontrol_edildi').length} kontrol_edildi)`);
